### ISSUE TITLE
Add `cstr!` macro for creating `&'static CStr`s.

### ISSUE THREAD

**Issue by reitermarkus** [rust-lang/libs-team#103]
# Proposal

## Problem statement

Now that `core::ffi::CStr` is stabilized, there should be an ergonomic way to create `&CStr` constants.

## Motivation, use-cases

On stable there is currently no good way to create a `&'static CStr`, the simplest solution needs `unsafe`, i.e. 

```rust
const MY_C_STRING: &CStr = unsafe { CStr::from_bytes_with_nul_unchecked(b"Hello, world!\0") };
```

On nightly, it is possible since https://github.com/rust-lang/rust/pull/100291 without `unsafe`, but these are even more verbose or don't provide meaningful error messages:

```rust
#![feature(const_cstr_methods)]

const MY_C_STRING: &CStr = if let Ok(s) = CStr::from_bytes_with_nul(b"Hello, world!\0") {
    s
} else {
    panic!("contains interior nul bytes")
};
```

```rust
#![feature(const_cstr_methods)]
#![feature(const_option)]

const MY_C_STRING: &CStr = CStr::from_bytes_with_nul(b"Hello, world!\0").ok().unwrap();
```

## Solution sketches

With a `cstr!`, the example above becomes both easier to write and easier to read, i.e.

```rust
const MY_C_STRING: &CStr = cstr!("Hello, world!");
```

## Links and related work

- The `cstr_core` crate contains such a macro: https://docs.rs/cstr_core/0.2.6/cstr_core/macro.cstr.html
- The `cstr` crate provides such a macro: https://docs.rs/cstr/0.2.10/cstr/index.html
- Pull request adding this as `core::ffi::cstr` is here: https://github.com/rust-lang/rust/pull/101607

## What happens now?

This issue is part of the libs-api team [API change proposal process]. Once this issue is filed the libs-api team will review open proposals in its weekly meeting. You should receive feedback within a week or two.

[API change proposal process]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html

**Comment by thomcc** [comment]
I'm broadly in favor of this -- it's worth considering what syntax we'd want for this under https://github.com/rust-lang/rfcs/pull/3267 (although, I guess I'm unsure the future that RFC has).

**Comment by m-ou-se** [comment]
I've nominated https://github.com/rust-lang/rust/pull/101607 for lang team discussion, to discuss the `c"abc"` alternative.

**Comment by m-ou-se** [comment]
I've opened https://github.com/rust-lang/rfcs/pull/3348 as an alternative.

**Comment by SUPERCILEX** [comment]
I actually just ran into this! I'll echo Thom about broadly wanting this and say that I'd prefer Mara's solution over a macro, but would settle for either.

**Comment by m-ou-se** [comment]
Closing this, because https://github.com/rust-lang/rfcs/pull/3348 has been accepted.
