### ISSUE TITLE
ACP: Negation functions for `NonZeroI*`

### ISSUE THREAD

**Issue by jmillikin** [rust-lang/libs-team#105]
# Proposal

## Problem statement

Integer primitives have functions such as `overflowing_neg()` for numeric negation with controlled overflow. These functions are currently missing from the `core::num::NonZeroI{8,16,32,64}` types.

## Motivation, use-cases

Non-zero integers are frequently used to represent error codes from low-level OS APIs, because these APIs use `0` to indicate non-error. Some APIs use signed error codes as a form of namespacing, such as internal/public (FreeBSD) or kernel/userspace (Linux).

For example, the FUSE protocol uses userspace error codes (positive non-zero) but negates them when sending an error frame to the kernel.

```rust
// old
let (neg, _) = err.get().overflowing_neg();
let wire_neg = unsafe { NonZeroI32::new_unchecked(neg) };

// new
let (wire_neg, _) = err.overflowing_neg();
```

## Solution sketches

Since the primitive integer types already have `*_neg()` functions, and negation can't return zero for non-zero inputs, writing wrappers for the non-zero integers is straightforward.

```rust

pub const fn is_negative(self) -> bool {
    self.get().is_negative()
}

pub const fn checked_neg(self) -> Option<$Ty> {
    if let Some(result) = self.get().checked_neg() {
        return Some(unsafe { $Ty::new_unchecked(result) });
    }
    None
}

pub const fn overflowing_neg(self) -> ($Ty, bool) {
    let (result, overflow) = self.get().overflowing_neg();
    ((unsafe { $Ty::new_unchecked(result) }), overflow)
}

pub const fn saturating_neg(self) -> $Ty {
    if let Some(result) = self.checked_neg() {
        return result;
    }
    unsafe { $Ty::new_unchecked(<$Int>::MAX) }
}

pub const fn wrapping_neg(self) -> $Ty {
    let result = self.get().wrapping_neg();
    unsafe { $Ty::new_unchecked(result) }
}
```

## Links and related work

https://github.com/rust-lang/rust/issues/89065
https://github.com/rust-lang/rust/issues/84186

## What happens now?

This issue is part of the libs-api team [API change proposal process]. Once this issue is filed the libs-api team will review open proposals in its weekly meeting. You should receive feedback within a week or two.

[API change proposal process]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html

**Comment by jmillikin** [comment]
Proposed implementation: https://github.com/jmillikin/upstream__rust/commit/a807a2d17298c4ff0fb61fc3f138675503ae0932

Docs screenshots:

![nonzero-negation-1](https://user-images.githubusercontent.com/646128/190882439-098da843-7025-4283-87e8-e257b4e8b242.png)

![nonzero-negation-2](https://user-images.githubusercontent.com/646128/190882441-264ff307-4380-4e27-aa3b-f1d5040fce1f.png)

![nonzero-negation-3](https://user-images.githubusercontent.com/646128/190882443-272c4779-6816-412f-aa5d-50fb3af73fee.png)

![nonzero-negation-4](https://user-images.githubusercontent.com/646128/190882444-c156dd71-8655-47dd-987f-2743d2a540ac.png)

![nonzero-negation-5](https://user-images.githubusercontent.com/646128/190882445-dad607b9-a33c-4d73-8897-40fe12921216.png)

**Comment by cuviper** [comment]
How about `trait Neg` for the operator?

**Comment by jmillikin** [comment]
> How about `trait Neg` for the operator?

It's easy to implement, but my understanding is that trait impls for two stable types can't be marked `unstable` due to <https://github.com/rust-lang/rust/issues/55436>.

```rust
#[unstable(feature = "nonzero_negation_ops", issue = "none")]
#[rustc_const_unstable(feature = "const_ops", issue = "90080")]
impl const Neg for $Ty {
    type Output = Self;

    #[inline]
    fn neg(self) -> Self {
        unsafe { $Ty::new_unchecked(Neg::neg(self.get())) }
    }    
}
```

```
error: an `#[unstable]` annotation here has no effect
   --> library/core/src/num/nonzero.rs:877:13
[...]
    = note: `#[deny(ineffective_unstable_trait_impl)]` on by default
    = note: see issue #55436 <https://github.com/rust-lang/rust/issues/55436> for more information
```

**Comment by thomcc** [comment]
That's not a deal-breaker if the trait implementation is sensible/desirable.

**Comment by jmillikin** [comment]
I agree that `Neg` would be useful, have no strong opinion on the exact details of the stabilization process, and would be happy to do whatever the Rust libc team recommends in this case.

**Comment by scottmcm** [comment]
Given that the signed nonzero types already have things like `checked_abs` and `overflowing_abs` and `saturating_mul` and such, adding things like `checked_neg` and `saturating_neg` seem well covered by existing precedent, so if you want to send a PR for the methods as unstable, you can `r? @scottmcm` on that and I'll approve it.  (They probably just weren't done originally because they don't make sense on the unsigned versions.)

Trait impls can't go in unstable, though, so that at least should be a different PR, and I'll leave it for a real libs-api member to comment on it.

**Comment by jmillikin** [comment]
OK, I've filed PR https://github.com/rust-lang/rust/pull/102341 to implement `Neg` for `NonZeroI*`.

To avoid merge conflicts, I'll send a second PR for the negation functions once that first one lands.

**Comment by scottmcm** [comment]
Traits take at least 10 days for FCP, so that PR will take much longer to land than one for unstable inherent methods.

**Comment by jmillikin** [comment]
> Traits take at least 10 days for FCP, so that PR will take much longer to land than one for unstable inherent methods.

Interesting. OK, filed https://github.com/rust-lang/rust/pull/102342 to add the new methods. Once one of them merges I'll rebase the second one.
