### ISSUE TITLE
Nominating things for discussion

### ISSUE THREAD

**Issue by KodrAus** [rust-lang/libs-team#11]
When we're not doing triage meetings would we like to determine our agenda by nominating topics opened as issues here? I think that's roughly how the Compiler team does things. That might give us a platform to raise bigger things for Libs discussion.

cc @rust-lang/libs

**Comment by m-ou-se** [comment]
Nominated issues on this repository now also show up in the agenda. Currently we don't seem to have the need to schedule dedicated meetings for a single topic.
