### ISSUE TITLE
ACP: Add a constant for the golden ratio (phi) to the floating point types

### ISSUE THREAD

**Issue by H4x5** [rust-lang/libs-team#119]
# Proposal

## Problem statement

The `std::f64::consts` module (and its friend `std::f32::consts`) currently contain constants for e (euler's number) and pi, along with some others (ln(2), 1/sqrt(2), etc). These are a subset of the [ones in C++](https://en.cppreference.com/w/cpp/numeric/constants), although C++ also includes phi (φ), the [golden ratio](https://en.wikipedia.org/wiki/Golden_ratio).

I am proposing to add a `PHI` constant to the standard library, in similar fashion to the existing floating point constants.

## Motivation, use-cases

From a math expression parsing library I'm working on:
```rust
use std::f64;

enum MathConst {
    E, // euler's number
    Pi, // pi
    Phi, // golden ratio
}

impl From<MathConst> for f64 {
    fn from(value: MathConst) -> f64 {
        match value {
            MathConst::E => f64::consts::E,
            MathConst::Pi => f64::consts::PI,
            MathConst::Phi => f64::consts::PHI, // not a thing :(
        }
    }
}
```

## Solution sketches

In `core/src/num/f64.rs`:

```rust
pub mod consts {
    // ...    

    /// The golden ratio (φ)
    pub const PHI: f64 = 1.618033988749894848204586834365638118_f64;
    
    // ...
}
```

In `core/src/num/f32.rs`:

```rust
pub mod consts {
    // ...    

    /// The golden ratio (φ)
    pub const PHI: f64 = 1.618033988749894848204586834365638118_f32;
    
    // ...
}
```

## Links and related work

- An [RFC discussion](https://github.com/rust-lang/rfcs/issues/1486) on the addition of the `TAU` constant (with some mentions of phi)
- [cppreference.com `<numbers>` header](https://en.cppreference.com/w/cpp/numeric/constants)
- [libstdc++ `inline constexpr double phi`](https://github.com/gcc-mirror/gcc/blob/16e2427f50c208dfe07d07f18009969502c25dc8/libstdc%2B%2B-v3/include/std/numbers#L120)

## What happens now?

This issue is part of the libs-api team [API change proposal process]. Once this issue is filed the libs-api team will review open proposals in its weekly meeting. You should receive feedback within a week or two.

[API change proposal process]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html

**Comment by cuviper** [comment]
> These are a subset of the [ones in C++](https://en.cppreference.com/w/cpp/numeric/constants), although C++ also includes phi (φ), the [golden ratio](https://en.wikipedia.org/wiki/Golden_ratio).

Maybe we should go ahead and add _all_ that we're missing?

**Comment by joshtriplett** [comment]
We reviewed this in today's @rust-lang/libs-api meeting, and we're fine with adding all five of the additional constants C++ has in that table (the five added by https://github.com/rust-lang/rust/issues/103883).
