### ISSUE TITLE
`unwrap!`-everything

### ISSUE THREAD

**Issue by SoniEx2** [rust-lang/libs-team#127]
# Proposal

## Problem statement

Maybe you wanna unwrap a `Result` without `Debug`, or a custom type that doesn't even represent an error but maybe represents a state machine and you wanna assume you're in a specific state and grab the values inside of it. The `unwrap!`-everything API would allow exactly that.

## Motivation, use-cases

We wrote this like 5 times before making it a function:

```rust
    fn key_subtree(&self) -> Option<usize> {
        if let PatternElement::Tag { key_subtree } = self.op() {
            key_subtree
        } else {
            unreachable!()
        }
    }
```

And we have... multiple places where we use this exact pattern.

## Solution sketches

We'd like to see some sort of `unwrap!` macro which basically asserts the expectation and returns the relevant results:

```rust
let x = unwrap!(Err(e) = result);
let y = unwrap!(Ok(v) = no_debug_result);
let z = unwrap!(PatternElement::Tag { key_subtree } = frame.op());
let w = unwrap!([a, ..] = my_slice);
unwrap!(None = my_option);
```

Tho we acknowledge we haven't thought about how this would interact with multiple results like so:

```rust
let _ = unwrap!([a, b, ..] = my_slice);
```

Maybe it should look more like this instead?

```rust
let x = unwrap!(Err(use) = result);
let y = unwrap!(Ok(use) = no_debug_result);
let z = unwrap!(PatternElement::Tag { key_subtree: use } = frame.op()); // actually wait is it field: pattern or pattern: field?
let w = unwrap!([use, ..] = my_slice);
unwrap!(None = my_option);
unwrap!(let [a, b, ..] = my_slice); // ?
```

## Links and related work

https://doc.rust-lang.org/std/index.html?search=unwrap

## What happens now?

This issue is part of the libs-api team [API change proposal process]. Once this issue is filed the libs-api team will review open proposals in its weekly meeting. You should receive feedback within a week or two.

[API change proposal process]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html

**Comment by thomcc** [comment]
The new `let...else` feature, stabilizing in the next release of Rust, allows
```rs
let PatternElement::Tag { key_subtree } = frame.op() else {
    unreachable!()
};
// use `key_subtree`...
```
which should reduce the need for something like this a lot.

**Comment by truppelito** [comment]
There's also the crate [enum-as-inner](https://crates.io/crates/enum-as-inner) which I believe would allow:

`let key_subtree = frame.op().as_tag().unwrap()`

(or something similar, my apologies if this is not 100% correct, I'm not looking in detail at the docs for the crate right now)

**Comment by SoniEx2** [comment]
do any of those produce the nice panic messages that `unwrap!` would produce?

(which, fwiw, is better than what we have with `unreachable!()`. it'd actually be closer to those produced by `assert!`.)

**Comment by truppelito** [comment]
What exactly would `unwrap!`provide? Using `let else` the error message can be defined by what is placed in the `else` block. With the `enum-as-inner`, we can use `frame.op().into_tag().expect("message")`, although I will concede that both options are more verbose.

**Comment by SoniEx2** [comment]
using `assert!` (or `assert_eq!`) always provides a descriptive error message stating what went wrong.

while we don't exactly want the value after the `=` to be `Debug`, just seeing "this is the code that failed" (similar to an `assert!`) instead of "here's the line number that failed" would help a lot.

**Comment by cuviper** [comment]
Something like this?

```rust
macro_rules! unwrap {
    ($pattern:pat_param = $expression:expr) => {
        let $pattern = $expression else {
            panic!("unwrap failed: {}", stringify!($pattern = $expression));
        };
    }
}
```

**Comment by SoniEx2** [comment]
yes, tho we'd also like expression/value functionality (tho that's way harder ofc).

**Comment by cuviper** [comment]
How do you expect to see the value if you don't have `Debug`?

**Comment by SoniEx2** [comment]
no like `foo(unwrap!(...))` or `unwrap!(...).bar()`

**Comment by cuviper** [comment]
Ah -- I think we'd need a compiler builtin to extract arbitrary bindings from a pattern.

**Comment by SoniEx2** [comment]
Additional benefit of `unwrap!`-everything, is when side-effects and bools are involved:

```rust
assert!(self.interp.frames[target].prev()); // bad
self.interp.frames[target].prev().then(|| ()).unwrap(); // awkward but okay
unwrap!(true = self.interp.frames[target].prev()); // perfect
```

**Comment by dead-claudia** [comment]
How about just throwing most the unwrapping methods on `Try` much like how `Iterator` has a number of helper methods of its own?

```rs
trait Try: FromResidual<Self::Residual> {
    // ...

    fn unwrap(self) -> Self::Output {
        // Ideally, this would use some compiler magic to wire in the type name instead.
        match self.branch() {
            ControlFlow::Break(_) => panic!("called `Try::unwrap()` on a residual value"),
            ControlFlow::Continue(result) => result,
        }
    }

    fn unwrap_or_default(self) -> Self::Output where Self::Output: Default {
        match self.branch() {
            ControlFlow::Break(_) => Self::Wrapped::default(),
            ControlFlow::Continue(result) => result,
        }
    }

    fn unwrap_or(self, default: Self::Output) -> Self::Output {
        match self.branch() {
            ControlFlow::Break(_) => default,
            ControlFlow::Continue(result) => result,
        }
    }

    unsafe fn unwrap_unchecked(self) -> Self::Output {
        match self.branch() {
            ControlFlow::Break(_) => std::hint::unreachable_unchecked(),
            ControlFlow::Continue(result) => result,
        }
    }

    fn expect(self, msg: &str) -> Self::Output {
        match self.branch() {
            ControlFlow::Break(_) => panic!("{}", msg),
            ControlFlow::Continue(result) => result,
        }
    }

    fn map_or<U>(self, default: U, f: FnOnce(Self::Output) -> U) -> U {
        match self.branch() {
            ControlFlow::Break(_) => default,
            ControlFlow::Continue(result) => f(result),
        }
    }

    fn map_or_default<U: Default>(self, f: FnOnce(Self::Output) -> U) -> U {
        match self.branch() {
            ControlFlow::Break(_) => U::default(),
            ControlFlow::Continue(result) => f(result),
        }
    }
}

impl<T> Try for Option<T> {
    // ...

    fn unwrap(self) -> Self::Output {
        self.expect("called `Option::unwrap()` on a `None` value")
    }
}

impl<T, E: fmt::Debug> Try for Result<T, E> {
    // ...

    fn unwrap(self) -> Self::Output {
        self.expect("called `Result::unwrap()` on an `Err` value")
    }

    fn expect(self, msg: &str) -> Self::Output {
        match self {
            Err(e) => panic!("{}: {}", msg, e),
            Ok(result) => result,
        }
    }
}
```

This would merge large chunk of `Result` and `Option`'s APIs and would also allow other `Try` impls to gain it for free.

This does carry a major con, though: it'd make https://github.com/rust-lang/rust/issues/67441 depend on traits supporting const fns (in some capacity).

**Comment by SoniEx2** [comment]
`Try` doesn't apply to arbitrary enums, let alone arbitrary patterns. The use-case of `unwrap!` is *not* `Try`-like enums; rather the opposite, it's for when you make assumptions about plain data enums (sum types), and slices.

Op | Returns a value | Arbitrary patterns | Panics
--- | --- | --- | ---
`Try` | :heavy_check_mark: | :x: | :warning: 
`unwrap!` | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: 
`let-else` | :x: | :heavy_check_mark: | :x:

**Comment by the8472** [comment]
We discussed this in a libs meeting. While we do want to make traversal of data structures and patternmatching less cumbersome we have several blocking concerns about this particular proposal and thus are going to close it.

- We don't want to encourage uses of unwrap
- This is already served by let-else or if-let. If you have ideas how to improve ergonomics of let-else you could bring that up in a separate proposal
- The solution sketches lack clarity, this suggests that further discussion (e.g. in internals.rlo or zulip) is needed before bringing such a proposal to the libs team
