### ISSUE TITLE
Implement Step for NonZeroUxx

### ISSUE THREAD

**Issue by SOF3** [rust-lang/libs-team#130]
# Proposal

## Problem statement

Ranges of non-zero **unsigned** integers does not contain zero, and should be step-able.

## Motivation, use-cases

I want to iterate over a `Range<NonZeroUsize>`.

## Solution sketches

It might be tricky to implement `backward_checked` properly since we cannot guarantee that the input `usize` is less than `start`.

It is also inconsistent that NonZeroIxx are not implemented.

## What happens now?

This issue is part of the libs-api team [API change proposal process]. Once this issue is filed the libs-api team will review open proposals in its weekly meeting. You should receive feedback within a week or two.

[API change proposal process]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html

**Comment by SUPERCILEX** [comment]
If all you want to do is iterate, why can't you use the underlying type? Though in general I don't see a reason to not implement step, so this seems like a good idea.

In terms of the ACP, it should be mentioned that ranges need to implement step for them to be iterable, hence why this ACP is necessary.

**Comment by SOF3** [comment]
> If all you want to do is iterate, why can't you use the underlying type?

That's my alternative solution now.

https://github.com/SOF3/dynec/blob/bade2b3083f9348b740dd83e34af4478dadee353/src/entity/raw.rs#L68-L73

The range is used as a parameter to a `BTreeSet<NonZeroU32>`, which has a `range` associated function that accepts a `Range`. As for why it doesn't jus tcontain `BTreeSet<u32>`... I just want the types to be as explicit as possible.

**Comment by jalil-salame** [comment]
I posted about this in the [Internals Forum](https://internals.rust-lang.org/t/impl-range-and-rangeinclusive-for-nonzerou/18721).

There I state another (although a bit esoteric) use case: when solving Sudokus letting `0` mean an empty cell is quite natural, you can make it explicit using Option<NonZeroU*>, but when you want to iterate over the values, using the underlying type is painful, as stated before.

**Comment by SOF3** [comment]
In my use case, I was developing an ECS library where entity IDs are always nonzero (to optimize `Option<Entity>` memory usage), but I frequently have the need to iterate over a range of allocated entities (for SIMD purposes).

**Comment by marshrayms** [comment]
I was bitten by this today.
I need the NonZeroUxx value inside the iteration.

**Comment by khuey** [comment]
Is there a reason not to move forward on this or does it just need someone to actually do the work?

**Comment by the8472** [comment]
libs-api discusses change proposals during meetings, there's a backlog and people open new ones almost as fast as they get processes so it just takes a while.

In principle the ACP process is optional and one can make a PR instead, but then may be faced with the same questions about motivation, alternatives, etc. especially when the reviewer is unsure if the addition makes sense.

**Comment by m-ou-se** [comment]
We discussed this in the libs-api meeting. We're happy to see these impls added.

Feel free to open a PR to rust-lang/rust to add them, at which point we'll propose an FCP for official team confirmation before stabilziation.

**Comment by tyilo** [comment]
Is there any reason that `Step` wasn't also implemented for `NonZero<iN>` or `NonZero<char>`?

**Comment by jalil-salame** [comment]
> Is there any reason that `Step` wasn't also implemented for `NonZero<iN>` or `NonZero<char>`?

Because it was easier to start with `NonZero<u*>`, if there's a usecase for the other iterators then feel free to propose implementing `Step` for them.

**Comment by pitaj** [comment]
`NonZero<iN>` is a little controversial since it introduces an iterator with a hole, `NonZero<char>` isn't controversial at all

**Comment by cuviper** [comment]
`Step for char` already has an even larger hole for the surrogate range `0xD800..=0xDFFF`, but we deal with that. Of course `NonZero<char>` would have to skip that range as well.

We could do the same for signed integers to skip 0, so e.g. `nz(-1).forward(1) == nz(1)`.

**Comment by pitaj** [comment]
Right, I didn't mean that it introduces an iterator with a hole for the first time, just that it introduces more iterators with holes.

That's arguably more problematic for `NonZero<iN>` since `char` isn't really a numeric integer type, but `NonZero<iN>` are. Could be considered counter-intuitive.

My main point was just that `NonZero<char>` isn't controversial at all, so if you want it specifically, you might consider creating an ACP just for it so as to not get held up by concerns around the middle zero hole of `NonZero<iN>`
