### ISSUE TITLE
Remove drain-on-drop behavior from various DrainFilter iterators

### ISSUE THREAD

**Issue by the8472** [rust-lang/libs-team#136]
# Proposal

## Problem statement

The current implementations can double-panic (via a panic-drop-panic cascade), may become aborts even on a single panic if the deny panic-in-drop RFC goes through and are not consistent with general Iterator laziness.

## Motivation, use-cases

A panicking closure can lead to a double-panic while iterating. [Playground link](https://play.rust-lang.org/?version=nightly&mode=release&edition=2021&gist=06642239b38eec632937e2f38b01fd2c)

```rust
#![feature(drain_filter)]
use std::collections::LinkedList;

fn main() {
    let mut c = LinkedList::from([1, 2, 3]);
    let _c = c.drain_filter(|_| panic!("panic")).collect::<Vec<_>>();
}
```

## Solution sketches

Add `#[must_use]` and remove drain-on-drop behavior from the `drain_filter` impls for these collections:

* Vec
* LinkedList
* BTree{Map, Set}
* Hash{Map, Set}

Since it'll be redundant  needed it will also remove `vec::DrainFilter::keep_rest()`

Additionally `drain_filter` can be renamed to `extract_filter`🚲🏚️ to avoid similarity to `Drain` which will retain its drain-on-drop behavior since it's less problematic as it doesn't evaluate a closure for each item. To be bikeshed.

## Limitations

This may cause surprises with short-circuiting iterators. That can be worked around (unergonomically) by taking `by_ref` and then exhausting the rest once the main use is completed or by avoiding short-circuiting ops.

## Links and related work

* https://github.com/rust-lang/rust/pull/104455 (PR for the proposed change)
* https://github.com/rust-lang/hashbrown/pull/374
* https://github.com/rust-lang/rfcs/pull/3288 
* https://github.com/rust-lang/rust/issues/43244#issuecomment-641638196 (summary comment highlighting the issue)
* https://github.com/rust-lang/rust/issues/70530 (affected tracking issue)
* https://github.com/rust-lang/rust/issues/59618 (affected tracking issue)

## What happens now?

This issue is part of the libs-api team [API change proposal process]. Once this issue is filed the libs-api team will review open proposals in its weekly meeting. You should receive feedback within a week or two.

[API change proposal process]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html

**Comment by Amanieu** [comment]
Seconded. I think this is actually quite intuitive: only elements that are returned from the iterator are actually removed from the collection.

**Comment by Mark-Simulacrum** [comment]
I think renaming is a good idea, not least because the alternative is breaking people in a pretty subtle way as they upgrade their nightly version. (None of these are stable, right?)


Is the recommended pattern if you want the old behavior something like .for_each(|_| {}) to preserve performance? Or is there something better?

**Comment by the8472** [comment]
>  (None of these are stable, right?)

Correct.

> Is the recommended pattern if you want the old behavior something like .for_each(|_| {}) to preserve performance? Or is there something better?

For most collections there's a `retain` method and my PR [directs users to use it](https://github.com/rust-lang/rust/pull/104455/files#diff-ac12b4a99e8fbf983e99854a4c0600223f7183ac1180b48325cdf8f2594b25c4R1354-R1358) when they don't need the iterator.

Only linked-list doesn't have that. But there you can't do much better than `.for_each(drop)` anyway.

**Comment by Mark-Simulacrum** [comment]
Ah, I see. I guess we stabilized retain_mut on Vec too now. Still, the rename seems like a good idea to avoid future confusion and subtle breakage now, even if most users not actively iterating have a better path in retain today.

**Comment by the8472** [comment]
Sure. Any preferences?

* extract_if
* extract_filter{ed}
* take_if
* ...

**Comment by Mark-Simulacrum** [comment]
No particular preferences from me.

**Comment by the8472** [comment]
This has been seconded and no objections have been registered, so I'm closing the issue as approved.
