### ISSUE TITLE
`std::process::Command` add `args_clear` function

### ISSUE THREAD

**Issue by HomyeeKing** [rust-lang/libs-team#149]
# Proposal

## Problem statement
we have to instantiate `Command` through `Command::new()` every time  to make sure the args are what we called

for me, a new Rustacean, I want to reuse the `Command` instance,  but the `args` are concated if you call it many times
see [this example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=27ab6abd4c374893233c86a7b75b8fed)

## Motivation, use-cases
```rs
use std::process::{Command, Output};

fn get_stdout(output: &Output) -> String {
    return (String::from_utf8(output.stdout.clone())).unwrap();
}

fn main() {
    let mut echo = Command::new("echo");  // save the `echo` command instance for future using instead of instantiating it  every time

    let first_call = get_stdout(
&echo
.args_clear() //  empty the args array
.arg("foo")
.output()
.unwrap());


    let second_call = get_stdout(
&echo
.args_clear() //  empty the args array
.arg("bar")   // if don't clear, the args here will be ["foo","bar"]
.output()
.unwrap());

    println!("first call is {first_call}");
    println!("second call is {second_call}");
}

```

## Solution sketches
call `args_clear()` to empty the args in this instance

## Links and related work
if team member have no objection on this, I will send a pull request to add this feature

## What happens now?

This issue is part of the libs-api team [API change proposal process]. Once this issue is filed the libs-api team will review open proposals in its weekly meeting. You should receive feedback within a week or two.

[API change proposal process]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html

**Comment by the8472** [comment]
A function/lambda that produces a `Command` would do the same job.
That's a common pattern: https://github.com/rust-lang/rust/blob/master/src/bootstrap/builder.rs#L1024

**Comment by HomyeeKing** [comment]
A function factory is a solution based on the current implementation, but I still prefer the way that just instantiate once

**Comment by Amanieu** [comment]
We discussed this in the libs meeting today. The `Command` type is designed to be used as a single-use builder and is not intended to be re-used multiple times. (for example, it doesn't implement `Clone` because it contains a bunch of single-use state) While we do have APIs to inspect its state (`get_*` methods), these are intended for use as debugging output.

We recommend using a separate structure such as the one suggested by @the8472 for spawning multiple commands with a similar environment.
