### ISSUE TITLE
Add Default support for arrays of all sizes

### ISSUE THREAD

**Issue by saeubank** [rust-lang/libs-team#153]
# Proposal

## Problem statement

Arrays over the size of 32 do not support `Default`.

## Motivation, use-cases

`let arr = <[u8; 64]>::default();`

## Solution sketches

`[T::default(); N]`
This does not work because default only gets called once.
If for some reason an implementation of default is like a generator, this will not behave as expected since the whole array will be the same value rather than being the generated value.

## Links and related work

https://github.com/rust-lang/rust/pull/106145

## What happens now?

This issue is part of the libs-api team [API change proposal process]. Once this issue is filed the libs-api team will review open proposals in its weekly meeting. You should receive feedback within a week or two.

[API change proposal process]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html

**Comment by cuviper** [comment]
We can't do this until we have a solution for `[T; 0]` without `T: Default`, or a convincing argument to make that breaking change.

**Comment by saeubank** [comment]
Yeah it looks like it will be a breaking change until negative Traits are implemented.
```
impl<T> Default for [T; 0] where 
 T: !Default {
    fn default() -> Self {
        []
    }
}
```

I think that this is worth making a breaking change for.
Is it worth using @craterbot to check if people actually use default for `[T; 0]` where T does not implement Default?

**Comment by cuviper** [comment]
I didn't have the issue at hand before, but that's rust-lang/rust#61415 for a lot more history.

**Comment by dtolnay** [comment]
I'm confident the library API team is on board with arbitrarily large \[T; N\] implementing Default. The missing piece is just figuring out a way to implement it &mdash; as mentioned above, this is tracked in https://github.com/rust-lang/rust/issues/61415.
