### ISSUE TITLE
impl Default for ExitStatus

### ISSUE THREAD

**Issue by ijackson** [rust-lang/libs-team#158]
# Proposal

## Problem statement

It is not possible for code outside std to portably create an `ExitStatus` without actually running a process.

## Motivation, use-cases

 * You might want to create a value as a placeholder in error handling APIs (for example, https://github.com/rust-lang/rfcs/pull/3362 https://github.com/ijackson/rust-rfcs/blob/command/text/0000-command-ergonomics.md#more-convenient-way-to-run-diff)
 * Testing

In some cases it might be convenient to use `Option<ExitStatus>`; but `ExitStatus` is already kind of option-ish in that it can represent an error, or no error.

It is IMO not reasonable to have a type that a user *can* mostly-portably create, but to require a user to run a dummy process to do so.  This type can already be non-portably constructed on Unix and Windows via `ExitStatusExt`.

## Solution sketches

The obvious-to-me answer is to `impl Default for ExitStatus`.

I did that in https://github.com/rust-lang/rust/pull/106425 and am now belatedly making this ACP.

A consequence is that `ExitStatus` now becomes inhabited even on platforms without subprocesses.  This seems reasonable.

## Links and related work

See also the tracking issue for thec currently-unstable `ExitStatusError`, https://github.com/rust-lang/rust/issues/84908.  I'm postponing addressing the same question for `ExitStatusError`, but it should be considered before stabilisation.

## What happens now?

This issue is part of the libs-api team [API change proposal process]. Once this issue is filed the libs-api team will review open proposals in its weekly meeting. You should receive feedback within a week or two.

[API change proposal process]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html

**Comment by m-ou-se** [comment]
Thanks! This seems fine to me. I'll start the FCP on https://github.com/rust-lang/rust/pull/106425.

(Perhaps we should also allow the creation of other statusses, maybe in the form of a `From<ExitCode>`. Although maybe `ExitStatusExt::from_raw` already suffices, at least on Windows and Unix platforms.)
