### ISSUE TITLE
Add `Option::transpose_fn` methods

### ISSUE THREAD

**Issue by nvzqz** [rust-lang/libs-team#166]
# Proposal

## Problem statement

Conversion from `Option<Fn(A) -> R>` to `Fn(A) -> Option<R>` as a helper function rather than writing out a closure for it.

## Motivation, use-cases

There exist callback APIs that take `Fn(A) -> Option<R>` which may be invoked in a setting where the caller has access to `f: Option<Fn(A) -> R>`. This conversion can be concisely written as `|arg| f.as_ref().map(|f| f(arg))`, but it can be difficult for some people to read what is happening there. It can also be written in long form:

```rs
|arg| match &f {
    Some(f) => Some(f(arg)),
    None => None,
}
```

By adding a function to the standard library that performs this conversion, this code can be made easier to read and maintained.

## Solution sketches

A full solution is implemented in https://github.com/rust-lang/rust/pull/107176.

The proposed API is:

```rs
impl<F> Option<F> {
    pub fn transpose_fn<A>(self) -> impl Fn<A, Output = Option<F::Output>>
        where A: Tuple, F: Fn<A>;

    pub fn transpose_fn_mut<A>(self) -> impl FnMut<A, Output = Option<F::Output>>
        where A: Tuple, F: FnMut<A>;

    pub fn transpose_fn_once<A>(self) -> impl FnOnce<A, Output = Option<F::Output>>
        where A: Tuple, F: FnOnce<A>;
}
```

## Alternatives

We could instead implement the `Fn` traits on `Option<F>`.

## Links and related work

This API is similar to [`Option::transpose`](https://doc.rust-lang.org/stable/std/option/enum.Option.html#method.transpose) for converting from `Option<Result<T, E>>` to `Result<Option<T>, E>`.

**Comment by nvzqz** [comment]
Like I mentioned in https://github.com/rust-lang/rust/pull/107176#pullrequestreview-1264706401, this API may be better off being a single method with a concrete return type rather than three separate methods with anonymous return types.

**Comment by thomcc** [comment]
Do we have any existing functions that return impl trait in the stdlib? I don't think so, we at least tend to avoid it in most cases.

**Comment by scottmcm** [comment]
If we had `try`, this could be written `try { f?(args) }`, right?

**Comment by Amanieu** [comment]
We discussed this in the libs-api meeting today. The overall feeling was that, of the many ways in which this transformation can be expressed, `transpose_fn` is the *least* readable. For example, simple doing `|arg| Some(f?(arg))` is much clearer.
