### ISSUE TITLE
Add `Lines::remainder`

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/libs-team#171]
# Proposal

Add `Lines::remainder` similarly to other `remainder` methods on split iterators for strings (see tracking issue: https://github.com/rust-lang/rust/issues/77998).

## Problem statement

While most iterators that split strings allow to get the remainder, `Lines` does not.

## Motivation, use-cases

It may be beneficial to get the remainder of an iterator, for example to process it differently. A rough sketch:
```rust
let lines = s.lines();

while let Some(line) = lines.next() {
    let command = line.parse::<Command>()?;
    // ...
    if command.is_end() {
        process_end(lines.remainder());
        break;
    }
}
```

## Solution sketches

```rust
impl<'a> Lines<'a> {
    pub fn remainder(&self) -> Option<&'a str> { /* ... */ }
}
```

## Links and related work

- Tracking issue for similar methods on other iterators: https://github.com/rust-lang/rust/issues/77998
- Implementation PR: https://github.com/rust-lang/rust/pull/107464

## What happens now?

This issue is part of the libs-api team [API change proposal process]. Once this issue is filed the libs-api team will review open proposals in its weekly meeting. You should receive feedback within a week or two.

[API change proposal process]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html

**Comment by pitaj** [comment]
Seems like a fitting addition to me

**Comment by JohnCSimon** [comment]
@WaffleLapkin Ping from triage:  Can you post your status on this PR? This has sat idle for a few months.

**Comment by WaffleLapkin** [comment]
@JohnCSimon it is waiting on review from libs-api (either the ACP or the PR)

**Comment by haberman** [comment]
Any update? I found myself wanting this method today.

**Comment by WaffleLapkin** [comment]
@haberman still waiting on T-libs-api. They are having problems with not having enough capacity.

**Comment by dtolnay** [comment]
This looks good to me, and I have accepted your PR. Thanks!
