### ISSUE TITLE
Implement `bool::sign` 

### ISSUE THREAD

**Issue by gimbling-away** [rust-lang/libs-team#172]
# Proposal

## Problem statement

A `bool::sign` method could be added which converts a `bool` into an `i8`, if it's true, 1, else -1.

## Motivation, use-cases

Such a pattern is very common while working with C-like APIs and in other areas and we do already have a `bool as <int>` conversion.

## Solution sketches

```rs
fn sign(self) -> i8 {
    if self { 1 } else { -1 }
}
```
Could be a possible implementation of this method in `core`.

**Comment by joboet** [comment]
Could you provide an example for C code actually using `-1` as `false` value? `false` normally corresponds to `0` (it does in Rust and in nearly other language) and for that, we have [quite a lot of `Into` implementations](https://doc.rust-lang.org/nightly/std/primitive.bool.html#impl-From%3Cbool%3E-for-i8), so you could always do `into::<i8>()` where type inference is not possible.

**Comment by thomcc** [comment]
It's also pretty common in low level APIs to use `-1` as true (note that it is "all bits set" in 2's complement). For example, many SIMD APIs do this, and it's actually reflected in the current version of `core::simd::Mask` for various reasons.

**Comment by scottmcm** [comment]
> `if self { 1 } else { -1 }`

I definitely find this surprising, because it's not what [`i8::from(self).signum()`](https://doc.rust-lang.org/std/primitive.i8.html#method.signum) would do, so I don't think we should have two "sign" things that are different like this.

(Floats have `is_sign_positive`, but that gives a `bool`, so wouldn't be useful on on `bool`.)

**Comment by gimbles** [comment]
Fair, this method might just cause further confusion, closing 👋🏻
