### ISSUE TITLE
Add type alias for raw OS errors

### ISSUE THREAD

**Issue by joboet** [rust-lang/libs-team#173]
# Proposal

## Problem statement

`io::Error` assumes OS error values always fit into an `i32`, but that is not true for all platforms.

## Motivation, use-cases

rust-lang/rust#105861 introduces `std` support for UEFI applications. There is however a problem with the way native OS errors are handled in `std`, as the current API expects error values to fit into an `i32`. While this the case for all currently supported platforms, UEFI diverges from the pattern by using an `usize`[^1] as error type. This forces code supporting UEFI to convert the native errors to custom `io::Error`s, which does not fit well with the current API and looses information.

## Solution sketches

Add a new type alias to `std::io` (naming open to bikeshedding):

```rust
pub type RawOsError = /* platform error type, `i32` most of the time */;
```

and use it in place of `i32` in [`io::Error::from_raw_os_error`](https://doc.rust-lang.org/nightly/std/io/struct.Error.html#method.from_raw_os_error) and [`io::Error::raw_os_error`](https://doc.rust-lang.org/nightly/std/io/struct.Error.html#method.raw_os_error). This is a backwards-compatible change on all current platforms, but new code wishing to support platforms like UEFI will need to use the new error type to ensure portability.

CC @Ayush1325

[^1]: At least according to the specification. However, error values always have the highest bit set, so `isize` would be more convenient...

**Comment by Ayush1325** [comment]
This is a perfect suggestion. 

Also, the current limitation of using i32 does not seem completely consistent inside std. The rust [`lang_start`](https://github.com/rust-lang/rust/blob/7c4a9a971ca6962533bed01ffbd0c1f6b5250abc/library/std/src/rt.rs#L159) returns `isize` and not `i32`.

Finally, I have already merged https://github.com/rust-lang/rust/pull/104001 which makes it easier to use custom entry points for custom targets and thus it would be great to have a more generic os errors.

**Comment by Amanieu** [comment]
I agree with this change, it does seem like we want a more flexible definition of a raw OS error.

@rustbot label +initial-comment-period

**Comment by joboet** [comment]
Closing in favour of the tracking issue: rust-lang/rust#107792
