### ISSUE TITLE
Adding `Vec::as_uninit_slice` and `Vec::as_mut_uninit_slice`

### ISSUE THREAD

**Issue by Aandreba** [rust-lang/libs-team#174]
# Proposal
This proposal would add the hability for a `Vec` to return a slice of uninitialized values over all it's currently allocated memory

## Problem statement
For optimization reasons, or to interact with external APIs, it's often usefull to use an uninitialized region of a vector directly, and then adjusting it's length if necesary.

## Motivation, use-cases
Currently, to get similar functionality, you would have to do this
```rust
use std::mem::MaybeUninit;

let mut vector: Vec<i32> = Vec::with_capacity(32);
let uninit: &mut [MaybeUninit<i32>] = unsafe {
    core::slice::from_raw_parts_mut(vector.as_mut_ptr().cast(), vector.capacity());
};

for i in 0..5 {
    uninit[i].write(i as i32);   
}

unsafe { vector.set_len(5) };
println!("{vec:?}") // prints [0, 1, 2, 3, 4]
```

But the complexity of the code could be reduced with this new API
```rust
use std::mem::MaybeUninit;

let mut vector: Vec<i32> = Vec::with_capacity(32);
let uninit: &mut [MaybeUninit<i32>] = vector.as_mut_uninit_slice();

for i in 0..5 {
    uninit[i].write(i as i32);   
}

unsafe { vector.set_len(5) };
println!("{vec:?}") // prints [0, 1, 2, 3, 4]
```

## Solution sketches
```rust
use std::mem::MaybeUninit;

impl<T> Vec<T> {
    #[inline]
    pub fn as_uninit_slice (&self) -> &[MaybeUninit<T>] {
        // SAFETY: The `MaybeUninit` API already provides safe access to the uninitialized "values"
        unsafe {
            core::slice::from_raw_parts(self.as_ptr().cast(), self.capacity())
        } 
    }

    #[inline]
    pub fn as_mut_uninit_slice (&mut self) -> &mut [MaybeUninit<T>] {
        // SAFETY: The `MaybeUninit` API already provides safe access to the uninitialized "values"
        unsafe {
            core::slice::from_raw_parts_mut(self.as_mut_ptr().cast(), self.capacity())
        } 
    }
}
```

## What happens now?

This issue is part of the libs-api team [API change proposal process]. Once this issue is filed the libs-api team will review open proposals in its weekly meeting. You should receive feedback within a week or two.

[API change proposal process]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html

**Comment by scottmcm** [comment]
The example here looks like it could be done with the existing <https://doc.rust-lang.org/std/vec/struct.Vec.html#method.spare_capacity_mut> instead?

Also, I'm pretty sure the proposed API is unsound, since I could do this:
```rust
let mut v = vec!["hello".to_string()];
v.as_mut_uninit_slice()[0] = MaybeUninit::uninit();
drop(v); // BOOM dropping an uninit `String`.
```

**Comment by Aandreba** [comment]
> The example here looks like it could be done with the existing https://doc.rust-lang.org/std/vec/struct.Vec.html#method.spare_capacity_mut instead?

Yes you could, but the implementation is different when the vec already has values.

**Comment by Aandreba** [comment]
> Also, I'm pretty sure the proposed API is unsound, since I could do this:
> 
> ```rust
> let mut v = vec!["hello".to_string()];
> v.as_mut_uninit_slice()[0] = MaybeUninit::uninit();
> drop(v); // BOOM dropping an uninit `String`.
> ```

That's true, perhaps it should be an unsafe method.

**Comment by cuviper** [comment]
`spare_capacity_mut` doesn't let you uninitialize existing items. The problem is not just leaking the old `String`, which is safe, but that `drop` will be called on the `uninit()` you wrote in its place.

**Comment by pitaj** [comment]
> Yes you could, but the implementation is different when the vec already has values.

I suggest you provide a use case that makes use of that difference in behavior.

**Comment by Aandreba** [comment]
>  The problem is not just leaking the old `String`, which is safe, but that `drop` will be called on the `uninit()` you wrote in its place.

Actually it won't, you haven't updated the vector's length, which is done through the unsafe `Vec::set_len`

**Comment by Aandreba** [comment]
Actually, you're right, spare_capacity_mut probably makes due
