### ISSUE TITLE
We need a doc(alias) policy

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/libs-team#18]
See also https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/doc.20aliases/near/243793287

- https://github.com/rust-lang/rust/pull/81989#issuecomment-824143364
- https://github.com/rust-lang/rust/pull/81988#issuecomment-824168459

**Comment by yaahc** [comment]
And we have a doc(alias) policy now! https://github.com/rust-lang/std-dev-guide/pull/25

:tada:

**Comment by joshtriplett** [comment]
We now have a doc(alias) policy, closing.
