### ISSUE TITLE
Add is_before and is_after on Instant

### ISSUE THREAD

**Issue by randomairborne** [rust-lang/libs-team#182]
# Proposal

## Problem statement

Writing code to test if an instant is before or after another often results in unclear code.

## Motivation, use-cases

`if instant > std::time::Instant::now() {}` is a particular example. It's mostly a usability and readability improvement, however whichever method is most performant could be chosen.

## Links and related work

Go has these [before](https://pkg.go.dev/time#Time.Before) [after](https://pkg.go.dev/time#Time.After), but the naming isn't the best.

**Comment by pitaj** [comment]
Your proposal isn't exactly clear. Are these functions relative to `now()`? Or are they just clearer versions of greater-than / less-than?

**Comment by randomairborne** [comment]
They are essentially clearer versions of greater-than and less-than. The Go standard library linked has basically the exact functionality.

**Comment by pitaj** [comment]
Is there precedent for this elsewhere in the standard library?

**Comment by randomairborne** [comment]
The main thing I see elsewhere in std is the is_empty/is_some/is_none/is_err/is_ok methods. It doesn't actually provide any "real" benefits, other then being clearer. Seeing if a certain time is before another is one of the main uses of monotonic clocks, is it not?

**Comment by pitaj** [comment]
But none of those are drop-in replacements for an existing operator or function. `.is_empty()` replaces `.len() == 0`, not `== other`. It seems like a completely different class.

**Comment by randomairborne** [comment]
I'm not quite sure how to find them, but...
I have kind of realized that this is essentially GT and LT. They aren't as clear as i thought, but directly using them is plenty clear IMO. Sorry for wasting your time.
