### ISSUE TITLE
ACP: Implement Step for many PartialOrd types that have good notion of predecessor and successor

### ISSUE THREAD

**Issue by schuelermine** [rust-lang/libs-team#189]
# Proposal

## Problem statement

Currently, `Step` has a well-formulated description that extends to lots of types. Unfortunately, only some of these types actually implement `Step`.

## Motivation, use-cases

Ranges of more types could be possible and generic code that deals with items that are `Step` in general could benefit from this.
Also, the `Step` documentation is pretty clear on what types fit the trait. I believe these traits simply fit that trait and should implement it, or the documentation ought to change.

## Solution sketches

Implement `Step` for the following types:
- `Ordering`
- `bool`
- `()`
- `NonZeroI8`
- `NonZeroI16`
- `NonZeroI32`
- `NonZeroI64`
- `NonZeroI128`
- `NonZeroIsize`
- `NonZeroU8`
- `NonZeroU16`
- `NonZeroU32`
- `NonZeroU64`
- `NonZeroU128`
- `NonZeroUsize`
- for `T: Step`: `Saturating<T>`
- for `T: Step`: `Wrapping<T>`

If `float_next_up_down` is stabilized, this list could also include:
- `f32`
- `f64`

These implementations are trivial except for `Wrapping` and `Saturating`.

I haven’t included values that I deem to be a combinations of other values. If the lexicographic ordering used by `PartialOrd` is to be used, a lot more could be added. You could argue about whether floats or IP addresses are or aren’t combinations of values.

## Links and related work

I chatted about a part of this on The Rust Programming Language Forum: https://users.rust-lang.org/t/why-does-bool-not-implement-step/90636/14
Haskell has a similar class (equiv. to traits), `Enum`, which is implemented for a whole host of types: https://hackage.haskell.org/package/base-4.18.0.0/docs/Prelude.html#t:Enum

## What happens now?

This issue is part of the libs-api team [API change proposal process]. Once this issue is filed the libs-api team will review open proposals in its weekly meeting. You should receive feedback within a week or two.

[API change proposal process]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html

**Comment by programmerjake** [comment]
imho `f32`/`f64` implementing `Step` is too confusing...lots of people are likely to think it counts by adding `1.0` rather than using `next_after`.

**Comment by jhpratt** [comment]
Implementing it for nonzero types is a no-brainer. Other than that, I don't think the implementations make sense.

**Comment by programmerjake** [comment]
imho NonZero*, Wrapping, and Saturating make sense.
other types that likely are useful:
* bool
* ()
* `*const T`/`*mut T` where `T: Sized` -- would use `wrapping_add` and `(a.addr() - b.addr()) / size_of::<T>()` for safety. may panic for zero-sized types

**Comment by jhpratt** [comment]
Wrapping and saturating have the natural question of what happens at the boundaries. bool and () I don't see an obvious use case for.

**Comment by programmerjake** [comment]
> * `*const T`/`*mut T` where `T: Sized` -- would use `wrapping_add` and `(a.addr() - b.addr()) / size_of::<T>()` for safety. may panic for zero-sized types

probably better if `steps_between` returns `None` when:
`(a.addr() - b.addr()) % size_of::<T>() != 0`
if `T` is zero-sized, instead returns Some(0) when a == b else None

**Comment by programmerjake** [comment]
> Wrapping and saturating have the natural question of what happens at the boundaries. bool and () I don't see an obvious use case for.

() is useful when you want an always empty range type that is a ZST.
bool is useful when you want to go through all combinations of some bool variables, e.g. when making a truth table:
```rust
for a in false..=true {
    for b in false..=true {
        println!("{a} AND {b} = {}", a & b);
    }
}
```

**Comment by programmerjake** [comment]
`Wrapping<u8>` could always return `Some` for `steps_between`, e.g. `Wrapping(5u8).steps_between(&Wrapping(0)) == Some(0x100 - 5)`

Wrapping and Saturating are useful when you want `v..` to go forever without panicking in debug mode.

**Comment by shepmaster** [comment]
> combinations of some bool variables

I think that an array is clearer and avoids the problem that only one of `false..=true` / `true..=false` would do what you want.

```rust
for a in [false, true] {
    for b in [false, true] {
        println!("{a} AND {b} = {}", a & b);
    }
}
```

**Comment by schuelermine** [comment]
I have edited the ACP body to note that the implementation for `Wrapping` and `Saturating` is up for debate.

**Comment by programmerjake** [comment]
> > combinations of some bool variables
> 
> I think that an array is clearer and avoids the problem that only one of `false..=true` / `true..=false` would do what you want.

the array version is poorly optimized, whereas the range version works great:
https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=c995cff834f35cff552dda945360d0c4

**Comment by scottmcm** [comment]
The signed non-zero types have a gap, but I guess that's not really a blocker since `char` has a gap too.  Does make it harder for me to come up with an obvious place that would want the range with the gap, though.

**Comment by shepmaster** [comment]
> the array version is poorly optimized

Since you don't mention the ergonomics, I'll assume you agree that the array version is clearer. Can the implementation of array's iterator be optimized? That would seem to have large benefit.

**Comment by BurntSushi** [comment]
What is the use case? All I see for motivation is that these trait impls "fit" and "help with generics," but those don't seem like compelling use cases to me. Can you show me some real code that would benefit from these impls? I'm especially skeptical of impls for `bool`, `()`, `Ordering`, `Saturating` and `Wrapping`.

**Comment by scottmcm** [comment]
> the array version is poorly optimized

I'm taking a [look](https://rust-lang.zulipchat.com/#narrow/stream/187780-t-compiler.2Fwg-llvm/topic/Convincing.20LLVM.20that.20GEP.20goes.20forwards/near/341071700) at this.  Sadly it's true that the by-value iterator optimizes less well some times (<https://stdrs.dev/nightly/x86_64-unknown-linux-gnu/core/array/drain/fn.drain_array_with.html>).  Hopefully https://github.com/rust-lang/rust/pull/107224 will make it better.

This works great, though! <https://rust.godbolt.org/z/YvzvYvEP4>
```rust
pub fn array(func: fn(bool, bool, bool)) {
    for &i in &[false, true] {
        for &j in &[false, true] {
            for &k in &[false, true] {
                func(i, j, k);
            }
        }
    }
}
```

**Comment by programmerjake** [comment]
> > the array version is poorly optimized
> 
> Since you don't mention the ergonomics, I'll assume you agree that the array version is clearer.

not necessarily... if you know that `bool` is essentially:
```rust
#[repr(u8)]
pub enum bool {
    false = 0,
    true = 1,
}
```

then imho `false..=true` easily makes sense. I do tend to prefer ranges instead of a list of values when iterating.

**Comment by cuviper** [comment]
See also #130.

**Comment by Amanieu** [comment]
We discussed this in the libs-api meeting and decided to only implement `Step` for unsigned `NonZero` types, which is proposed in ACP #130.

The main reason was that it was the only type for which people actually demonstrated use cases. Signed `NonZero` is excluded because it has a non-obvious gap at the value 0 which we felt is a bit of a footgun.

**Comment by kennytm** [comment]
> Signed `NonZero` is excluded because it has a non-obvious gap at the value 0 which we felt is a bit of a footgun.

well tbh `char` has a gap around the surrogates too

```rust
    assert_eq!( 
        ('\u{d7fe}'..'\u{e002}').collect::<String>(), 
        "\u{d7fe}\u{d7ff}\u{e000}\u{e001}",
    );
```

**Comment by m-ou-se** [comment]
@kennytm Yes, but for NonZeroI* that can be a footgun, because you might have simply forgotten to 'unwrap' the NonZeroI32 into a regular i32 first. For example, if you refactor some code from i32 to NonZeroI32, then some for loops will continue to compile fine but now silently skip `0`, which might not have been the intention.
