### ISSUE TITLE
Move `Utf8Chunks::new` to be inherent on `[u8]`

### ISSUE THREAD

**Issue by dylni** [rust-lang/libs-team#190]
# Proposal

## Problem statement

[`Utf8Chunks::new`] requires importing [`Utf8Chunks`]. Adding this method on `[u8]` would allow it to be used without an import.

This API is unstable, so this is not a breaking change.

## Motivation, use-cases

This is similar to other methods treating `[u8]` as a byte string, such as [`<[u8]>::is_ascii`][is_ascii].

### Example

Code using [`Utf8Chunks::new`]:

```rust
use std::str::Utf8Chunks;

for chunk in Utf8Chunks::new(string) {
    let valid = chunk.valid();
    let invalid = chunk.invalid();
    // formatting for `valid` and `invalid`
}
```

Code using `<[u8]>::utf8_chunks`:

```rust
for chunk in string.utf8_chunks() {
    let valid = chunk.valid();
    let invalid = chunk.invalid();
    // formatting for `valid` and `invalid`
}
```

## Solution sketches

Current signature:

```rust
impl<'a> Utf8Chunks<'a> {
    fn new(bytes: &'a [u8]) -> Self;
}
```

Proposed signature:

```rust
impl [u8] {
    fn utf8_chunks(&self) -> Utf8Chunks<'_>;
}
```

## Links and related work

- Tracking issue: https://github.com/rust-lang/rust/issues/99543
- Proposal: #54
- Implementation: https://github.com/rust-lang/rust/pull/99544

## What happens now?

This issue is part of the libs-api team [API change proposal process]. Once this issue is filed the libs-api team will review open proposals in its weekly meeting. You should receive feedback within a week or two.

[API change proposal process]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html
[is_ascii]: https://doc.rust-lang.org/std/primitive.slice.html#method.is_ascii
[`Utf8Chunks`]: https://doc.rust-lang.org/std/str/struct.Utf8Chunks.html
[`Utf8Chunks::new`]: https://doc.rust-lang.org/std/str/struct.Utf8Chunks.html#method.new

**Comment by dtolnay** [comment]
Looks good. This would join quite a few other byte-string-like methods we already have on `[u8]`.

- https://doc.rust-lang.org/std/primitive.slice.html#method.is_ascii
- https://doc.rust-lang.org/std/primitive.slice.html#method.eq_ignore_ascii_case
- https://doc.rust-lang.org/std/primitive.slice.html#method.make_ascii_uppercase
- https://doc.rust-lang.org/std/primitive.slice.html#method.make_ascii_lowercase
- https://doc.rust-lang.org/std/primitive.slice.html#method.escape_ascii
- https://doc.rust-lang.org/std/primitive.slice.html#method.to_ascii_uppercase
- https://doc.rust-lang.org/std/primitive.slice.html#method.to_ascii_lowercase
- https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.as_ascii (unstable)
- https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.as_ascii_unchecked (unstable)
- https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.trim_ascii_start (unstable)
- https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.trim_ascii_end (unstable)
- https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.trim_ascii (unstable)
