### ISSUE TITLE
Implement `PartialEq` between `Box<T>`/etc. and `T`

### ISSUE THREAD

**Issue by dead-claudia** [rust-lang/libs-team#206]
# Proposal

## Problem statement

I'd like to compare equality against references and collections of them (most commonly `&'static [u8]` and `&'static str`) in testing.

## Motivation, use-cases

- Superset of https://github.com/rust-lang/libs-team/issues/79 that's also much simpler to implement
- I find myself sometimes wanting to `assert_eq!(vec_of_boxes, array_of_slices)`, and it'd be nice to not have to allocate capacity for each entry. Currently, I only have this issue in a `vec_of_strings` only created in test, but it's very easy to imagine it coming up in prod.
- It'd be nice to not have to do `&boxed` just for the sake of equality against boxes in testing.

## Solution sketches

```rust
impl<T: ?Sized, D: Deref> PartialEq<T> for D where D::Target: PartialEq<T> {
    fn eq(&self, other: &T) -> bool { &*self == other }
}

impl<T: ?Sized, D: Deref> PartialOrd<T> for D where D::Target: PartialOrd<T> {
    fn partial_cmp(&self, other: &T) -> Option<Ordering> { (**self).partial_cmp(other) }
}
```

## Links and related work

- https://github.com/rust-lang/libs-team/issues/79 as this obviously would replace that

## What happens now?

This issue is part of the libs-api team [API change proposal process]. Once this issue is filed the libs-api team will review open proposals in its weekly meeting. You should receive feedback within a week or two.

[API change proposal process]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html

**Comment by dead-claudia** [comment]
There is one concern I will call out immediately, though: you can `impl PartialEq for &T` when `T` is module-local (and I do actually do this for other types, though not `PartialEq` or `PartialOrd`), so these unfortunately can't be implemented both ways.

`D` might have to be restricted to various collections - there is an `impl Deref for &T`, and this may very well result in related conflicts. If a Crater run doesn't yield any issues, it may be possible to implement the reverse of the above two as well (and so the above concern could be safely ignored).

**Comment by joshtriplett** [comment]
We discussed this in the libs meetup, and we felt that this is likely to create widespread inference issues. We're going to close this for now, but don't let that stop you from attempting to demonstrate that it *can* work without widespread inference failure. :)
