### ISSUE TITLE
Remove unstable `Poll::ready`

### ISSUE THREAD

**Issue by ibraheemdev** [rust-lang/libs-team#214]
# Proposal

`Poll::ready` was added as an experimental alternative to `task::ready!`, but was deemed to problematic because of the already existing `Try` implementations for `Poll` (see https://github.com/rust-lang/rust/issues/89780 for the relevant discussion). Fixing this would likely require changes over an edition, which seems unlikely after `task::ready!` was already stabilized, so I think we should just go ahead and remove `Poll::ready`.

Pull request: https://github.com/rust-lang/rust/pull/107060

**Comment by m-ou-se** [comment]
As discussed in the libs meetup: we can proceed with https://github.com/rust-lang/rust/pull/107060 to remove the unstable .ready() method, as ready!() is already stable. Thanks!
