### ISSUE TITLE
ACP: Make <[[T; N]]>::flatten const

### ISSUE THREAD

**Issue by xfix** [rust-lang/libs-team#218]
# Proposal

## Problem statement

Allow using `<[[T; N]]>::flatten` within `const fn`.

## Motivation, use-cases

Could be useful for code like this where you have an array containing arrays (for instance from `u32::to_be_bytes`) to return an array. For example, `Ipv6Addr::new` in standard library could make use of it.

```rust
[f(a), f(b), f(c), f(d)].flatten().try_into().unwrap()
```

## Solution sketches

Add `const` keyword. The current implementation is already const-compatible, and I don't see a reason why this would change.

## What happens now?

This issue is part of the libs-api team [API change proposal process]. Once this issue is filed the libs-api team will review open proposals in its weekly meeting. You should receive feedback within a week or two.

[API change proposal process]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html

**Comment by scottmcm** [comment]
Thanks for the ACP!  For an unstable method, I'm going to consider this something that can be done as a tweak under the existing tracking issue, and not something that needs to wait on a libs-api decision, given that the implementation change is trivial.  I've approved the PR.

libs-api folks, please feel free to yell at me if you disagree 🙃

**Comment by pitaj** [comment]
This can now be closed.
