### ISSUE TITLE
Add desktop to `std::os::windows::process::CommandExt`

### ISSUE THREAD

**Issue by RichardRobertson** [rust-lang/libs-team#221]
# Proposal

## Problem statement

Add a function to the Windows specific Command extension to enable specifying the desktop name to launch a child process in.

## Motivation, use-cases

Currently, I must duplicate some of the code in Command and call `CreateProcessW` manually in order to set `STARTUPINFOW.lpDesktop`. I also do not get the convenient Child instance.

## Solution sketches

I imagine it would look like this and work similarly to `creation_flags`. It would need the associated bits in the inner value but I'm not sure where that code is located yet.

```rust
// in std/src/os/windows/process.rs

pub trait CommandExt: Sealed {
    fn desktop(&mut self, name: &str) -> &mut process::Command;

    // ...
}

// ...

impl CommandExt for process::Command {
    fn desktop(&mut self, name: &str) -> &mut process::Command {
        self.as_inner_mut().desktop(name);
        self
    }

    // ...
}
```

Current I'm doing this:

```rust
fn example() {
    let mut name: Vec<u16> = "testing".encode_utf16().chain([0u16]).collect();
    let start_info = windows::Win32::System::Threading::STARTUPINFOW {
        cb: std::mem::size_of::<windows::Win32::System::Threading::STARTUPINFOW>() as u32,
        lpDesktop: windows::core::PWSTR(name.as_mut_ptr()),
        ..Default::default()
    };
    let mut process_info = windows::Win32::System::Threading::PROCESS_INFORMATION::default();
    unsafe {
        windows::Win32::System::Threading::CreateProcessW(
            windows::w!("C:\\Windows\\system32\\notepad.exe"),
            windows::core::PWSTR::null(),
            None,
            None,
            false,
            windows::Win32::System::Threading::PROCESS_CREATION_FLAGS::default(),
            None,
            windows::core::PCWSTR::null(),
            &start_info,
            &mut process_info,
        )
        .unwrap();
    }
    // process_info contains the handle among other things
}
```

## What happens now?

This issue is part of the libs-api team [API change proposal process]. Once this issue is filed the libs-api team will review open proposals as capability becomes available. Current response times do not have a clear estimate, but may be up to several months.

[API change proposal process]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html

**Comment by pitaj** [comment]
Sounds like a good addition to me. Why does it take an `Option<&str>`?

**Comment by RichardRobertson** [comment]
Option because null string is valid input to CreateProcessW.

**Comment by RichardRobertson** [comment]
I'm brand new to Rust. Is that more idiomatic for builders?

**Comment by the8472** [comment]
What purpose does the desktop parameter serve? I only know it from sandboxing, but in that case one has to specify a lot more than just that.

**Comment by RichardRobertson** [comment]
I'm my case, it's to invisibly automate a GUI installer. Administrative process initiated server side that creates a desktop for the installer to run on without the user interfering or being interfered with. Creating a desktop is super easy with a couple of Win32 calls. Due to UAC, the standard user can't interact with or switch to the privileged desktop even if they knew it existed.

Once the process is running on the second desktop, UI Automation will install it unattended.

Related, but not a Rust problem: I wish all installers had silent command line options.

**Comment by m-ou-se** [comment]
Thanks for your ACP.

- About the problem: Having more methods on CommandExt for windows to e.g. set the desktop fine and useful functionality to have in std.

- About the proposed solution: I don't know which method signature(s) are the best for this.

So, please discuss (on e.g. the internals forum or on Zulip) with other users and (windows/rust) experts what the signature(s) should be. (E.g. Option or not, or a more generic solution that allows you to accesss the STARTUPINFOW directly, or something else.)

**Comment by RichardRobertson** [comment]
I didn't think of just exposing the STARTUPINFOW struct. That would probably have the longest term flexibility.

**Comment by ChrisDenton** [comment]
Allowing setting of [`STARTUPINFOW`](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/ns-processthreadsapi-startupinfow) sounds good to me. There's also extended startup info but that's [a whole other thing](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-updateprocthreadattribute). Off the top of my head the two questions that come to mind are:

* Should information set by a custom `STARTUPINFOW` take precedence over those set by `Command` itself or the other way around?
* Should it be an `unsafe` function? It does allow setting flags which may be added to in the future. We can't know how future flags may change things.

**Comment by joshtriplett** [comment]
@ChrisDenton I would expect that the custom hook overrides things set by Command. Also, we probably shouldn't expose the Windows type definition in std, unless we use our own type and you're confident it will never change?

**Comment by ChrisDenton** [comment]
I mean, `STARTUPINFOW` is where we set the I/O handles. Allowing users to override this is useful but it's also may lead to inconsistencies if the user just wants to set `lpDesktop`. On the other hand the `dwFlags` field could, potentially, have new flags added to it. A new flag may change the meaning of the other fields (like `STARTF_USEHOTKEY` does) or even change the way a process is created in unknowable ways.

**Comment by joshtriplett** [comment]
@ChrisDenton That seems relatively reasonable for an `unsafe` function to do, though.

**Comment by ChrisDenton** [comment]
Yeah, so that answer my question.

**Comment by RichardRobertson** [comment]
What if the builder started setting `STARTUPINFOW` fields directly and had one exposed mut ref to it? That way it could be initialized by the Command inner builder but also be accessible to modify b those who need to.

Alternatively, just adding the remaining `STARTUPINFOW` fields to the Command inner builder for consistency with the current API would work.

**Comment by pitaj** [comment]
What about exposing an opaque pointer which we guarantee is soundly castable to `*mut STARTUPINFOW`. Then someone can use the windows crate or whatever to operate on it, but it can be forward compatible.

**Comment by joshtriplett** [comment]
We talked about this again today among @rust-lang/libs-api. Based on the fields present in `STARTUPINFOW` (only a subset of which we want to expose), as well as the inconvenience of having a method that exposes an opaque pointer (to avoid exposing a Windows API type in the standard library), we changed our minds and would like to approve just adding a `desktop` method as a Windows extension. If there are other fields of `STARTUPINFOW` people want to set, we can add Windows extension methods for those too.

**Comment by joshtriplett** [comment]
Original ACP accepted as written; please ignore the tangent about exposing `STARTUPINFOW`.

**Comment by Krakoer** [comment]
Hi,
This issue has been marked as completed, but it doesn't seem implemented in the latest Rust release, and I can't find any issue/PR in the rust repo that mentions it. What is the status of this issue?

I have a ready implementation, I just wanted to check if I missed something before submitting it.

**Comment by ChrisDenton** [comment]
You're not missing anything. Feel free to create a tracking issue and submit a PR implementing this.

As per libs-api's new policy, I'll reopen this until a tracking issue is created.

**Comment by ChrisDenton** [comment]
Tracking issue created (https://github.com/rust-lang/rust/issues/158852). Closing this as complete.
