### ISSUE TITLE
ACP: Add `Cow::clear` methods

### ISSUE THREAD

**Issue by nvzqz** [rust-lang/libs-team#234]
# Proposal

## Problem statement

Making a `Cow` of a common slice type (`[T]`, `str`, `OsStr`) empty requires manually performing a `match` over `Owned`/`Borrowed` and performing the appropriate operations.

## Motivating examples or use cases

```rust
fn should_clear(s: &str) -> bool;

let mut strings: Vec<Cow<str>> = // ...

for s in &mut strings {
    if should_clear(s) {
        match s {
            Cow::Owned(string) => string.clear(),
            Cow::Borrowed(str) => *str = "",
        }
    }
}
```

## Solution sketch

Add an inherent `clear(&mut self)` method to `Cow` types where the owned type also has `clear`:

```rust
impl<T> Cow<'_, [T]>
where
    [T]: ToOwned<Owned = Vec<T>>,
{
    pub fn clear(&mut self) {
        match self {
            Self::Owned(vec) => vec.clear(),
            Self::Borrowed(slice) => *slice = &[],
        }
    }
}

impl Cow<'_, str> {
    pub fn clear(&mut self) {
        match self {
            Self::Owned(string) => string.clear(),
            Self::Borrowed(str) => *str = "",
        }
    }
}

impl Cow<'_, OsStr> {
    pub fn clear(&mut self) {
        match self {
            Self::Owned(os_string) => os_string.clear(),
            Self::Borrowed(os_str) => *os_str = OsStr::new(""),
        }
    }
}
```

## Alternatives

Don't do this.

## Links and related work

Implementation: https://github.com/rust-lang/rust/pull/112306

**Comment by pitaj** [comment]
Seems pretty niche. Do you have some examples of use cases in the wild?

**Comment by nvzqz** [comment]
I ran into this a few different times on some closed-source projects, so after the 4th time I was motivated to make this change. I unfortunately don't look through open source projects enough to have found public examples.

**Comment by pitaj** [comment]
I just need some context to figure out why someone would need to clear a Cow.

**Comment by programmerjake** [comment]
other related types that should have `clear` if `Cow<str>` and `Cow<OsStr>` get `clear` for consistency: `Cow<CStr>` and `Cow<Path>`
(`CString` should get `clear` anyway, just nobody got around to adding it)

**Comment by programmerjake** [comment]
> `CString` doesn't keep spare capacity, so `clear` would be no better than `mem::take` in that case.

well, `CString` claims to be like `String`, so imho that should change if practical

**Comment by m-ou-se** [comment]
In addition to that, `Cow` is extensible for your own types through `ToOwned`, but with this proposal, `Cow::clear()` would be specific to just a few types and not be extensible.

**Comment by scottmcm** [comment]
> and seems to be generally equivalent to just doing `cow = "".into()`.

The difference would be in keeping the allocation if the cow is owned, I think.

But that suggests an alternative here: 
```rust
x.clone_from(&Default::default());
```
<https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8cb2592a13256e9d90ba80a5c962be1b>

Which clears while preserving capacity.

**Comment by cuviper** [comment]
The unstable `ToOwned::clone_into` is also relevant for a fully general `Cow` approach.

**Comment by scottmcm** [comment]
Yup, `Cow::clone_from` using it was the main reason it got stabilized 🙂
