### ISSUE TITLE
Implement `PartialEq`, `Eq`, `PartialOrd`, `Ord`, `Hash` for unix `SocketAddr`

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/libs-team#236]
# Proposal

## Problem statement

Given a unix `SocketAddr` from `recv_from`, I'd like to compare it to a previous `SocketAddr` I generated. I'd also like to map it to some other value (e.g. via a `HashMap`).

## Motivating examples or use cases

I have a specific crate where I want to use `SocketAddr` values as "tags" to identify incoming data. Rather than sprinkle special-cases in the code to compare pathnames or compare abstract names, I'd like to just store and compare the `SocketAddr` values directly, or use them as keys in a `HashMap`.

## Solution sketch

`derive(PartialEq, Eq, PartialOrd, Ord, Hash)` for the internal `AddressKind` type, then add trivial implementations of `PartialEq` and `PartialOrd` and `Hash` for `SocketAddr` by forwarding to the `AddressKind` implementations.

`std::net::SocketAddr` already implements all of these traits.

## Alternatives

I could write an equality comparison via existing APIs; it would look roughly like:

```rust
fn some_eq<T: Eq>(lhs: Option<T>, rhs: Option<T>) -> bool {
    if let Some(lhs) = lhs {
        if let Some(rhs) = rhs {
            return lhs == rhs;
        }
    }
    false
}
if some_eq(lhs.as_pathname(), rhs.as_pathname()) || (lhs.is_unnamed() && rhs.is_unnamed()) {
    return true;
}
#[cfg(target_os = "linux")]
if some_eq(lhs.as_abstract_name(), rhs.as_abstract_name()) {
    return true;
}
return false;
```

This seems much more cumbersome and duplicative, and would be even more painful for `PartialOrd` or `Hash`.

We could expose the underlying address as bytes, which the user could compare. This would also expose the user to any platform-specific quirks we would otherwise abstract over, whether currently or in the future. Would that make users have to deal with any of those quirks? In addition, once people start directly comparing the bytes, we can't hide those in the future. That would also prevent us from switching our representation in the future to something that doesn't directly store a `sockaddr_un` (e.g. if we wanted to store something more like the `Address` enum). Most importantly, though, that wouldn't allow `derive` of any of these traits on a structure containing `SocketAddr`.

## What happens now?

This issue is part of the libs-api team [API change proposal process]. Once this issue is filed the libs-api team will review open proposals as capability becomes available. Current response times do not have a clear estimate, but may be up to several months.

[API change proposal process]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html

## Possible responses

The libs team may respond in various different ways. First, the team will consider the *problem* (this doesn't require any concrete solution or alternatives to have been proposed):

- We think this problem seems worth solving, and the standard library might be the right place to solve it.
- We think that this probably doesn't belong in the standard library.

Second, if there's a concrete solution:

- We think this specific solution looks roughly right, approved, you or someone else should implement this. (Further review will still happen on the subsequent implementation PR.)
- We're not sure this is the right solution, and the alternatives or other materials don't give us enough information to be sure about that. Here are some questions we have that aren't answered, or rough ideas about alternatives we'd want to see discussed.

**Comment by the8472** [comment]
For clarity, you mean `unix::SocketAddr`? Because we have `net::SocketAddr` too.

I would be somewhat concerned about supporting other socket types but it already says 

> An address associated with a Unix socket.

so I guess that ship sailed.

**Comment by m-ou-se** [comment]
Is there a good/clear definition of 'equality' that everyone would expect? Would one expect `unnamed` to compare equal or unequal to itself?

Since sockaddr_un just has a char[], perhaps exposing as_bytes() or as_chars() is an alternative to consider.

**Comment by joshtriplett** [comment]
@m-ou-se I don't think a bytewise comparison would work; that would expose users to some platform-specific quirks that we handle (now or in the future). For instance, there seems to be a quirk on macOS with unnamed sockets.

Nonetheless, I'll record it as a possible alternative.

**Comment by m-ou-se** [comment]
> For instance, there seems to be a quirk on macOS with unnamed sockets.

I think that would work just fine. On macOS you'd just get `&[0; 16]` for unnamed sockaddrs, but that seems fine for comparing and hashing.

**Comment by joshtriplett** [comment]
@m-ou-se You're right, that one would likely work, assuming that macOS uniformly returns the same representation for an unnamed address from any context.

**Comment by joshtriplett** [comment]
Summarizing discussion from today's @rust-lang/libs-api meeting: there's some disagreement over whether two `SocketAddr` values with `is_unnamed()` should compare equal or not. I argued that they should compare equal, as the underlying values are semantically equal (there is no address). Some people argued that they should not compare equal, thinking of the underlying value as more like a float NaN because different connections from different clients can all be unnamed. The discussion didn't reach a consensus yet.

**Comment by thomcc** [comment]
I'm often an IEEE754 defender but the NaN semantics have a long history of being very surprising to users, and are a mistake we probably shouldn't repeat elsewhere.

**Comment by pitaj** [comment]
`Hash` doesn't seem very useful without `Eq`, but we can always leave those for a second FCP at a later point if they are highly requested.

**Comment by m-ou-se** [comment]
We discussed this again today. While there were some concerns about equality of empty/unnamed addresses, we discussed the alternatives and thought that what's proposed in this ACP is probably the best alternative. If you open a PR for this we can FCP it. :)
