### ISSUE TITLE
thread::sleep_until, wait until a deadline is reached

### ISSUE THREAD

**Issue by dvdsk** [rust-lang/libs-team#237]
# Proposal

## Problem statement
There is no method to pause a thread until a deadline is reached. Currently that means writing one yourself. I argue the use case is common enough that it is worth it to bring this into the std. It would make code that needs this slightly shorter,  a bit more readable and easier to write. 

Last but not least while a pause until method is not hard to write it is easy to do incorrectly without noticing. A naive approach subtracts the deadline from `Instant::now()`. Currently, this works, however it might panic in the future see [Monotonicity](https://doc.rust-lang.org/std/time/struct.Instant.html#monotonicity) and [Instant::sub](https://doc.rust-lang.org/std/time/struct.Instant.html#impl-Sub%3CInstant%3E-for-Instant). Adding `sleep_until` lessens the impact of future rust versions panicking again a bit.

## Motivating examples or use cases

Most use-cases take the shape of a planning problem, performing some action at a set moment. For example today I wanted to use `sleep_until` to exponentially back off on requesting a certificate up to a deadline. Like any web request it may take a while before it fails, therefore we must take the time the work takes into account.

```rust
const MAX_DURATION: Duration = Duration::from_secs(10);
let mut next_attempt = Instant::now();
let deadline = Instant::now() + MAX_DURATION;
let mut delay = Duration::from_millis(250);

loop {
    if Instant::now() > deadline {
        break Err(()),
    }
    // get_signed_certificate also takes some time
    if let Ready(cert) = get_signed_certificate() {
        break Ok(cert),
    }

    delay *= 2;
    next_attempt = deadline.min(next_attempt + delay);
    sleep_until(next_attempt);
}
```

This can be generalized by replacing `get_signed_certificate` with any fallible function that takes a non-trivial amount of time. 

On GitHub there are about 3k hits for rust code containing `fn sleep_until`. Though a minor argument, having this in the std could help porting async code using _tokios_ `sleep_until` easier.

## Solution sketch

I propose we make the solution look like the `sleep_until` function in [tokio::time::sleep_until](https://docs.rs/tokio/latest/tokio/time/fn.sleep_until.html). 

The API:
```
pub fn sleep_until(deadline: Instant);
```

The implementation:
```rust
// proposed implementation
pub fn sleep_until(deadline: Instant) {
    let now = Instant::now();
    
    // if now is after the deadline do not sleep
    if let Some(delay) = deadline.checked_duration_since(now) {
        thread::sleep(delay);        
    }
}
```
[playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=98c862dc44277844fe49104230932f21)

## Alternatives

If we chose not to implement `sleep_until` an example should be added to `thread::sleep` to steer users away from using subtract on two `Instant`s.

## Links and related work

 - This was previously brought up last year as an alternative to https://github.com/rust-lang/libs-team/issues/55. 
 - In 2017 it was [proposed](https://github.com/rust-lang/rust/issues/46316) to use the `_until` suffix instead of `_deadline` for functions that do not have meaningful blocking versions such as the thread::sleep family.

## What happens now?

This issue is part of the libs-api team [API change proposal process]. Once this issue is filed the libs-api team will review open proposals as capability becomes available. Current response times do not have a clear estimate, but may be up to several months.

[API change proposal process]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html

_if the libs-api team decides to adopt this proposal I would like to implement the RFC_

**Comment by the8472** [comment]
The other issue is the eternal question whether one wants to sleep for a duration including or excluding system suspend time. The answer often differs depending on the kind of task that is sleeping.
That is currently inconsistent across different operating systems.

**Comment by dvdsk** [comment]
> > There is no method to pause a thread until a deadline is reached. A naive approach subtracts the deadline from Instant::now(). Currently, this works, however it might panic in the future see [Monotonicity](https://doc.rust-lang.org/std/time/struct.Instant.html#monotonicity) and [Instant::sub](https://doc.rust-lang.org/std/time/struct.Instant.html#impl-Sub%3CInstant%3E-for-Instant).
> 
> The section also points to `checked_duration_since` as a guranteed panic-free option. So if _that_ is the motivation... the problem is already solved?

Ahh sorry, what I meant is that because there is no `sleep_until` in the std people tend to implement it themselves. While they can do that correctly using `checked_duration_since` that assumes they noticed the issue with `Monotonicity`. That requires them to look at the `sub` implementation documentation. I am not usually that careful and I think I am not alone in that.

I will edit the RFC and clarify that section. I will also add code readability for completeness.

**Comment by dvdsk** [comment]
> The other issue is the eternal question whether one wants to sleep for a duration including or excluding system suspend time.

In my opinion `thread::sleep_until` should have the same behavior as `thread::sleep` currently has. Otherwise it could get quite confusing.

**Comment by Amanieu** [comment]
We discussed this in the @rust-lang/libs-api meeting today and are mostly happy with this proposal. We did discuss the possibility of support multiple clock sources (`SystemTime`, `Instant`, some sort of CLOCK_BOOTTIME, etc), but this question can be deferred for now until the stabilization of this feature.

**Comment by dvdsk** [comment]
Thanks for accepting the proposal! 

I am looking into the various APIs/platforms right now, trying to find a consistent clock source. Once I have learned a bit more I will hammer out an implementation and open a tracking issue and PR.

**Comment by neachdainn** [comment]
I just want to point out that the proposed solution isn't a full solution in that it ignores the possibility of drift which doesn't matter for many implementations but is critical in situations where it does matter. Specifically:

```rust
pub fn sleep_until(deadline: Instant) {
    let now = Instant::now();
    
   // What if the thread is suspended here? If that happens, you are no longer sleeping until `deadline` but
   // are instead sleeping until `deadline + epsilon` which is not universally acceptable. The relevant OS's
   // have operations to do actual deadline sleeping and those should be used here.
    
    if let Some(delay) = deadline.checked_duration_since(now) {
        thread::sleep(delay);        
    }
}
```
