### ISSUE TITLE
Make `PartialOrd for Vec` allocator independent

### ISSUE THREAD

**Issue by gootorov** [rust-lang/libs-team#240]
# Proposal

## Problem statement

`PartialOrd` cannot currently be used on vectors allocated with different allocators.

## Motivating examples or use cases

* It is consistent with [`PartialEq<Vec<U, A2>> for Vec<T, A1>`](https://doc.rust-lang.org/std/vec/struct.Vec.html#impl-PartialEq%3CVec%3CU,+A2%3E%3E-for-Vec%3CT,+A1%3E).
* Writing tests for/using data structures that are parameterized by an allocator may be tedious due to the fact that an underlying vector cannot be compared with different allocators.

## Solution sketch

See PR: https://github.com/rust-lang/rust/pull/112632

## Alternatives

Compare underlying slices via `Deref<Target = [T]>`.

**Comment by dtolnay** [comment]
Seems good to me.

Let's do a libs-api team FCP on your PR, since this would need to be instantly stable.

**Comment by thomcc** [comment]
It's not insta-stable because Allocator isn't stable.

**Comment by dtolnay** [comment]
You are right, good call.
