### ISSUE TITLE
Make `Box` comparisons independent of allocator choice

### ISSUE THREAD

**Issue by gootorov** [rust-lang/libs-team#241]
# Proposal

## Problem statement

Comparing `Box`s that are allocated by different allocators via `PartialEq` or `PartialOrd` is not currently possible.

## Motivating examples or use cases

* It is consistent with [`PartialEq<Vec<U, A2>> for Vec<T, A1>`](https://doc.rust-lang.org/std/vec/struct.Vec.html#impl-PartialEq%3CVec%3CU,+A2%3E%3E-for-Vec%3CT,+A1%3E).
*  I'm writing a library that uses a specific allocator internally. For tests, I'd like to be able to declaratively define data that is `expected`, and compare it with data that I `got`. Resorting to `Deref<Target = T>` and comparing individual fields may be very tedious in cases when the data in question contains several layers of types internally, and especially enums. 

## Solution sketch

See PR: https://github.com/rust-lang/rust/pull/112628

## Alternatives

* Compare `Box`s via `Deref<Target = T>`.
* Make sure to use the same allocator everywhere.

**Comment by m-ou-se** [comment]
We discussed this briefly in the libs-api meeting. This is fine. Since this doesn't affect the stable API (as Boxes with a custom allocator are unstable), this doesn't need to go through FCP.
