### ISSUE TITLE
proc_macro: Implementation of Extend (parameterized over Group, Ident, Punct, and Literal) for TokenStream

### ISSUE THREAD

**Issue by JohnScience** [rust-lang/libs-team#242]
# Proposal

## Problem statement

At the moment of writing, [`proc_macro::TokenStream`](https://doc.rust-lang.org/beta/proc_macro/struct.TokenStream.html) implements parametrizations of [`core::iter::Extend`](https://doc.rust-lang.org/beta/core/iter/trait.Extend.html) over `proc_macro::TokenStream` and [`proc_macro::TokenTree`](https://doc.rust-lang.org/proc_macro/enum.TokenTree.html), i.e. `Extend<TokenStream>` and `Extend<TokenTree>`. However, it is not implemented for parametrizations of `Extend` over

1. [`proc_macro::Group`](https://doc.rust-lang.org/proc_macro/struct.Group.html)
2. [`proc_macro::Ident`](https://doc.rust-lang.org/proc_macro/struct.Ident.html)
3. [`proc_macro::Punct`](https://doc.rust-lang.org/proc_macro/struct.Punct.html)
4. [`proc_macro::Literal`](https://doc.rust-lang.org/proc_macro/struct.Literal.html)

which all can can be stored in respective variants of `TokenTree`.

I believe that this is a problem because it either

1. causes unnecessary verbosity/boilerplate when one of `Group`, `Ident`, `Punct`, or `Literal`, is added to a `TokenStream`, as will be demonstrated further; or
2. forces the developers to implement a local twin of `Extend` that they would implement for `TokenStream`, either manually or using a non-standard library.

Such inconveniences could push developers use [`quote`](https://crates.io/crates/quote), which results in higher compile times, even in situations where `proc_macro` with the proposed changes would suffice.

Also, it *probably* results in higher compile times in projects which extensively use procedural macros because these macros have to generate more Rust syntax.

## Motivating examples or use cases

Before:

```rust
use proc_macro::{TokenStream, TokenTree, Ident, Span};
let mut ts = TokenStream::new();
ts.extend(iter::once(TokenTree::Ident(Ident::new("new_ident", Span::call_site()))));
```

After:

```rust
use proc_macro::{TokenStream, TokenTree, Ident, Span};
let mut ts = TokenStream::new();
ts.extend(iter::once(Ident::new("new_ident", Span::call_site())));
```

Once (or when) `Extend::extend_one` stabilizes, the difference will be even more noticeable.

Before:

```rust
use proc_macro::{TokenStream, TokenTree, Ident, Span};
let mut ts = TokenStream::new();
ts.extend_one(TokenTree::Ident(Ident::new("new_ident", Span::call_site())));
```

After:

```rust
use proc_macro::{TokenStream, TokenTree, Ident, Span};
let mut ts = TokenStream::new();
ts.extend_one(Ident::new("new_ident", Span::call_site()));
```

## Solution sketch

```rust
impl Extend<Group> for TokenStream {
    fn extend<I: IntoIterator<Item = Group>>(&mut self, groups: I) {
        self.extend(groups.into_iter().map(TokenTree::Group))
    }
}

// And so on for the 3 remaining items, or we can use a macro_rules! for that.
```

## Alternatives

Leave it as it is and delegate the implementation to a non-standard library via an extension trait that would be a twin of `Extend`. I dislike this approach because all these types belong to standard libraries and it would result in unnecessary complexity.

## Links and related work

* Rust internals discussion ["Opinion: `proc_macro::TokenStream` should implement Extend<proc_macro::Group>, etc "](https://internals.rust-lang.org/t/opinion-proc-macro-tokenstream-should-implement-extend-proc-macro-group-etc/19022).

**Comment by dtolnay** [comment]
Seconded. Please send PR.

**Comment by jyn514** [comment]
> It's my first contribution to the standard library so I might make some silly mistakes as I make it happen. In order to make the development of the PR more transparent, I'll document what I'm doing along the way.

@JohnScience this is *extremely* helpful, thank you ❤️ i don't have time right now but i plan to improve several of the issues you mentioned this weekend

**Comment by jyn514** [comment]
> **Q: should the doc be updated to make it aware of Windows?**

I've opened https://github.com/rust-lang/rustc-dev-guide/pull/1701/files?short_path=cdf7c1e#diff-cdf7c1e6d2d1ec81510204b0c3250cb2c90880843f005bb942bafb84996a90b0 to improve the docs here.

> and after asking on official Discord server in `#contribute` channel figured out that the point of that lint is to prevent the mess from growing. I haven't figured out whether it goes to `proc-macro` or `feature-gates`, so I chose `proc-macro`.

I made this error from tidy more helpful in https://github.com/rust-lang/rust/pull/113008/files#diff-31008ceb5198220e3ec8834cac868728b9db572697eb5a14e48b402edc9c2246.

> **Q: I guess I should report this bug later?**

I cannot replicate this bug. It looks like you're using cmd.exe, but when I run `x test library/proc_macro` in cmd it does the right thing automatically. Are you sure that you've added `~/.cargo/bin` to PATH?

> Tried `./x.py setup` on Windows. Got the following error:

We do not really support `cmd.exe`; it's horribly limited in what it can do. Powershell should work a lot better. I tried to document that in the rustc-dev-guide PR.

> **Q: I haven't found the list of the comments in the Rust Compiler Development Guide. Is it a thing that is yet to be documented?**

This is documented at https://rustc-dev-guide.rust-lang.org/tests/headers.html#header-commands. I'm not sure how to make it easier to find.

> * Started playing around with `rg` and [`huniq`](https://crates.io/crates/huniq) to find more comments but the terminal crashed. Due to that, I decided to create a test using only limited knowledge.
> 
>     * Faced problem related to `LF` vs `CRLF`. Fixed it in Visual Studio Code.
> 
> **Q: Can't git hook either propose changes or apply them automatically?**

Can you talk more about the error you ran into here? do you mean this?

```
tidy check
tidy error: C:\Users\vboxuser\rust\tests\ui\feature-gates\foo.rs:1: CR character
```
it would be helpful if you could open an issue on rust-lang/rust asking for this to be `--bless`able :)
