### ISSUE TITLE
Add `ptr::addr_eq` for use with pointers-to-DSTs

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/libs-team#274]
# Proposal

## Problem statement

As discussed in https://github.com/rust-lang/rust/issues/106447 (and in the 2023-09-26 lang meeting that inspired this ACP), equality for pointers to DSTs is awkward.

## Motivating examples or use cases

If we're going to work towards deprecating it, it would help to have methods with clear intent that people could use instead.  That won't be a 100% solution (not even close), but at least there'd be a simple

## Solution sketch

in core::ptr and std::ptr
```rust
/// Compares the *addresses* of the two pointers for equality,
/// ignoring any metadata in fat pointers.
///
/// If the arguments are thin pointers of the same type,
/// then this is the same as [`ptr::eq`].
///
/// # Examples
///
/// ```
/// let a = [1, 2, 3];
/// let slice = &a[..];
/// let first = &a[0];
/// assert!(std::ptr::addr_eq(slice, first));
/// assert!(!std::ptr::eq::<dyn Debug>(slice, first));
/// ```
pub fn addr_eq<T: ?Sized, U: ?Sized>(p: *const T, q: *const U) -> bool {
    (p as *const ()) == (q as *const ())
}
```

## Alternatives

- Different name?  Method instead of function?
- I wrote it heterogeneous since address comparison works fine like that, but homogeneous could also make sense.
- Newtypes that change the `PartialEq` implementation?
- Different pointer type entirely?
- Additional functions for `addr_and_meta_eq` or something?

## What happens now?

This issue is part of the libs-api team [API change proposal process]. Once this issue is filed the libs-api team will review open proposals as capability becomes available. Current response times do not have a clear estimate, but may be up to several months.

[API change proposal process]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html

## Possible responses

The libs team may respond in various different ways. First, the team will consider the *problem* (this doesn't require any concrete solution or alternatives to have been proposed):

- We think this problem seems worth solving, and the standard library might be the right place to solve it.
- We think that this probably doesn't belong in the standard library.

Second, if there's a concrete solution:

- We think this specific solution looks roughly right, approved, you or someone else should implement this. (Further review will still happen on the subsequent implementation PR.)
- We're not sure this is the right solution, and the alternatives or other materials don't give us enough information to be sure about that. Here are some questions we have that aren't answered, or rough ideas about alternatives we'd want to see discussed.

**Comment by dtolnay** [comment]
Seconded! Feel free to send a PR implementing this. Thank you!
