### ISSUE TITLE
ACP: `Duration::abs_diff`

### ISSUE THREAD

**Issue by elomatreb** [rust-lang/libs-team#291]
# Proposal

## Problem statement

I would like to be able to get the absolute difference between two `std::time::Duration` values, without going through a manual "compare and subtract" dance.

## Motivating examples or use cases

In a personal project I have some code that compares durations of music albums, and considers them close enough if they are within a certain threshold (because of sub-second rounding differences).

## Solution sketch

I would like to propose adding a `Duration::abs_diff` method mirroring the existing `abs_diff` methods on primitive integers.

```rs
impl Duration {
    pub fn abs_diff(self, other: Duration) -> Duration {
        // ...
    }
}
``` 

## Alternatives

It's perfectly possible to do this sort of thing using existing APIs, but it's verbose and potentially error-prone (e.g. the order of operations might be the wrong way around leading to a potential runtime panic). The manual implementation would be the following:

```rs
let abs_diff = if a < b {
    b - a
} else {
    a - b
};
```

## Links and related work

n/a

## What happens now?

This issue contains an API change proposal (or ACP) and is part of the libs-api team [feature lifecycle]. Once this issue is filed, the libs-api team will review open proposals as capability becomes available. Current response times do not have a clear estimate, but may be up to several months.

[feature lifecycle]: https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html

## Possible responses

The libs team may respond in various different ways. First, the team will consider the *problem* (this doesn't require any concrete solution or alternatives to have been proposed):

- We think this problem seems worth solving, and the standard library might be the right place to solve it.
- We think that this probably doesn't belong in the standard library.

Second, if there's a concrete solution:

- We think this specific solution looks roughly right, approved, you or someone else should implement this. (Further review will still happen on the subsequent implementation PR.)
- We're not sure this is the right solution, and the alternatives or other materials don't give us enough information to be sure about that. Here are some questions we have that aren't answered, or rough ideas about alternatives we'd want to see discussed.

**Comment by dtolnay** [comment]
Seconded; please send a standard library PR! Thanks.
