### ISSUE TITLE
Add `array::repeat` for making an array from a non-`Copy` non-`const` value

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/libs-team#310]
# Proposal

## Problem statement

For a type that's copy, `[x; N]` works great for getting an array.
For a constructor that's const, `[const { Foo::new() }; N]` works great (or hopefully will soon) for getting an array.

However, if you have a general `String` value that you want to repeat, there's no great way right now.

We should add one.

## Motivating examples or use cases

Like how `vec![x; N]` supports non-`Copy` values, we should have a way to do that for normal arrays too.

See zulip thread <https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/syntactical.20parallelism.20for.20multiple.20clones/near/403589163>

As an interesting bonus, this would also let `array::repeat(x)` work inferring the length in many cases, which could actually be a nice thing to use even with `Copy` types, until `[x; _]` (or however we spell that) ends up happening.

## Solution sketch

This is trivial to implement in `core` with the existing internal methods:

```rust
// in core::array

pub fn repeat<T: Clone, const N: usize>(x: T) -> [T; N] {
    from_trusted_iterator(iter::repeat_n(x, N))
}
```

## Alternatives

The simplest option is `array::from_fn(|_| x.clone())`, but that's sub-optimal in that it never re-uses the original value, likely losing capacity -- since the whole reason to not be using `[x; N]` in the first place is that the type isn't `Copy`, and thus plausibly has a non-trivial `Drop`.

Fixing that takes something like [this (from Kevin Reid)](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/syntactical.20parallelism.20for.20multiple.20clones/near/403668669):
```rust
fn dup<T: Clone, const N: usize>(v: T) -> [T; N] {
    let mut buf = Some(v);
    core::array::from_fn(|i| if i == N - 1 { buf.take() } else { buf.clone() }.unwrap())
}
```

But that's far more complicated, and doesn't necessarily optimize well either.  It could be done with `unsafe`, but once that's happening it's probably good to have it in `core` again to encapsulate the unsafe in a known-safe interface.

## What happens now?

This issue contains an API change proposal (or ACP) and is part of the libs-api team [feature lifecycle]. Once this issue is filed, the libs-api team will review open proposals as capability becomes available. Current response times do not have a clear estimate, but may be up to several months.

[feature lifecycle]: https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html

## Possible responses

The libs team may respond in various different ways. First, the team will consider the *problem* (this doesn't require any concrete solution or alternatives to have been proposed):

- We think this problem seems worth solving, and the standard library might be the right place to solve it.
- We think that this probably doesn't belong in the standard library.

Second, if there's a concrete solution:

- We think this specific solution looks roughly right, approved, you or someone else should implement this. (Further review will still happen on the subsequent implementation PR.)
- We're not sure this is the right solution, and the alternatives or other materials don't give us enough information to be sure about that. Here are some questions we have that aren't answered, or rough ideas about alternatives we'd want to see discussed.

**Comment by ChayimFriedman2** [comment]
Perhaps instead of adding more and more iterator-like function to arrays, we should just have a `collect_array()` method on iterators?

**Comment by Amanieu** [comment]
It seems like there are 2 separate motivations here, which each have different optimal solutions.

If the primary concern is the syntax, then `array::repeat` is a good solution: it's simple an easy to use.

If the primary concern is performance due to multiple refcount increments, then a more general solution would be a way to increment an `Arc` multiple times at once and then return the new `Arc`s in an iterator:

```rust
impl Arc<T> {
    fn increment_multiple(self: Self, n: usize) -> impl Iterator<Item = Arc<T>>;
}
```

**Comment by the8472** [comment]
Hrm, that reminds me of the java feature where the method-reference syntax can create instance bound ~closures.

I.e. one would just write `repeat(clonable)` as `from_fn(clonable::clone)`

**Comment by Amanieu** [comment]
We discussed this in the @rust-lang/libs-api meeting and are happy to accept it!
