### ISSUE TITLE
Yank published `libtest`

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/libs-team#319]
As mentioned in https://github.com/rust-lang/docs.rs/issues/2344 the published https://crates.io/crates/libtest can be confusing for search results. Given the experiment in extracting it out-of-repo appears to have at least stalled, it would be nice to have this yanked from crates.io so that it will be removed from search results both there and on docs.rs.

**Comment by cuviper** [comment]
I went ahead and yanked it. We can always unyank if that's deemed a mistake.
