### ISSUE TITLE
Support const trait impls in unstable-api tool

### ISSUE THREAD

**Issue by yaahc** [rust-lang/libs-team#33]
The unstable-api tool is currently broken and always errors out with "expected identifier" when run against the rust codebase. The issue seems to be caused by the following impl:

```rust
#[stable(feature = "rust1", since = "1.0.0")]
#[rustc_const_unstable(feature = "const_deref", issue = "88955")]
impl<B: ?Sized + ToOwned> const Deref for Cow<'_, B>
where
    B::Owned: ~const Borrow<B>,
{
    type Target = B;

    fn deref(&self) -> &B {
        match *self {
            Borrowed(borrowed) => borrowed,
            Owned(ref owned) => owned.borrow(),
        }
    }
}
```

To fix this we will need to update syn to support this new syntax: https://github.com/dtolnay/syn/issues/1051

**Comment by dtolnay** [comment]
Const trait impls such as this one have been removed from the standard library since https://github.com/rust-lang/rust/pull/110393.
