### ISSUE TITLE
Implement ExactSizeIterator for Flatten<option::IntoIter<I>>

### ISSUE THREAD

**Issue by SOF3** [rust-lang/libs-team#332]
# Proposal

## Motivating examples or use cases

```rs
fn iter_if<T>(cond: bool, inner: impl ExactSizeIterator<Item = T>) -> impl ExactSizeIterator<Item = T> {
    cond.then(|| inner).into_iter().flatten()
}
```

cannot compile because

> error[E0277]: the trait bound `Flatten<std::option::IntoIter<impl ExactSizeIterator<Item = T>>>: ExactSizeIterator` is not satisfied

## Solution sketch

In reality, the exact size can be inferred from the underlying iterator directly, something like this:

```rs
match self.inner.as_ref() {
    None => (0, Some(0)),
    Some(iter) => iter.size_hint(),
}
```

However this requires specialization on the `size_hint` impl of `FlattenCompat`.

## Alternatives

Or we could just add an `into_iter_flatten()` method on `Option`, which returns `IntoIterFlatten<I>` that basically reimplements `Flatten<option::IntoIter<I>>`.

**Comment by the8472** [comment]
This doesn't work because they can be `Option::None` which flatten into zero items.

**Comment by SOF3** [comment]
@the8472 Isn't that what the `None => (0, Some(0))` line is supposed to handle?

**Comment by the8472** [comment]
Oh, sorry, I was thinking about flattening an iterator that yields `option::IntoIter`, not directly flattening an option iterator.

So `iter_if` could also be implemented using `itertools::Either`

```rust
fn iter_if<T>(cond: bool, inner: impl ExactSizeIterator<Item = T>) -> impl ExactSizeIterator<Item = T> {
    if cond {
       return Either::Left(inner)
    }
    return Either::Right(iter::empty())
}

**Comment by the8472** [comment]
We discussed this during a libs-API meeting and concluded that this would probably be ok to add we generally don't expose API guarantees for things that depend on specialization.

So until specialization is on a path to stabilization we'll consider this blocked.
We're closing it for now to take it off our agenda. Please reopen when the situation changes.
