### ISSUE TITLE
Add `HashMapEntry` and `BTreeMapEntry` aliases to `std::collections`

### ISSUE THREAD

**Issue by GrigorenkoPV** [rust-lang/libs-team#340]
# Proposal: in `std::collections` add `{Hash,BTree}MapEntry` as an alias for `{hash,btree}_map::Entry`

## Problem statement

Has this happened to you?

```rust
use std::collections::hash_map::Entry as HashMapEntry;
```

## Motivating examples or use cases

It surely has happened to:
- [tikv](https://github.com/tikv/tikv/blob/66847e9c5ac701e73da1366938a7e2306cacc671/components/collections/src/lib.rs#L11)
- [cargo-depgraph](https://github.com/jplatte/cargo-depgraph/blob/96d4d0bd69457b4d7647302a5e83e7c1ae627fb5/src/graph/build.rs#L1)
- [Rust X11 bindings](https://github.com/psychon/x11rb/blob/6592b386021f86fd35c13d77b821f7e9ed780591/x11rb/src/extension_manager.rs#L3)
- [shadow](https://github.com/shadow/shadow/blob/53f18878c159a8b5effdbbcfa6256db8d63a5e40/src/main/host/descriptor/epoll/mod.rs#L1)
- [Rust port of Lucene](https://github.com/zhihu/rucene/blob/5b55f842c2bb03beb96898d520e880c180c91adf/src/core/store/directory/mmap_directory.rs#L14)
- [CodeChain](https://github.com/CodeChain-io/codechain/blob/9964d028e0b4c51443e59526a1aa4708f4d99b38/state/src/cache/write_back.rs#L20)
- [Hey! Listen!](https://github.com/Lakelezz/hey_listen/blob/c3f3d746b74d456e90ee1292e498a926e0c9b057/src/sync/priority_dispatcher.rs#L4) (notable for having `BTreeMapEntry` too)
- And [many others](https://github.com/search?q=HashMapEntry+language%3ARust&type=code&l=Rust&p=2).

Not to mention that most of the contents in `std::colections::{hash,btree}_map` are "internal" things like iterator implementations, which you rarely ever have to refer to directly. Unlike with `Entry`, which is a surprisingly versatility API that lends itself especially well with Rust's pattern matching. But then you have to name the type, and generally you have the following options:
1. Fully qualified name (long, not pretty).
2. `use std::collections::hash_map;` and then refer to it as `hash_map::Entry`. But importing an entire module just to refer to a single type inside doesn't sit right with me.
3. `use std::collections::hash_map::Entry;`. Suboptimal, the name is too vague and might collide.
4. `use std::collections::hash_map::Entry as HashMapEntry;`

## Solution sketch

Add these two lines (plus the neccessary attributes) to `alloc/collections/mod.rs` & `srd/collections/mod.rs`:
```rust
pub use btree_map::Entry as BTreeMapEntry;
pub use hash_map::Entry as HashMapEntry;
```

Sadly, this is a breaking change because of the glob imports. But I guess this can be done across an edition boundary?

## Alternatives

1. Do not do anything
2. `type HashMapEntry<'a, K, V, A = Global> = hash_map::Entry<'a, K, V, A>;` (sounds even worse).

**Comment by Amanieu** [comment]
We discussed this in the libs-api meeting. The overall feeling was against adding these aliases. As you've mentioned, it's already possible to do this yourself with the following code:
```rust
use std::collections::hash_map::Entry as HashMapEntry
```

With that said, there was interest in adding a type alias on the `HashMap` type itself, which would allow the `Entry` type to be named with `HashMap::Entry`. However this is blocked on inherent associated types (https://github.com/rust-lang/rust/issues/8995) which are still unstable and in an incomplete state due to compiler limitations.
- You can already do this
- inherent associated type in future

**Comment by GrigorenkoPV** [comment]
I agree, an associated alias sounds better.

And since this is a rather unimportant change, it can easily wait.

Thanks for the review!
