### ISSUE TITLE
ACP: Add `impl Display` variant to print `Duration` as decimal seconds

### ISSUE THREAD

**Issue by dead-claudia** [rust-lang/libs-team#351]
# Proposal

## Problem statement

There's no easy way to print a duration as seconds without potential loss of precision. One could use `format!("{}", duration.to_secs_f64())`, but that loses precision after about 3 months (experimentally, I found 8388608.000000001 seconds to be the first duration printed imprecisely, equating to 97 days, 2 hours, 10 minutes, 7 seconds, and 1 nanosecond).

## Motivating examples or use cases

[Run this program to see what I mean](https://rust.godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:rust,selection:(endColumn:45,endLineNumber:4,positionColumn:45,positionLineNumber:4,selectionStartColumn:45,selectionStartLineNumber:4,startColumn:45,startLineNumber:4),source:'use+std::time::Duration%3B%0A%0Apub+fn+main()+%7B%0A++++let+duration1+%3D+Duration::new(10_000_000,+1)%3B%0A++++let+duration2+%3D+Duration::new(1,+1)%3B%0A%0A++++println!!(%22duration1:%22)%3B%0A++++println!!(%22++++debug:+%7B:%3F%7D%22,+duration1)%3B%0A++++println!!(%22++++f32:+++%7B%7D%22,+duration1.as_secs_f32())%3B%0A++++println!!(%22++++f64:+++%7B%7D%22,+duration1.as_secs_f64())%3B%0A++++println!!(%22duration2:%22)%3B%0A++++println!!(%22++++debug:+%7B:%3F%7D%22,+duration2)%3B%0A++++println!!(%22++++f32:+++%7B%7D%22,+duration2.as_secs_f32())%3B%0A++++println!!(%22++++f64:+++%7B%7D%22,+duration2.as_secs_f64())%3B%0A%7D'),l:'5',n:'0',o:'Rust+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:executor,i:(argsPanelShown:'1',compilationPanelShown:'0',compiler:r1760,compilerName:'',compilerOutShown:'0',execArgs:'',execStdin:'',fontScale:14,fontUsePx:'0',j:1,lang:rust,libs:!(),options:'',source:1,stdinPanelShown:'1',wrap:'1'),l:'5',n:'0',o:'Executor+rustc+1.76.0+(Rust,+Editor+%231)',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4):

```js
use std::time::Duration;

pub fn main() {
    let duration1 = Duration::new(10_000_000, 1);
    let duration2 = Duration::new(1, 1);

    println!("duration1:");
    println!("    debug: {:?}", duration1);
    println!("    f32:   {}", duration1.as_secs_f32());
    println!("    f64:   {}", duration1.as_secs_f64());
    println!("duration2:");
    println!("    debug: {:?}", duration2);
    println!("    f32:   {}", duration2.as_secs_f32());
    println!("    f64:   {}", duration2.as_secs_f64());
}
```

For context, 10 million seconds is about 115 days. While this might seem nonsensical for most, this *could* come up in Prometheus expositions, where the protocol *expects* durations to be printed in decimal seconds at millisecond precision, and [nanosecond-resolution timestamps are a thing in the relevant spec](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#timestamps-1).

Also, it'd be nice to have a pretty printer that didn't rely on the FPU, for low-end MCUs and just generally smaller, simpler code.

## Solution sketch

Maybe a `duration.display_seconds()` that returns an `impl Display` that prints a nanosecond-precision timestamp. Assuming [this helper in `impl fmt::Debug for Duration`](https://github.com/rust-lang/rust/blob/master/library/core/src/time.rs#L1185-L1342) was extracted out:

```rs
pub struct DisplaySeconds(Duration);

impl fmt::Display for DisplaySeconds {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // Print leading '+' sign if requested
        let prefix = if f.sign_plus() { "+" } else { "" };
        fmt_decimal(f, self.0.secs, self.0.nanos.0, NANOS_PER_SEC / 10, prefix, "")
    }
}

impl Duration {
    pub fn display_seconds(&self) -> DisplaySeconds {
        DisplaySeconds(*self)
    }
}
```

## Alternatives

One could also provide that via `impl Display for Duration`. The `Debug` implementation for >1s durations already does exactly what I'm proposing here, so there's *some* precedent already.

Assuming [this helper in `impl fmt::Debug for Duration`](https://github.com/rust-lang/rust/blob/master/library/core/src/time.rs#L1185-L1342) was extracted out, it'd look like this:

```rs
impl fmt::Display for Duration {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // Print leading '+' sign if requested
        let prefix = if f.sign_plus() { "+" } else { "" };
        fmt_decimal(f, self.secs, self.nanos.0, NANOS_PER_SEC / 10, prefix, "")
    }
}
```

## Links and related work

[The existing workhorse implementation for `impl fmt::Debug for core::Duration`](https://github.com/rust-lang/rust/blob/master/library/core/src/time.rs#L1185-L1342) implements 99% of this already. Only difference is it also writes a suffix that, for this, would need to be an empty string.

## What happens now?

This issue contains an API change proposal (or ACP) and is part of the libs-api team [feature lifecycle]. Once this issue is filed, the libs-api team will review open proposals as capability becomes available. Current response times do not have a clear estimate, but may be up to several months.

[feature lifecycle]: https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html

## Possible responses

The libs team may respond in various different ways. First, the team will consider the *problem* (this doesn't require any concrete solution or alternatives to have been proposed):

- We think this problem seems worth solving, and the standard library might be the right place to solve it.
- We think that this probably doesn't belong in the standard library.

Second, if there's a concrete solution:

- We think this specific solution looks roughly right, approved, you or someone else should implement this. (Further review will still happen on the subsequent implementation PR.)
- We're not sure this is the right solution, and the alternatives or other materials don't give us enough information to be sure about that. Here are some questions we have that aren't answered, or rough ideas about alternatives we'd want to see discussed.

**Comment by kennytm** [comment]
> Metric values in OpenMetrics MUST be either floating points or integers. **Note that ingestors of the format MAY only support float64**. 

If your use case is a metric *value* for Prometheus AFAIK it will be consumed as `f64` anyway, so even if you print `.display_seconds()` in the most precise way what is scraped and parsed is still 10000000.000000002.

```go
package main

import (
	"fmt"
	"strconv"
)

func main() {
	fmt.Println(strconv.ParseFloat("10000000.000000001", 64))
	// 1.0000000000000002e+07 <nil>
}
```

and for the "nanosecond timestamp"... [Prometheus only supported millisecond-precision](https://github.com/prometheus/prometheus/blob/eea6ab1cdd24ec69c94ba4b0d165030c89860c8b/model/textparse/openmetricsparse.go#L387) :shrug: 

In any case printing a nanosecond timestamp that is compatible with OpenMetrics should be as simple as (assuming you're OK with the extra trailing zeroes):

```rust
format_args!("{}.{:09}", dur.as_secs(), dur.subsec_nanos())
```

**Comment by m-ou-se** [comment]
We briefly discussed this in the libs-api meeting and are happy to see `display_seconds` as an unstable experimental feature.

Feel free to [open a tracking issue](https://github.com/rust-lang/rust/issues/new?assignees=&labels=C-tracking-issue%2C+T-libs&template=library_tracking_issue.md&title=Tracking+Issue+for+XXX) and open a PR to rust-lang/rust to add it as an unstable feature.

Thanks!
