### ISSUE TITLE
Add `str::reverse` method for in place string reversal

### ISSUE THREAD

**Issue by alexstanovoy** [rust-lang/libs-team#353]
# Proposal

## Problem statement

Currently, to reverse a _UTF-8 string_ you need a to write a freestanding function like `fn reverse(&mut str)` or use `s.chars().rev().collect()`, which requires an allocation.

## Motivating examples or use cases

I haven't remembered a real-world example; it's in my list for a while. Why not though? :)

## Solution sketch

The design should be the same as `[T]::reverse`. First, reverse all bytes, then reverse every char with respect to UTF-8 standard.

## What happens now?

This issue contains an API change proposal (or ACP) and is part of the libs-api team [feature lifecycle]. Once this issue is filed, the libs-api team will review open proposals as capability becomes available. Current response times do not have a clear estimate, but may be up to several months.

[feature lifecycle]: https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html

## Possible responses

The libs team may respond in various different ways. First, the team will consider the *problem* (this doesn't require any concrete solution or alternatives to have been proposed):

- We think this problem seems worth solving, and the standard library might be the right place to solve it.
- We think that this probably doesn't belong in the standard library.

Second, if there's a concrete solution:

- We think this specific solution looks roughly right, approved, you or someone else should implement this. (Further review will still happen on the subsequent implementation PR.)
- We're not sure this is the right solution, and the alternatives or other materials don't give us enough information to be sure about that. Here are some questions we have that aren't answered, or rough ideas about alternatives we'd want to see discussed.

**Comment by BurntSushi** [comment]
> I haven't remembered a real-world example; it's in my list for a while. Why not though? :)

I think we need something more compelling than this for `std`. And I don't see the correctness problems with reversing based on codepoint acknowledged here.

Note that `bstr` has [`reverse_bytes`], [`reverse_chars`] and [`reverse_graphemes`]. Arguably, `reverse_graphemes` is the _most_ correct and the least likely to produce surprising results. But `std` doesn't have grapheme segmentation. 

[`reverse_bytes`]: https://docs.rs/bstr/latest/bstr/trait.ByteSlice.html#method.reverse_bytes
[`reverse_chars`]: https://docs.rs/bstr/latest/bstr/trait.ByteSlice.html#method.reverse_chars
[`reverse_graphemes`]: https://docs.rs/bstr/latest/bstr/trait.ByteSlice.html#method.reverse_graphemes

**Comment by alexstanovoy** [comment]
Yeah, it looks like _usually_, users expect to reverse _graphemes_, not the codepoints. Although it may be useful to have idiomatic alternative to `.chars().rev().collect()` inside the `std`, after your comment I don't think it's really useful. Thanks for your time! :)
