### ISSUE TITLE
mixed_integer_ops extension

### ISSUE THREAD

**Issue by davidzeng0** [rust-lang/libs-team#386]
# Proposal

## Problem statement

Extend the methods added by https://github.com/rust-lang/rust/issues/87840

https://github.com/rust-lang/libs-team/issues/381#issuecomment-2130783890

The following subtraction methods are missing
```rust
impl uX {
    pub const fn checked_sub_signed(self, iX) -> Option<Self>;
    pub const fn overflowing_sub_signed(self, iX) -> (Self, bool);
    pub const fn saturating_sub_signed(self, iX) -> Self;
    pub const fn wrapping_sub_signed(self, iX) -> Self;
}
```

## Motivating examples or use cases

The current best way to replicate `checked_sub_signed` is by
```rust
match signed.checked_neg() {
    Some(neg) => unsigned.checked_add_signed(neg),
    None => unsigned.checked_add(signed as Unsigned)
}
```

## What happens now?

This issue contains an API change proposal (or ACP) and is part of the libs-api team [feature lifecycle]. Once this issue is filed, the libs-api team will review open proposals as capability becomes available. Current response times do not have a clear estimate, but may be up to several months.

[feature lifecycle]: https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html

## Possible responses

The libs team may respond in various different ways. First, the team will consider the *problem* (this doesn't require any concrete solution or alternatives to have been proposed):

- We think this problem seems worth solving, and the standard library might be the right place to solve it.
- We think that this probably doesn't belong in the standard library.

Second, if there's a concrete solution:

- We think this specific solution looks roughly right, approved, you or someone else should implement this. (Further review will still happen on the subsequent implementation PR.)
- We're not sure this is the right solution, and the alternatives or other materials don't give us enough information to be sure about that. Here are some questions we have that aren't answered, or rough ideas about alternatives we'd want to see discussed.

**Comment by joshtriplett** [comment]
We reviewed these in today's @rust-lang/libs-api meeting, and approved them.
