### ISSUE TITLE
Repurpose `str::lines_any` to truly split on *all* newlines

### ISSUE THREAD

**Issue by Jules-Bertholet** [rust-lang/libs-team#390]
# Proposal

## Problem statement

In addition to `'\n'` and `"\r\n"`, Unicode specifies several other sequences that can cause a line break:

- `'\r'` not followed by `'\n'`
- `'\x0B'` (vertical tab)
- `'\x0C'` (form feed)
- `'\u{0085}'` (next line)
- `'\u{2028}'` (line separator)
- `'\u{2029}'` (paragraph separator)

(See [Unicode § 5.8](https://www.unicode.org/versions/Unicode15.0.0/ch05.pdf#G10213) and [UAX 14](https://www.unicode.org/reports/tr14/).) 

However, the standard library provides no APIs for dealing with these.

## Motivating examples or use cases

For security and interoperability, it can sometimes be important for software to support the full range of potential line breaking characters ([UTS 51](https://www.unicode.org/reports/tr55/#Spoofing-LB)). Having an API for this in the standard library makes this more likely to happen.

## Solution sketch

Undeprecate `str::lines_any()`, and modify its behavior to treat any of the above characters and sequences as a line break.

This change in behavior is extremely unlikely to cause any issues, as the function in question has been deprecated since 1.4, and the change in behavior of `lines()` which occurred concurrently with the deprecation caused no problems either.

As a possible future extension, add a `read_line_any()` counterpart to `read_line()` on `std::io::BufRead`.
## Alternatives

This could be added as a completely new API instead of repurposing a pre-existing deprecated function. However, this would require a more awkward naming, and the behavior change is extremely unlikely to be problematic.

This could be a crate on crates.io. However, users are more likely to simply not handle this correctly, rather than add a dependency just for this niche corner case.

## What happens now?

This issue contains an API change proposal (or ACP) and is part of the libs-api team [feature lifecycle]. Once this issue is filed, the libs-api team will review open proposals as capability becomes available. Current response times do not have a clear estimate, but may be up to several months.

[feature lifecycle]: https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html

## Possible responses

The libs team may respond in various different ways. First, the team will consider the *problem* (this doesn't require any concrete solution or alternatives to have been proposed):

- We think this problem seems worth solving, and the standard library might be the right place to solve it.
- We think that this probably doesn't belong in the standard library.

Second, if there's a concrete solution:

- We think this specific solution looks roughly right, approved, you or someone else should implement this. (Further review will still happen on the subsequent implementation PR.)
- We're not sure this is the right solution, and the alternatives or other materials don't give us enough information to be sure about that. Here are some questions we have that aren't answered, or rough ideas about alternatives we'd want to see discussed.

**Comment by BurntSushi** [comment]
I would like to see more concrete use cases motivating this. Otherwise I am quite skeptical of whether its utility is broad enough to warrant a place in std.

**Comment by joshtriplett** [comment]
@BurntSushi :+1:, I'd want to see a use case for this as well.

In any case, I don't think we should repurpose the old deprecated `lines_any` for this. *If* we consider adding this, it should have a name that makes it easy for people to find this if *and only if* it's what they actually need.
