### ISSUE TITLE
Non-blocking check for `LazyLock`s

### ISSUE THREAD

**Issue by workingjubilee** [rust-lang/libs-team#402]
# Proposal

## Problem statement

You currently cannot check if a `LazyLock` or `LazyCell` is initialized (and then read it **if** it is already initialized) in a non-blocking manner. You can deref, or call `force`, but those initialize it. Sometimes you just want to check without doing so, for somewhat esoteric reasons (e.g. async-signal-safe code).

## Motivating examples or use cases

I use `OnceLock` for a `static` variable that gets checked from rustc's signal handler, but really ought to just be a `LazyLock`, because of this. It's not that bad an amount of code grunge, but it's annoying. The static:

https://github.com/rust-lang/rust/blob/5a3e2a4e921097c8f2bf6ea7565f8abe878cdbd4/compiler/rustc_interface/src/util.rs#L51-L82

The place it gets checked in the signal handler:

https://github.com/rust-lang/rust/blob/d8d5732456d375f7c4bdc2f6ad771989a5e0ae02/compiler/rustc_driver_impl/src/signal_handler.rs#L103-L107

## Solution sketch

Add the following function to LazyLock and LazyCell:
```rust
impl<T, F> LazyLock<T, F> {
    /// `Some` if LazyLock completed initialization.
    pub fn as_completed(&self) -> Option<&T> {
        todo!()
    }
}
```

## Alternatives

- I can suck it up, I guess?
- This function is called [`Lazy::get`](https://docs.rs/once_cell/latest/once_cell/sync/struct.Lazy.html#method.get) in OnceCell, but that seems prone to conflicts. Naming things `get` when they have a different semantic purpose than a simple indexing operation (...which would deref, thus initialize...) seems like an antipattern. I don't really like `Pin::get_mut` either. Thus the somewhat unusual name for a somewhat unusual operation which is specifically trying to *avoid* doing something that might prematurely force a deref to the inner type.

## Links and related work

- [Lazy::get](https://docs.rs/once_cell/latest/once_cell/sync/struct.Lazy.html#method.get)
- [Once::is_completed](https://doc.rust-lang.org/std/sync/struct.Once.html#method.is_completed)

<details><summary>

## What happens now?
</summary>

This issue contains an API change proposal (or ACP) and is part of the libs-api team [feature lifecycle]. Once this issue is filed, the libs-api team will review open proposals as capability becomes available. Current response times do not have a clear estimate, but may be up to several months.

[feature lifecycle]: https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html

</details>
<details><summary>

## Possible responses

</summary>

The libs team may respond in various different ways. First, the team will consider the *problem* (this doesn't require any concrete solution or alternatives to have been proposed):

- We think this problem seems worth solving, and the standard library might be the right place to solve it.
- We think that this probably doesn't belong in the standard library.

Second, if there's a concrete solution:

- We think this specific solution looks roughly right, approved, you or someone else should implement this. (Further review will still happen on the subsequent implementation PR.)
- We're not sure this is the right solution, and the alternatives or other materials don't give us enough information to be sure about that. Here are some questions we have that aren't answered, or rough ideas about alternatives we'd want to see discussed.

</details>

**Comment by pitaj** [comment]
Should probably take `this: &Self` instead, like `force`, in order to entirely avoid deref conflicts.  That's how `Lock::get` works.

Some other name options: 
- `try_deref`
- `try_as_ref`
- `try_ref`
- `as_ref`
- `fetch`

**Comment by the8472** [comment]
some prior art: `thread::JoinHandle::is_finished`

**Comment by kennytm** [comment]
If we model after `JoinHandle::is_finished` there would be only an `is_initialized() -> bool` function and then

> *once this returns true, ~~`join`~~ `force` can be expected to return quickly, without blocking for any significant amount of time.*

but IMO doing this in 2 steps does not feel very rusty.

**Comment by pitaj** [comment]
It would be kinda weird if the `OnceCell` API is called `get` but the `LazyCell` API is named something different. 

I don't really see a problem with
```rust
impl<T, F> LazyLock<T, F> {
    fn get(this: Self) -> Option<T>
}
```

**Comment by workingjubilee** [comment]
OnceLock is opaque with respect to its contents. It **is** different.

Further, all of those APIs named `get` that don't take an additional key or index argument of some kind are a mistake.

**Comment by workingjubilee** [comment]
The thing saving `OnceLock` is that in general the use of `get` is incredibly niche (which makes it having such a terse name feel like an incredible misprioritization) so the real function is `get_or_init`.

for all others:

get what, motherfucker?

**get what**?

by not having a second argument and having such a pointlessly vague name, it's totally context free. if you see some `x.get()` that tells you jack shit about what's coming next. "oh people shouldn't write non-descriptive variable names", yeah, well standard libraries shouldn't have non-descriptive function names. If we had a trait named `Get` it wouldn't implement the unary argument form, it would be the two-argument form, because everyone understands `get` is a kind of field accessor which means it should essentially **always** be qualified with the notional field, and no, it's **not** obvious when something has only one internal field because **it's internal**. Even implementing Deref or DerefMut doesn't reveal that, as plenty things that implement those traits have additional data they could be accessing.

The only reason I don't argue that on every single issue is because I have a limited amount of time and energy and I do not believe anyone is interested in fucking hearing my opinions about how you are supposed to do technical or pedagogic writing.

**Comment by kennytm** [comment]
> if you see some `x.get()` that tells you jack shit about what's coming next.

Except that you can't write `x.get()` in this case, it has to be `LazyLock::get(&x)` and that gives you a lot of context.

**Comment by workingjubilee** [comment]
That is true. I am nonetheless irked by `NonZeroU32` and the like.

Anyways.

- OnceLock does not require that, which would make the types further dissimilar.
- I don't regard forfeiting method chaining syntax as a victory, here.

**Comment by kennytm** [comment]
Forfeiting method chaining is caused by `LazyLock` implementing `Deref<Target = T>`, it is irrelevant to what the function should be named. 

Anyway I think it should *not* be called `get`. I expect a zero-argument `get()` to be an *infallible* method returning `T` or its reference/pointer i.e. works like `force`. The method proposed here sounds more like `Mutex::try_lock`, so IMO the name should also be like `try_xxxx` (unfortunately `try_force` is oxymoron).

**Comment by workingjubilee** [comment]
My brief rant about the overloading of `get` aside, I note that one of the few functions with an exactly matching signature to this is [Option::as_deref](https://doc.rust-lang.org/std/option/enum.Option.html#method.as_deref), which seems to recommend `as_deref` or `try_deref`.

**Comment by kennytm** [comment]
That's a false comparison, `Option<T>::as_deref()` can be called `as_xxxx` because the input is also an `Option`, in the same situation as [`Result`](https://doc.rust-lang.org/std/result/enum.Result.html#method.as_deref) and [`Pin`](https://doc.rust-lang.org/std/pin/struct.Pin.html#method.as_deref_mut). You are trying to get an `Option` out of a `LazyLock` here.

**Comment by workingjubilee** [comment]
huh, so a slight difference in type signature can make the use of another function's name inappropriate, even if it has some similarities? interesting how that works!

**Comment by programmerjake** [comment]
I would say `try_deref` is a good name, except that implies that you'd return `None`/`Err` if `deref` would fail/panic instead of the actual operation of returning `None` if the initialization function hasn't ran yet.
maybe `deref_if_initialized`?

**Comment by workingjubilee** [comment]
Whatever.
