### ISSUE TITLE
Add `BufRead::try_read_until`

### ISSUE THREAD

**Issue by tjallingt** [rust-lang/libs-team#409]
# Proposal

## Problem statement

It can be tricky to implement a way to do synchronous non-blocking reads from a buffered data stream which has delimited frames.

A concrete example is communication with a microcontroller over a serial port using https://github.com/serialport/serialport-rs.
One nice way of framing messages over such a data stream is using [COBS](https://en.wikipedia.org/wiki/Consistent_Overhead_Byte_Stuffing) this means that the 0x00 byte can be used to see where message frames start/end.
Rust guides you to use `BufReader` on top of the serial port (which implements the `Read` and `Write` traits) to get access to useful functions like `BufRead::read_until()`. However this is a blocking function which may be undesireable in certain contexts (for example when the goal is just to check if complete messages have been received but to continue other work, or sleep the thread, otherwise).

## Motivating examples or use cases

An example of what one may write currently would be:

```rust
fn write_frame(dev: &mut BufReader<Box<dyn SerialPort>>, data: Vec<u8>) -> Result<(), FrameError> {
    let frame = codec::wrap_frame(data)?;
    dev.get_mut().write_all(&frame)?;
    Ok(())
}

fn read_frame(dev: &mut BufReader<Box<dyn SerialPort>>) -> Result<Vec<u8>, FrameError> {
    let mut buffer = Vec::with_capacity(codec::MAX_ENCODED_FRAME_SIZE);

    dev.read_until(0x00, &mut buffer)
        .map_err(|error| FrameError::IoError(error))
        .and_then(|_| codec::unwrap_frame(buffer))
}

// This is the function of interest, it is currently difficult to discover the "right"
// thing to do here. Rust helpfully offers `read_until` but what if we don't want to block?
fn read_frame_now_or_never(dev: &mut BufReader<Box<dyn SerialPort>>) -> Result<Option<Vec<u8>>, FrameError> {
    dev.fill_buf()?
        .contains(&0x00)
        .then(|| read_frame(dev))
        .transpose()
}

fn handle_frame(frame: Vec<u8>) -> Result<Option<Response>, FrameError> {
    let response: Response = postcard::from_bytes(frame)?;
    // do something with the data
    // return `None` if the data was not an actual "response" but was "unsolicited"
}

// Example using the `read_frame_now_or_never` to optimistically process incomming unsolicited data
fn process_pending_unsolicited(dev: &mut BufReader<Box<dyn SerialPort>>) -> Result<(), FrameError> {
    loop {
        let frame = match read_frame_now_or_never(dev)? {
            Some(frame) => frame,
            None => return Ok(()),
        };

        // We don't expect any `Response`s here since we did not write any requests.
        match handle_frame(frame)? {
            Some(_) => panic!("unexpected response while processing pending unsolicited"),
            None => {}
        }
    }
}

// Example using the `read_frame` (blocking) to wait for a `Response`
fn transmit(dev: &mut BufReader<Box<dyn SerialPort>>, request: &Request) -> Result<Response, FrameError> {
    let data = postcard::to_vec(request)?;

    write_frame(dev, data)?;

    loop {
        let frame = read_frame(dev)?;

        // We handle all unsolicited messages until we encounter a `Response`.
        match handle_frame(frame)? {
            Some(response) => return Ok(response),
            None => {}
        }
    }
}
```

It can be difficult to figure out what to do when `read_until` is not fitting your use case because of its blocking nature.

## Solution sketch

Adding `BufRead::try_read_until` which returns a `None` to indicate that the delimiter was not found would be a nice logical solution and would appear in the documentation close to the `read_until` which users may encounter.

```rust
BufRead::try_read_until(&mut self, byte: u8, buf: &mut Vec<u8>) -> Result<Option<usize>>;
```

## Alternatives

Keep as is and maybe add an example to `fill_buf()` showing how to read until a certain byte if present.

## Links and related work

- https://doc.rust-lang.org/std/io/trait.BufRead.html#method.read_until
- https://doc.rust-lang.org/std/io/trait.BufRead.html#tymethod.fill_buf

## What happens now?

This issue contains an API change proposal (or ACP) and is part of the libs-api team [feature lifecycle]. Once this issue is filed, the libs-api team will review open proposals as capability becomes available. Current response times do not have a clear estimate, but may be up to several months.

[feature lifecycle]: https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html

## Possible responses

The libs team may respond in various different ways. First, the team will consider the *problem* (this doesn't require any concrete solution or alternatives to have been proposed):

- We think this problem seems worth solving, and the standard library might be the right place to solve it.
- We think that this probably doesn't belong in the standard library.

Second, if there's a concrete solution:

- We think this specific solution looks roughly right, approved, you or someone else should implement this. (Further review will still happen on the subsequent implementation PR.)
- We're not sure this is the right solution, and the alternatives or other materials don't give us enough information to be sure about that. Here are some questions we have that aren't answered, or rough ideas about alternatives we'd want to see discussed.

**Comment by m-ou-se** [comment]
> ```rust
> BufRead::try_read_until(&mut self, byte: u8, buf: &mut Vec<u8>) -> Result<Option<usize>>;
> ```

What exactly would that method do? Can you clarify by giving the implementation?

Only `BufRead::fill_buf` and `BufRead::consume` are required, so it'd need to be implementable with only those two methods. (And it wouldn't be, if I understand correctly what you're proposing.)

**Comment by kennytm** [comment]
Your `read_frame_now_or_never` calls `.fill_buf()` which *will block* if the `buf` was empty, is this expected? If you need a function that never blocks you should use [`BufReader::buffer()`](https://doc.rust-lang.org/std/io/struct.BufReader.html#method.buffer).

**Comment by tjallingt** [comment]
Using the term "non-blocking" was a mistake/overstatement. I'm not fully sure but, I believe `fill_buff` will perform a blocking read but not (potentially) block forever unlike `read_until` which may never complete if the delimiter does not appear in the buffer. Additionally `fill_buff` may be interrupted. Unlike `read_until`.

My suggested `try_read_until` would therefore not be non-blocking but it would stop after a single read and therefore be unlikely to block the thread for a significant amount of time. (At least this is my understanding, I may be wrong)

**Comment by kennytm** [comment]
if the buffer `available` does *not* contain `delim`, the buffer will never be consumed (`r.consume(used)` is never called) and `.fill_buf()` will return the same content forever until you force a read through the "blocking" `.read_until()`.

**Comment by tjallingt** [comment]
In the context of the serialport individual reads (messages) are well below the default capacity of the `BufReader`.
The documentation does describe that:

> Returns the contents of the internal buffer, filling it with more data from the inner reader  __*if it isempty*__.

 So maybe I didn't fully grasp what that means but you are saying that if the application read partial data on the first call to `fill_buf` (so no delimiter yet), future calls to `fill_buf` without first calling `consume` will not actually read from the reader?

In that case it seems that using `BufReader` with a `serialport` to get `BufRead::read_until` is probably not a good combination.
However the documentation seems to encourage it for a usecase like this:

> `BufReader<R>` can improve the speed of programs that make small and repeated read calls to the same file or network socket.

Which does apply to a serialport.

I think this is somewhat core to my suggestion: `read_until` is a great tool that users can find quickly when looking to read "frames" from a bytes stream. However when the goal is not to block the thread permanently until the delimiter has been sent but instead to _check_ whether a full frame has already been received (which may involve doing a read to ensure the buffer is filled) there is no clear guidance (at least from the standard library documentation).

Maybe more info on what I'm trying to do makes this clearer:
In my application there is 


I could use `read_until` on a seperate thread but having a utility to check whether a full message has been received can enable using a single thread for both sending and receiving by just having it wake up periodically.

**Comment by tjallingt** [comment]
sorry pressed the wrong key combination and accidentally closed

**Comment by kennytm** [comment]
> So maybe I didn't fully grasp what that means but you are saying that if the application read partial data on the first call to `fill_buf` (so no delimiter yet), future calls to `fill_buf` without first calling `consume` will not actually read from the reader?

it can be easily verified? you must call `.consume()` if you want to populate the buffer with new data.

```rust
use std::io::{BufRead, BufReader, Result};

fn main() -> Result<()> {
    let mut reader = BufReader::with_capacity(4, &[1,2,3,4,5,6,7,8][..]);
    for _ in 0..10 {
        dbg!(reader.fill_buf()?);
    }
    Ok(())
}

// result: prints `[1,2,3,4]` ten times
```

**Comment by tjallingt** [comment]
In your case you reach the capacity of the BufReader so it seems expected that it cannot continue to fill the buffer while its full.

More interestingly this also appears to happen when the capacity is not reached:

```rust
use std::io::{BufRead, BufReader, Result, Cursor};

fn main() -> Result<()> {
    let cursor = Cursor::new(vec![]);
    let mut reader = BufReader::new(cursor);
    for i in 1..=10 {
        reader.get_mut().get_mut().extend([1*i,2*i,3*i,4*i,5*i]);
        dbg!(reader.fill_buf()?);
    }
    Ok(())
}
```
