### ISSUE TITLE
ACP: add bitwise/bytewise methods to NonZero

### ISSUE THREAD

**Issue by pitaj** [rust-lang/libs-team#413]
# Proposal

## Problem statement

There are several integer methods which, when applied to a `NonZero`, could output a `NonZero`. If added to the `NonZero` type, these can make applying those operations to `NonZero` types much easier and remove the need for `unwrap`s.

## Motivating examples or use cases

```rust
let mut x: NonZeroU32;
x = NonZeroU32::new(x.get().reverse_bits()).unwrap();
x = NonZeroU32::new(x.get().to_be());
```

## Solution sketch

```rust
impl<T> NonZero<T> {
    pub fn reverse_bits(self)  -> Self;
    pub fn rotate_left(self) -> Self;
    pub fn rotate_right(self) -> Self;
    pub fn swap_bytes(self) -> Self;
    pub fn to_be(self) -> Self;
    pub fn to_le(self) -> Self;
}
```

## Alternatives

Do nothing, people continue needing to use `new_unchecked` or `unwrap`.

## Links and related work

- #391 
- [`NonZero::count_ones`](https://doc.rust-lang.org/stable/std/num/struct.NonZero.html#method.count_ones-7)

## What happens now?

This issue contains an API change proposal (or ACP) and is part of the libs-api team [feature lifecycle]. Once this issue is filed, the libs-api team will review open proposals as capability becomes available. Current response times do not have a clear estimate, but may be up to several months.

[feature lifecycle]: https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html

## Possible responses

The libs team may respond in various different ways. First, the team will consider the *problem* (this doesn't require any concrete solution or alternatives to have been proposed):

- We think this problem seems worth solving, and the standard library might be the right place to solve it.
- We think that this probably doesn't belong in the standard library.

Second, if there's a concrete solution:

- We think this specific solution looks roughly right, approved, you or someone else should implement this. (Further review will still happen on the subsequent implementation PR.)
- We're not sure this is the right solution, and the alternatives or other materials don't give us enough information to be sure about that. Here are some questions we have that aren't answered, or rough ideas about alternatives we'd want to see discussed.

**Comment by Amanieu** [comment]
We discussed this in the libs-api meeting today and these seem fine to add.

**Comment by programmerjake** [comment]
imo you should add the `from_be`/`from_le` variants too.

**Comment by pitaj** [comment]
@programmerjake those would be equivalent to

```rust
NonZeroU32::new(u32::from_be(x))
```

Aging them wouldn't avoid any `unwrap`s or unsafe.

**Comment by programmerjake** [comment]
> @programmerjake those would be equivalent to
> 
> ```rust
> NonZeroU32::new(u32::from_be(x))
> ```
> 
> Adding them wouldn't avoid any `unwrap`s or unsafe.

no, `from_be` and `to_be` behave identically, so if `to_be` is a good idea, `from_be` should be too. same with `*_le` variants.

**Comment by pitaj** [comment]
Oh never mind I was mistaken. Good point 👍
