### ISSUE TITLE
Implement `IntoRawX`, `FromRawX` and `AsRawX` for `RawHandler` and `RawSocket`

### ISSUE THREAD

**Issue by fredr** [rust-lang/libs-team#421]
# Proposal

## Problem statement

To make the api more consistent between Unix `RawFd` and Windows `RawSocket` and `RawHandler`.

## Motivating examples or use cases

I was recently porting some functionality from unix to windows, where on unix systems I dealt with `RawFd` and on windows I used `RawSocket`.

On unix we had functions like these:
```
fn matches_fd<V: AsRawFd>(&self, fd: V) -> bool {}
```
and for windows I ported them to
```
fn matches_sock<V: AsRawSocket>(&self, sock: V) -> bool {}
```

But since `AsRawSocket` is not implemented for `RawSocket` like `AsRawFd` is for `RawFd` I had to first wrap it in a type that implemented it for the cases where I had a `RawSocket`.

## Solution sketch

Copy the impls `AsRawFd`, `IntoRawFd` and `FromRawFd` that are implemented for `RawFd` (in `std::os:unix::io`), so that they are also implemented for both `RawSocket` and `RawHandler` (in `std::os::windows::io`)

Since the implementation is so simple, I've made an implementation instead of a sketch here: https://github.com/fredr/rust/commit/e1b1f2162430306c55d0881314647353827bcc8a

**Comment by joshtriplett** [comment]
cc @sunfishcode

**Comment by joshtriplett** [comment]
The question for @sunfishcode: Is there any reason we *shouldn't* `impl AsRawSocket for RawSocket` and `impl AsRawHandle for RawHandle`?

**Comment by sunfishcode** [comment]
I don't have an opinion either way, but here is the context I have:

The `RawFd` impls for unix are unfortunate. `RawFd` is just an `i32`, so these impls permit accidental misuse via unrelated `i32` values. And, they don't have any awareness of the single-ownership transfer that `FromRawFd` and `IntoRawFd` are meant to do. These impls are the reason the documentation needs to have the unfortunate [weasel words](https://doc.rust-lang.org/stable/std/os/fd/trait.IntoRawFd.html#tymethod.into_raw_fd) "however, transferring ownership is not strictly required". `RawSocket` is an alias for a `u64` so it would be similar.

**Comment by sunfishcode** [comment]
Also, as a historical note, these `RawFd` impls were added before the I/O safety types were standardized, at a time when it was more common for code to work with `RawFd`s directly because there was no standard owning fd type yet.

**Comment by ChrisDenton** [comment]
If it weren't for the consistency argument I'd not be enthusiastic about it. As it is I'm more of a shrug, but leaning towards "sure"  because consistency is a useful property for std to have.

**Comment by Amanieu** [comment]
We dicussed this in the libs-api meeting today. The `RawFd` implementations are unfortunate and not something that we want to encourage. The example code shown above (`matches_fd`) should really be using the `AsFd` trait which accepts any type that can become a `BorrowedFd`. As such, we are choosing to reject this ACP.
