### ISSUE TITLE
ACP: impl From<&mut {slice}> for Rc<{slice}> and Arc<{slice}>

### ISSUE THREAD

**Issue by eduardosm** [rust-lang/libs-team#424]
# Proposal

## Problem statement

Sometimes, I need to build reference counted slice (e.g., `Rc<str>`, `Rc<[u8]>`, `Rc<Path>`... or their `Arc` counterparts) from a borrowed sliced. If it is an immutable borrow (e.g., `&str`), I can use `From<&str> for Rc<str>`. If it is a mutable borrow (e.g., `&mut str`), there is not a  `From<&mut str> for Rc<str>`.

## Motivating examples or use cases

```rust
let chr: char = ...;
let s: Rc<str> = chr.encode_utf8(&mut [0; 4]).into();
```

Since `char::encode_utf8` returns a `&mut str`, it fails to compile with "the trait bound `Rc<str>: From<&mut str>` is not satisfied"

## Solution sketch

The proposal is to add the following impls:

```rust
impl From<&mut CStr> for Rc<CStr>
impl From<&mut OsStr> for Rc<OsStr>
impl From<&mut Path> for Rc<Path>
impl From<&mut str> for Rc<str>
```

And their `Arc` counterparts.

An easy implementation would consist on coercing the mutable slice to an immutable one and leverage the existing impls, which take immutable slices, to perform the conversion.

## Alternatives

The alternative right now is to manually coerce the `&mut _` to `&_` before creating the `Rc`.

```rust
let chr: char = ...;
let mut buf = [0; 4];
let s: &str = chr.encode_utf8(&mut buf);
let s: Rc<str> = s.into();
```

## Links and related work

https://github.com/rust-lang/rust/issues/128885

## What happens now?

This issue contains an API change proposal (or ACP) and is part of the libs-api team [feature lifecycle]. Once this issue is filed, the libs-api team will review open proposals as capability becomes available. Current response times do not have a clear estimate, but may be up to several months.

[feature lifecycle]: https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html

## Possible responses

The libs team may respond in various different ways. First, the team will consider the *problem* (this doesn't require any concrete solution or alternatives to have been proposed):

- We think this problem seems worth solving, and the standard library might be the right place to solve it.
- We think that this probably doesn't belong in the standard library.

Second, if there's a concrete solution:

- We think this specific solution looks roughly right, approved, you or someone else should implement this. (Further review will still happen on the subsequent implementation PR.)
- We're not sure this is the right solution, and the alternatives or other materials don't give us enough information to be sure about that. Here are some questions we have that aren't answered, or rough ideas about alternatives we'd want to see discussed.

**Comment by pitaj** [comment]
Can't you just reborrow?
```rust
let s: Rc<str> = (&*chr.encode_utf8(&mut [0; 4])).into();
```

**Comment by eduardosm** [comment]
That should work too.

**Comment by Amanieu** [comment]
We discussed this in the libs-api meeting and are happy to add these. This should also include the implementation for `&mut [T]`  which seems to be missing from the ACP.

Considering we've had recent breakage from new trait implementations, the PR for this should probably go through a crater run.
