### ISSUE TITLE
[ACP] Make it no need to customize both `Ord` and `PartialOrd` manually

### ISSUE THREAD

**Issue by Neutron3529** [rust-lang/libs-team#425]
# Proposal

## Problem statement

Currently, it is documented that `Ord` must consist with `PartialOrd`, thus it is not possible to impl `PartialOrd` manually and impl `Ord` by derive.

>It’s easy to accidentally make cmp and partial_cmp disagree by deriving some of the traits and manually implementing others.
>
> Violating these requirements is a logic error.

## Motivating examples or use cases

Use case 1. Writting a `Ord` directly for `BinaryHeap` [as the doc suggests](https://doc.rust-lang.org/std/collections/struct.BinaryHeap.html#min-heap):
> Either [core::cmp::Reverse](https://doc.rust-lang.org/std/cmp/struct.Reverse.html) or a custom [Ord](https://doc.rust-lang.org/std/cmp/trait.Ord.html) implementation can be used to make BinaryHeap a min-heap. This makes heap.pop() return the smallest value instead of the greatest one.

but in fact, if it is `Ord` rather than `PartialOrd` that is customized, BinaryHeap will yield the default order (due to modify Ord while keeping the PartialOrd is a logic error), rather than the customized order.

Use case 2. Lots of derives

Sometimes, when we want to have a struct with beautiful properties, we have to wrote lots of derives:
```rust
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
...
```
Such derive is too long and contains too many verbose informations. We could directly write
```rust
#[derive(Copy, Eq, Ord)]
// or even less (if we allow derive Eq from Ord. Although it is not easy both allow derive Eq from Ord and derive PartialEq from PartialOrd, enable one of them is possible.)
#[derive(Copy, Ord)]
```
and the compiler should recognize it is `Clone, Copy, PartialEq, Eq, PartialOrd, Ord`.

## Solution sketch

The main idea comes from the solution 3 in section Alternatives.

Section 3 suggests adding an `impl<T:Ord> PartialOrd for T`, which blow up nearly all the existing code. To make sure the backward comptability helds, we could mainly allowing the impls suggests in solution 3, but with a newly added switch:
```rust
#![feature(associated_type_defaults)] // without this line we have to modify all the implementations by adding a switch.
// in mod std::marker
pub struct True {_no_constructor:()} // for trait only, should not construct it.
pub struct False {_no_constructor:()} // for trait only, should not construct it.
pub type DeriveDefault = False; // choose False for legacy edition, True for newer edition

trait Sealed{}
#[allow(private_bounds)]
pub trait Bool: Sealed {}
impl Bool for True {}
impl Bool for False {}
impl Sealed for True {}
impl Sealed for False {}
// trait
trait Foo : PartialFoo {
    /// A newly added switch to show which trait it should be derived
    /// switch it to `Self` will enable the blanket impl 
    /// ```
    /// impl<T:Foo<Derive = Self>> PartialFoo for T {}
    /// ```
    /// Since old code has only T:Foo<Derive = PhantomData<Self>>, the derive behavior is disable by default.
    type Derive:Bool = DeriveDefault;

    // methods
    fn foo(&self) {
        println!("f")
    }
    // methods for impl, all those methods should have a default impl, otherwise for those Foo<Derive = PhantomData<Self>>, compiler still requires a impl.
    // this is not a big problem, for things really needs some extra derive that does not have a default impl, we may adding a trait FooExt, adding those trait in FooExt.
    fn impl_partial_foo(&self) where Self : Foo<Derive = True> {
        println!("impl_pf")
    }
}
trait PartialFoo {
    fn partial_foo(&self) {
        println!("pf")
    }
}
impl<T:Foo<Derive=True>> PartialFoo for T{
    fn partial_foo(&self) {
        self.impl_partial_foo()
    }
}

// old impl is Ok
impl Foo for i32 {}
impl PartialFoo for i32 {}

// new derive is Ok
impl Foo for u32 {
    type Derive = True; // PartialFoo is automatically derived.
}
// customize partial_foo in Foo is Ok
impl Foo for () {
    type Derive = True;
    fn impl_partial_foo(&self) {
        println!("customized partial_foo")
    }
}
fn main(){
    1i32.foo();
    1i32.partial_foo();
    1u32.foo();
    1u32.partial_foo();
    ().foo();
    ().partial_foo();
}
```

The remain question is that, the conflict derive problem could not be (even manually) solved:

```rust
trait ord {
    type partial_ord:?Sized = PhantomData<Self>;
    type eq:?Sized = PhantomData<Self>;
}
trait partial_ord {
    type partial_eq:?Sized = PhantomData<Self>;
}
trait eq {
    type partial_eq:?Sized = PhantomData<Self>;
}
trait partial_eq {}
impl<U, T:ord<partial_ord = Self, eq = U>> partial_ord for T {
    // choose Eq -> PartialEq when possible
    // type partial_eq:?Sized = PhantomData<Self>;
}
impl<U, T:ord<partial_ord = U, eq = Self>> eq for T {
    type partial_eq:?Sized = Self; // thus partial_eq is automatically derived by T
}
// impl<T:partial_ord<partial_eq = Self>> partial_eq for T {} // conflict even there is no trait defined with `<Self as Trait>::partial_eq=Self`
impl<T:eq<partial_eq = Self>> partial_eq for T {}
```

## Alternatives

All the solutions in subsections below are Alternatives which I wrote in Aug.12. I have no idea which to choose at that time, since the first method is the simplest one, and the third method seems doing the most right thing but breaks all the existing code by not allowing impl `Ord` and `PartialOrd` at the same time, and for consistance, impl both `Eq` and `PartialEq`, even impl both `Copy` and `Clone` should also be disallowed.

Of course, keep things as-is is also an alternative, but this requires people writting both PartialOrd and Ord.

Another solution is that, make `#[derive]` works with traits

```rust
#[derive(PartialOrd)]
impl Ord for T {
    ... 
}
```

There are 3 solution pathes, I think the third one is the best way since it provides the most beautiful code. The solution 2 could be regarded as solution 3 with alternative names (thus users have to deal with similar names that have not exactly the same meaning), and the solution 1 has the minimal effect of existing code, although it is ugly. All the following 3 ways are changes that makes `Eq/Ord` consist with `PartialEq/PartialOrd`. All the target are makes custom `PartialOrd` consist with automatic generated `Ord`.

### 1. A minor ACP

This should have the minimal impact of all the existing code: makes `cmp` in `Ord` a default impl. In this case, the `#[derive(Ord)]` for `$ty` only generates a line

```rust
trait Ord : PartialOrd {
    // provide cmp rather than need cmp implementation
    fn cmp(&self, other:&Self) -> Ordering {
        assert_unsafe_precondition!(
            check_library_ub,
            "the PartialOrd is not Ord",
            ( res: Ordering = self.partial_cmp(other) ) => res.is_some(),
        );
        if let Some(res) = self.partial_cmp(other) {
            res
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
}
```
This ACP converts the complex derive of `Ord` into this simple line:
```rust
impl Ord for $Ty {} // since cmp is automatically provided.
```

### 2. A normal ACP

This change is that, adding 2 new trait, `TotalOrd` and `TotalEq`, derive `TotalEq/TotalOrd` requires all the field is `Eq/Ord`, and then use `TotalEq/TotalOrd` to impl `Eq/Ord`

```rust
impl<T:TotalEq> PartialEq for T {
    ...
}
impl<T:TotalEq + PartialEq> Eq for T {
    ...
}
impl<T:TotalOrd> PartialOrd for T {
    ...
}
impl<T:TotalOrd + PartialOrd> Ord for T {
    ...
}

/// same to PartialEq, expect it impl Eq automatically
trait TotalEq {
    // requires
    fn eq(&self, other:&Self) -> bool;

    // provides
    fn ne(&self, other:&Self) -> bool { !self.eq(other) }
}
trait TotalOrd : TotalEq {
    // requires
    // since Total order is required, only provide a `lt` method is enough.
    fn lt(&self, other:&Self) -> bool;

    // provides
    fn le(&self, other:&self) -> bool { self.lt(other) || self.eq(other) }
    fn gt(&self, other:&Self) -> bool { other.lt(self) }
    fn ge(&self, other:&Self) -> bool { other.le(self) }
    fn cmp(&self, other:&Self) -> Ordering {
        if self.lt(other) {
            Ordering::Less
        } else if self.gt(other) {
            Ordering::Greater
        } else {
            Ordering::Equal
        }
    }
}
```

With the ensurance of `TotalEq/TotalOrd`, we could just implement one custom compare function, `TotalOrd`, rather than impl `cmp` first and let `partial_cmp` returns `Some(self.cmp(other))`.

### 3. A major ACP, redesign the whole structure

As the method 2 suggests, `TotalEq` is same to `PartialEq + Eq`, and `TotalOrd` is same to `PartialOrd + Ord`, all the 2 methods just doing the same thing that should be done by `Eq/Ord`. This interesting thing suggests a modification is needed here.

Currently, we have trait `PartialX` and `trait X`(`PartialEq/Eq`,`PartialOrd/Ord` and even `Clone/Copy`), struct with `trait X` could always implement `trait PartialX`, in case both `trait X` and `trait PartialX` are implemented, `trait PartialX` must generate the same result as `trait PartialX` implemented by default.

Here, actually, expect `trait X: PartialX`, we have another solution:
```rust
impl<T:X> PartialX for T {...}
```

To be detailed,

```rust
// define X and PartialX in the crate that provide X and PartialX
pub mod traits {
    pub trait Foo : PartialFoo {
        // require method
        fn foo(&self);

        // provide methods
        // it is actually the default impl for `impl<T:X> PartialX for T`,
        // could be overrided by other crates for performance reasons. 
        fn impl_partial_foo(&self){
            print!("partial_");
            self.foo()
        }
    }
    pub trait PartialFoo {
        fn partial_foo(&self);
    }
    impl<T:Foo> PartialFoo for T {
        // For the maximize freedom, this function should no more than just forwarding all the parameters.
        #[inline(always)] // this is ok since we just inline `<Self as Foo>::partial_foo(self)`
        fn partial_foo(&self) {
            self.impl_partial_foo()
        }
    }
}

// Other crate could implement at most one of `X` and `PartialX` 
pub mod item {
    pub struct Bar;
    impl crate::Foo for Bar {
        fn foo(&self){println!("bar")}
    }
//    // cannot compile with defining both `Foo` and `PartialFoo` into a same struct.
//    impl crate::PartialFoo for Bar {
//        fn foo(&self){println!("partial_bar")}
//    }
    pub struct Baz;
    impl crate::PartialFoo for Baz {
        fn partial_foo(&self){println!("partial_baz")}
    }
}
use traits::*;
use item::*;
fn main(){
    Bar.foo();
    Bar.partial_foo();
    // Baz.foo(); // cannot compile
    Baz.partial_foo();
}
```

With this redesign, `PartialX` is always restricted by `X`( You cannot define a different `PartialX` with `X` defined ), and thus no need to write document everywhere to emphaseize *X must be restricted by the following rules*.

In case extra safety should be guarateened, we could delete the `impl_partial_x` function, move its code into `impl<T:X> PartialX for T {/*here*/}`.

The shortcoming is signaficant: it impacts almost all the rust crate.

For crate with `#[derive(Clone, Copy)]`, since `Clone` should be restricted by `Copy`, in the new design, there exists some code like
```rust
impl <T:Copy> Clone for T {...}
```
And thus the derive will directly generates a conflict. This might be a better choice since in case we say something is `Copy`, it should be inferred as `Clone` automatically.

In this redesign, the trait looks as follows:

```rust
impl<T:Copy> Clone for T {}
impl<T:Eq> PartialEq for T {}
impl<T:Ord> PartialOrd for T {}
// in case we regard `Eq` as `PartialX` and `Ord` as `X`:
// This might be very inefficient, thus provide a `impl_eq` function in trait `Ord` might be a good choice.
impl<T:Ord> Eq for T {}

// what if `impl<T:Eq + DeriveHash> for Hash`? If we allow `impl Eq for Ord`, the chain could be
// Ord -> Eq -> Hash, thus we have to provide a default implementation somewhere
// maybe stop our step before `impl<T:Ord> Eq for T {}` is enough.

// Taking one step further, consider the relationship between Eq -> PartialEq and PartialOrd -> PartialEq
// if T:Ord, these two method should have the same effect, thus both is acceptable
// if T:!Ord + Eq, we have a strange struct that is Eq, PartialEq, PartialOrd but not Ord. In this conflict case, use `impl<T:Eq> PartialEq for T {}` is enough.
// in case the struct is only `PartialEq + PartialOrd`, we may use the default impl (which has not yet usable)
default impl<T:PartialOrd> PartialEq for T {}
// Since there is no direct relation that could converts a `PartialOrd` relationship into the correct `PartialEq` relationship (unless we specific a `fn eq(self,b:&self)->bool{...}` in `PartialOrd` directly), there is no need to adding such default impl.
```

For backward compatiability, adding several marker gate might be a choice:
```rust
impl<T:Copy + DerivedCopy> Clone for T {}
impl<T:Eq + DerivedEq> PartialEq for T {}
impl<T:Ord + DerivedOrd> PartialOrd for T {}
// since things like `DerivedOrd` is newly introduced, all the old code are not affected.
// thus the only affected thing is #[derive], which could be handled by ignore duplicated derive(e.g., ignore Clone when Copy is derived)
```

This major ACP will change the normal derive, `#[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]` into `#[derive(Copy, Eq, Ord)]` or even `#[derive(Copy, Ord)]`, make the code more clear.

## Links and related work

https://internals.rust-lang.org/t/discussion-better-derive-for-trait-eq/21356

## What happens now?

This issue contains an API change proposal (or ACP) and is part of the libs-api team [feature lifecycle]. Once this issue is filed, the libs-api team will review open proposals as capability becomes available. Current response times do not have a clear estimate, but may be up to several months.

[feature lifecycle]: https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html

## Possible responses

The libs team may respond in various different ways. First, the team will consider the *problem* (this doesn't require any concrete solution or alternatives to have been proposed):

- We think this problem seems worth solving, and the standard library might be the right place to solve it.
- We think that this probably doesn't belong in the standard library.

Second, if there's a concrete solution:

- We think this specific solution looks roughly right, approved, you or someone else should implement this. (Further review will still happen on the subsequent implementation PR.)
- We're not sure this is the right solution, and the alternatives or other materials don't give us enough information to be sure about that. Here are some questions we have that aren't answered, or rough ideas about alternatives we'd want to see discussed.

```[tasklist]
### Tasks
```

**Comment by Neutron3529** [comment]
I'm afraid the simple impl hits the performance issues: A simple example is done [in playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=b470c2d5f9ab34e0101a141ae01951d1), to show the benefits that how much manually impl the provided things in `PartialEq` are.

If there is only one thing that should be implemented, I'd rather prefer impl `PartialEq` with performance taking into concern. And this is why in solution 3, I added a `impl_partial_foo` for `trait Foo`.

---

As for having `impl<T: Eq> PartialEq for T` from the beginning, I'm afraid that's not an option. Since `impl<T: Eq>` have no associate functions, it is something no more than a marker. And such impl break all the existing code that impl PartialEq + Eq (mostly of them comes from derive macro). I'm afraid there is no chance to make `impl<T: Eq> PartialEq for T` alone. The `DerivedCopy` solution is that, we might keep the forward comptability and the new fancy grammar (`derive(Ord)` automatically derive its dependencies, `impl Eq/Ord` automatically obtain a customized `PartialEq/PartialOrd`, ...) 

If once we could solve the problem of conflict implementation, I cannot image why there is only `impl <T:Eq> PartialEq for T` is implemented (Since Copy means bitwise clone, starts with `impl<T:Copy> Clone for T` might be better.)

**Comment by RustyYato** [comment]
Your benchmark doesn't measure what you think it does. Just commenting out the custom lt and gt implementations brings all 4 times within a magin of error within each other. And more consistent than before with the custom lt/gt:

https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=49a84e8f00c19696469b898eaa060543

Before commenting out lt/gt: 3 runs

test 396.115475ms
test 318.22715ms
test 317.349749ms
test 216.701189ms 

test 281.852392ms
test 216.02779ms
test 283.781308ms
test 365.020678ms

test 167.482658ms
test 129.905642ms
test 159.006996ms
test 134.91777ms

After commenting out custom lt/gt: (3 runs)
test 144.908223ms 
test 143.55054ms
test 145.348433ms
test 142.903686ms

test 236.72765ms
test 220.378739ms
test 219.585061ms
test 259.36463ms

test 267.865591ms
test 216.900355ms
test 197.106734ms
test 145.252146ms

**Comment by Neutron3529** [comment]
> Your benchmark doesn't measure what you think it does.

It might be better test it in your local machine. Since the payload of playground might change during our benchmark.

In the following result calcuted in my laptop, you could easily figure out the difference.
```
[neutron@3060 me]$ rc test2.rs
rustc --edition 2021 test2.rs -C opt-level=3 -C target-cpu=native -C codegen-units=1 -C lto -o test2 && ./test2
test 161.148538ms
test 161.110687ms
test 159.678529ms
test 160.192403ms
[neutron@3060 me]$ ./test2 
test 160.328096ms
test 160.113614ms
test 159.614024ms
test 160.138856ms
[neutron@3060 me]$ ./test2 
test 165.901387ms
test 160.176961ms
test 159.611669ms
test 159.949666ms
[neutron@3060 me]$ ./test2 
test 165.064068ms
test 160.050448ms
test 159.623039ms
test 159.940492ms
[neutron@3060 me]$ vi test2.rs
[neutron@3060 me]$ rc test2.rs
rustc --edition 2021 test2.rs -C opt-level=3 -C target-cpu=native -C codegen-units=1 -C lto -o test2 && ./test2
test 160.161471ms
test 118.264877ms
test 159.699017ms
test 117.840661ms
[neutron@3060 me]$ ./test2
test 161.373953ms
test 116.878647ms
test 159.884586ms
test 118.417895ms
[neutron@3060 me]$ ./test2
test 161.340919ms
test 116.695045ms
test 159.621773ms
test 116.25352ms
```

What's more, a better solution 3 has been developed, which solve the compatitability issues. I'm writting its details.

**Comment by kennytm** [comment]
or maybe like `#[derive(Ord + super, Copy + super)]` :upside_down_face:

**Comment by Neutron3529** [comment]
> and we felt that they would either have issues with backwards compatibility or would otherwise be too invasive of a change.

The backwards compatibility issue could be solved by the blanket impl:
```rust
pub type True = ...;
pub type False = ...;
// for old edition
#[I don't know which flag could be added]
pub type DefaultPartialOrd = False ;
// for new edition
#[I don't know which flag could be added]
pub type DefaultPartialOrd = True ;

pub trait Ord : PartialOrd {
    type ImplPartialOrd = DefaultPartialOrd; // thus it is false for old editions, true for new editions.
...
}
impl<T:Ord<ImplPartialOrd = True>> PartialOrd for T {
    fn partial_cmp(&self, other:Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}
```

Is it being discussed?

**Comment by kennytm** [comment]
you can't use `&dyn Ord` with that change.
