### ISSUE TITLE
Introduce an async util `WaitGroup`

### ISSUE THREAD

**Issue by tisonkun** [rust-lang/libs-team#427]
# Proposal

## Problem statement

crossbeam provides a [WaitGroup](https://docs.rs/crossbeam/latest/crossbeam/sync/struct.WaitGroup.html) that is good for synchronizing a fork-join task.

However, it's a sync version, meaning that it's not suitable to use in `async`/`await` context.

I made a tidy and solid async `WaitGroup` implementation and wonder if it's suitable to contribute to the std lib (e.g., `std::sync`) or [`futures-util`](https://crates.io/crates/futures-util) or anywhere that is (de-facto) standard so that the ecosystem can collaborate together instead of make one own each time.

## Motivating examples or use cases

My motivating scenario is during the server starting, wait for all its components ready. For example,

```rust
let wg = WaitGroup::new();
let wg_clone = wg.clone();

// may repeat for different components
runtime.spawn(async move {
  // ... initializing ...
  drop(wg_clone);
  // accepting connections
});

wg.await;
```

## Solution sketch

The implementation is tidy, and can be even inlined here:

```rust
#[derive(Clone)]
pub struct WaitGroup {
    inner: Arc<Inner>,
}

pub struct WaitGroupFuture {
    inner: Weak<Inner>,
}

impl WaitGroupFuture {
    /// Gets the number of active workers.
    pub fn workers(&self) -> usize {
        Weak::strong_count(&self.inner)
    }
}

struct Inner {
    waker: AtomicWaker,
}

impl Drop for Inner {
    fn drop(&mut self) {
        self.waker.wake();
    }
}

impl WaitGroup {
    pub fn new() -> Self {
        Self {
            inner: Arc::new(Inner {
                waker: AtomicWaker::new(),
            }),
        }
    }

    /// Gets the number of active workers.
    pub fn workers(&self) -> usize {
        Arc::strong_count(&self.inner) - 1
    }
}

impl Default for WaitGroup {
    fn default() -> Self {
        Self::new()
    }
}

impl IntoFuture for WaitGroup {
    type Output = ();

    type IntoFuture = WaitGroupFuture;

    fn into_future(self) -> Self::IntoFuture {
        WaitGroupFuture {
            inner: Arc::downgrade(&self.inner),
        }
    }
}

impl Future for WaitGroupFuture {
    type Output = ();

    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        match self.inner.upgrade() {
            Some(inner) => {
                inner.waker.register(cx.waker());
                Poll::Pending
            }
            None => Poll::Ready(()),
        }
    }
}

#[cfg(test)]
mod test {
    use pollster::FutureExt;

    use super::*;
    use crate::test_runtime;

    #[test]
    fn test_wait_group_match() {
        let wg = WaitGroup::new();

        for _ in 0..100 {
            let w = wg.clone();
            let _drop = test_runtime().spawn(async move {
                drop(w);
            });
        }

        wg.into_future().block_on();
    }

    #[test]
    fn test_wait_group_timeout() {
        let wg = WaitGroup::new();
        let _wg_clone = wg.clone();
        test_runtime().block_on(async move {
            tokio::select! {
                _ = wg => panic!("wait group should timeout"),
                _ = tokio::time::sleep(tokio::time::Duration::from_secs(1)) => {}
            }
        });
    }
}

```

## Alternatives

The main argument is whether it should be in the std lib, or anywhere suitable for the most Rust developers to collaborate on.

## Links and related work

This is somehow derivative from [waitgroup-rs](https://github.com/laizy/waitgroup-rs).

## What happens now?

This issue contains an API change proposal (or ACP) and is part of the libs-api team [feature lifecycle]. Once this issue is filed, the libs-api team will review open proposals as capability becomes available. Current response times do not have a clear estimate, but may be up to several months.

[feature lifecycle]: https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html

## Possible responses

The libs team may respond in various different ways. First, the team will consider the *problem* (this doesn't require any concrete solution or alternatives to have been proposed):

- We think this problem seems worth solving, and the standard library might be the right place to solve it.
- We think that this probably doesn't belong in the standard library.

Second, if there's a concrete solution:

- We think this specific solution looks roughly right, approved, you or someone else should implement this. (Further review will still happen on the subsequent implementation PR.)
- We're not sure this is the right solution, and the alternatives or other materials don't give us enough information to be sure about that. Here are some questions we have that aren't answered, or rough ideas about alternatives we'd want to see discussed.

**Comment by tisonkun** [comment]
I just notice that `AtomicWaker` is part of `futures`. So possible `furtures-util` is more proper.

Does the process then still go through libs-team, or I should file an issue at https://github.com/rust-lang/futures-rs?

cc @@taiki-e

**Comment by Amanieu** [comment]
The ACP process is only for API changes to the standard library. For changes to futures-rs you should open an issue on that repo.

**Comment by tisonkun** [comment]
@Amanieu Yeah. I'm yet to be sure with where to go, and considering push to `std::sync` or other mod a possible option.

**Comment by Amanieu** [comment]
We'd prefer if this was trialed in the ecosystem under future-rs before being added to the standard library.
