### ISSUE TITLE
Add inner methods to some iterators

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/libs-team#430]
# Proposal

Add inner methods to some iterators
## Problem statement

When you create an adapter such as `peekable`, it will remain a peekable and there is no way to recover the wrapped iterator.
## Motivating examples or use cases

This could be useful for lexers for example, but the main reason is that I don't see a clear reason to make it impossible to retrieve the wrapped iterator
```rs
"my str".chars()
  .peekable();
// At this point you lose the ability to call `as_str`
 ```
Of course you could just clone the iterator beforehand but this limits the flexibility of the API unnecessarily.
## Solution sketch

https://github.com/rust-lang/rust/pull/127061

This has the caveat that users now need to know that if you peek you advance the iterator, but if we expose the inner iterator and the saved peeked state users can just recreate the full previous state.

**Comment by the8472** [comment]
Previous proposal: #128

**Comment by the8472** [comment]
As per the previous [ACP resolution](https://github.com/rust-lang/libs-team/issues/128#issuecomment-1637550127), we generally recommend using [by_ref()](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.by_ref) for this pattern.

Do you have a strong use-case that cannot be covered via `by_ref`? If so please add that to the motivation section of your ACP.

**Comment by dev-ardi** [comment]
I guess that it can be covered by that in a better way, yes. I was not aware of the previous ACP.
