### ISSUE TITLE
Adding position to Enumerate

### ISSUE THREAD

**Issue by x4exr** [rust-lang/libs-team#435]
# Proposal
Adding position function to Enumerate struct.

## Problem statement
Other than doing next() which will progress the position, there is no straight forward way to get the position. If you call something that uses your iterator, you cant know how far it progressed without knowing the position start and end.

## Solution sketch
```rs

    #[inline]
    pub fn position(&self) -> usize {
        self.count
    }
```

## Alternatives
Putting Peek around Enumerate, then doing .peek() and subtracting 1 from the position. The issue with this is if you are at the end of the iteration, you get None and need to store the end position else where. This also uses peek in a way that is unnatural and unneccesary. Its over complicated

## Links and related work
 - https://github.com/rust-lang/rust/pull/129784 Is a pull request I opened for this

## What happens now?

This issue contains an API change proposal (or ACP) and is part of the libs-api team [feature lifecycle]. Once this issue is filed, the libs-api team will review open proposals as capability becomes available. Current response times do not have a clear estimate, but may be up to several months.

[feature lifecycle]: https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html

## Possible responses

The libs team may respond in various different ways. First, the team will consider the *problem* (this doesn't require any concrete solution or alternatives to have been proposed):

- We think this problem seems worth solving, and the standard library might be the right place to solve it.
- We think that this probably doesn't belong in the standard library.

Second, if there's a concrete solution:

- We think this specific solution looks roughly right, approved, you or someone else should implement this. (Further review will still happen on the subsequent implementation PR.)
- We're not sure this is the right solution, and the alternatives or other materials don't give us enough information to be sure about that. Here are some questions we have that aren't answered, or rough ideas about alternatives we'd want to see discussed.

**Comment by pitaj** [comment]
The name conflicts with [`Iterator::position`](https://doc.rust-lang.org/stable/std/iter/trait.Iterator.html#method.position). [`count`](https://doc.rust-lang.org/stable/std/iter/trait.Iterator.html#method.count) also won't work.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=dfb1461dad8991aeeb1fb10b8187cc42

**Comment by x4exr** [comment]
So could offset also get added to enumerated then

**Comment by workingjubilee** [comment]
> Putting Peek around Enumerate, then doing `.peek()` and subtracting 1 from the position. The issue with this is if you are at the end of the iteration, you get None and need to store the end position else where. This also uses peek in a way that is unnatural and unneccesary. Its over complicated

You would have to subtract 1 anyways, because the initial position will actually be an item you haven't iterated to yet.

**Comment by workingjubilee** [comment]
Do you have a practical use-case in mind? It's not entirely clear if you want what you say you want, because of the whole "the actual first position will be 0, even before you call `.next()`" problem.

**Comment by x4exr** [comment]
Yes I need this method to measure the number of iterations made when I call a function such as parse string with Mt iterator inside

**Comment by workingjubilee** [comment]
Ah, so you're going to call... hm, it can't be `position`, and it can't be `count`, so let's say `iter.current_count()`, and then you're going to call it again later, and subtract the two? So kind of like this?
```rust
let start = iter.current_count();
my_parser_that_accepts_iterators(iter);
let end = iter.current_count();
let iterations = end - start;
```

**Comment by x4exr** [comment]
Yes, I was even thinking `enumerated_position`

**Comment by pitaj** [comment]
Another option that avoids the conflicts entirely, meaning you can use any name you want: 

```rust
    #[inline]
    pub fn count(this: &Self) -> usize {
        self.count
    }
```

**Comment by x4exr** [comment]
why call it `this`? is it so rust does not accept this as a method? Also `.count()` already is a function in Iterator

**Comment by pitaj** [comment]
Yes, it doesn't become a method, so there's no name conflict. It's called like `Enumerate::count(&instance)`

**Comment by kennytm** [comment]
While `next_index()` is very clear on its own,  together with other existing iterator functions like `next()` / `next_back()` / `next_chunk()` / `next_if()` it sounds like calling it will mutate the iterator.

**Comment by pitaj** [comment]
What about `peek_index`?

**Comment by x4exr** [comment]
What does it have to do with peek?

**Comment by cuviper** [comment]
It's a preview of what `next()` would return, similar to `Peekable::peek()`.

**Comment by Amanieu** [comment]
> While `next_index()` is very clear on its own, together with other existing iterator functions like `next()` / `next_back()` / `next_chunk()` / `next_if()` it sounds like calling it will mutate the iterator.

We did discuss this issue in the meeting but we felt like this was unlikely to be an issue in practice. While it follows the same pattern as the `next_*` methods, it's unlikely that this would be confused with advancing the iterator. The documentation would make that clear, especially with the method taking `&self`.

**Comment by workingjubilee** [comment]
We'll have plenty of time to argue over what Pantone chips to use, let's just get it on nightly.
