### ISSUE TITLE
`core::arch::breakpoint`

### ISSUE THREAD

**Issue by workingjubilee** [rust-lang/libs-team#436]
# Proposal

It does a breakpoint. Like `unsafe { asm!("int 3") }` except safe and cross-platform.

## Problem statement

Debugging is hard.
Breakpoints are useful.
`unsafe { asm!("int 3") }` is platform-specific.

## Motivating examples or use cases

...`gdb`?

## Solution sketch

Add `fn breakpoint`.

## Alternatives

Don't?

Make it only available on platforms guaranteed to support it?

It could go in `core::hint::breakpoint` and have the semantic that it is optional if the target doesn't support breakpoints, I guess? Though that's a hint that can abort the process, so maybe that's a bit weird?

## Links and related work

- [std::breakpoint](https://en.cppreference.com/w/cpp/utility/breakpoint)

**Comment by workingjubilee** [comment]
context: we have this intrinsic: https://doc.rust-lang.org/std/intrinsics/fn.breakpoint.html

**Comment by pitaj** [comment]
What about `core::hint::breakpont`?

**Comment by Amanieu** [comment]
We discussed this in the libs-api meeting. Breakpoints are very architecture and OS-specific and it's not obvious that this functionality can be provided by a single instruction in a core-only API. However it might be interesting to offer a more complete debugger API in `std` on a best-effort basis, following the C++ [`<debugging>](https://en.cppreference.com/w/cpp/header/debugging) API.
