### ISSUE TITLE
Path::force_relative

### ISSUE THREAD

**Issue by lolbinarycat** [rust-lang/libs-team#437]
# Proposal

## Problem statement

It is frequently desirable to prevent creation of files outside a given directory.

## Motivating examples or use cases

archive extractor programs (eg. `tar`, `unzip`) usually do not allow extracting to an absolute path, instead removing the leading `/`.

## Solution sketch

```rust
impl Path {
    /// remove any leading `/`, then remove any leading `..` sections
    fn force_relative(&self) -> PathBuf;
}
```

## Alternatives

* proper sandboxing virtual filesystems, similar to go `fs.FS`.  both this and the current proposal would need additonal help to prevent symlink escapes.
* convert to string and do manual manipulations (unlikely to function properly on Windows)
* have the function return `&Path`.  saves an allocation and works for the basic case where it only needs to trim charachters from the start
* have the function return `Cow`, saving an allocation in the trimming and passthrough cases, but slightly increasing complexity
* delegate this to an external crate (unergonomic, requires an extension trait or function call syntax, rust already has too many trivial single-function crates, may become unmaintained, has security implications...)

## Links and related work

[golang `fs.FS`](https://pkg.go.dev/io/fs#FS)
[tar(1)](https://www.man7.org/linux/man-pages/man1/tar.1.html), see the `--absolute-names` option.
## What happens now?

This issue contains an API change proposal (or ACP) and is part of the libs-api team [feature lifecycle]. Once this issue is filed, the libs-api team will review open proposals as capability becomes available. Current response times do not have a clear estimate, but may be up to several months.

[feature lifecycle]: https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html

## Possible responses

The libs team may respond in various different ways. First, the team will consider the *problem* (this doesn't require any concrete solution or alternatives to have been proposed):

- We think this problem seems worth solving, and the standard library might be the right place to solve it.
- We think that this probably doesn't belong in the standard library.

Second, if there's a concrete solution:

- We think this specific solution looks roughly right, approved, you or someone else should implement this. (Further review will still happen on the subsequent implementation PR.)
- We're not sure this is the right solution, and the alternatives or other materials don't give us enough information to be sure about that. Here are some questions we have that aren't answered, or rough ideas about alternatives we'd want to see discussed.

**Comment by kennytm** [comment]
> have the function return `&Path`. saves an allocation and works for the basic case where it only needs to trim charachters from the start

in what cases this function will *not* be just trimming characters from the start?

> `remove any leading `/`, then remove any leading `..` sections`

1. what about Windows path with leading `C:\` or `\\?\UNC\server\share\` 
2. what about `..` in the middle of the path e.g. `/tmp/a/b/c/d/../e/f/g` or `/tmp/a/../../../../b/c/../../../d`

**Comment by lolbinarycat** [comment]
> in what cases this function will not be just trimming characters from the start?

it may be desirable to normalize away `..` components to make handling easier.  also i'm not at all familiar with the edge cases of windows paths

> what about Windows path with leading C:\ or \\?\UNC\server\share\

yes, that will also be turned into a relative path.

**Comment by kennytm** [comment]
i mean could you fill in the expected results for 

```rust
// this is according to doc
assert_eq!(Path::new(r"../../../../etc/passwd").force_relative(), Path::new("etc/passwd"));

#[cfg(windows)] {
    assert_eq!(Path::new(r"C:\PROGRA~1\Rust\rustc.exe").force_relative(), Path::new("???"));
    assert_eq!(Path::new(r"\\server\share\a.txt").force_relative(), Path::new("???"));
}
#[cfg(unix)] {
    // this is according to doc
    assert_eq!(Path::new(r"/tmp/swap.txt").force_relative(), Path::new("tmp/swap.txt"));

    assert_eq!(Path::new(r"a/b/../c/d").force_relative(), Path::new("???"));
    assert_eq!(Path::new(r"/a/b/../b/c/d").force_relative(), Path::new("???"));
    assert_eq!(Path::new(r"a/../b/c/d").force_relative(), Path::new("???"));
    assert_eq!(Path::new(r"/a/../b/c/d").force_relative(), Path::new("???"));
    assert_eq!(Path::new(r"a/../../c/d").force_relative(), Path::new("???"));
    assert_eq!(Path::new(r"/a/../../c/d").force_relative(), Path::new("???"));
}
```

**Comment by kennytm** [comment]
> it may be desirable to normalize away `..` components to make handling easier.

this should be handled separately by `.normalize_lexically()` #396.

**Comment by the8472** [comment]
> It is frequently desirable to prevent creation of files outside a given directory.

[openat2](https://man7.org/linux/man-pages/man2/openat2.2.html) calls this `RESOLVE_BENEATH`

And due to symlinks it's outright impossible to do this properly without talking to the filesystem.

Prior art: [pathrs](https://docs.rs/pathrs/latest/pathrs/)

**Comment by lolbinarycat** [comment]
> And due to symlinks it's outright impossible to do this properly without talking to the filesystem.

what if the directory you want to isolate to is known to not contain symlinks?
