### ISSUE TITLE
add `impl From<Box<str>> for Box<Path>` and friends

### ISSUE THREAD

**Issue by its-the-shrimp** [rust-lang/libs-team#439]
# Proposal

Add impls for converting a container of `str` to a container of `Path` or `OsStr`

## Problem statement

Converting between allocated containers of different unsized types reauires either unsafe code, (e.g. `transmute`) or reallocation, even though converting between these same unsized types is trivial if they're in their owned form, e.g. it's easy to convert `String` to a `PathBuf`, but a `Box<str>` to `Box<Path>` - not so much, same goes for the conversion from `Rc<str>` to `Rc<Path>`, and for equivalent conversions but to an `OsStr`

## Solution sketch

```rs
impl From<Box<str>> for Box<Path> { ... }
impl From<Box<str>> for Box<OsStr> { ... }
impl From<Box<Path>> for Box<OsStr> { ... }
impl From<Box<OsStr>> for Box<Path> { ... }
impl From<Rc<str>> for Rc<Path> { ... }
impl From<Rc<str>> for Rc<OsStr> { ... }
impl From<Rc<Path>> for Rc<OsStr> { ... }
impl From<Rc<OsStr>> for Rc<Path> { ... }
impl From<Arc<str>> for Arc<Path> { ... }
impl From<Arc<str>> for Arc<OsStr> { ... }
impl From<Arc<Path>> for Arc<OsStr> { ... }
impl From<Arc<OsStr>> for Arc<Path> { ... }
```

## Alternatives

As mentioned previously, either unsafe code or reallocation, neither of which are desirable

## What happens now?

This issue contains an API change proposal (or ACP) and is part of the libs-api team [feature lifecycle]. Once this issue is filed, the libs-api team will review open proposals as capability becomes available. Current response times do not have a clear estimate, but may be up to several months.

[feature lifecycle]: https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html

## Possible responses

The libs team may respond in various different ways. First, the team will consider the *problem* (this doesn't require any concrete solution or alternatives to have been proposed):

- We think this problem seems worth solving, and the standard library might be the right place to solve it.
- We think that this probably doesn't belong in the standard library.

Second, if there's a concrete solution:

- We think this specific solution looks roughly right, approved, you or someone else should implement this. (Further review will still happen on the subsequent implementation PR.)
- We're not sure this is the right solution, and the alternatives or other materials don't give us enough information to be sure about that. Here are some questions we have that aren't answered, or rough ideas about alternatives we'd want to see discussed.

**Comment by m-ou-se** [comment]
We discussed this in the libs-api meeting. This looks good. Feel free to send a PR to add these implementations (which will need an FCP for merging, as it'd be insta-stable).

**Comment by pitaj** [comment]
This overlaps substantially with https://github.com/rust-lang/libs-team/issues/399

They've already begun work on this, and have run into coherence issues.
