### ISSUE TITLE
Add `LowerExp` and `UpperExp` implementations to `NonZero`

### ISSUE THREAD

**Issue by rick-de-water** [rust-lang/libs-team#458]
# Proposal

## Problem statement

`LowerExp` and `UpperExp` format traits implementations are missing from the `NonZero` integer types. All other (`Binary`, `*Hex`, `Octal`, etc) have been implemented, so it looks like an oversight, especially since the integer primitives themselves do implement `LowerExp` and `UpperExp`.

## Motivating examples or use cases

`UpperExp` example changed to use `NonZeroU32`
```rust
fn main() {
    let x = core::num::NonZeroU32::new(42).unwrap(); // 42 is '4.2E1' in scientific notation
    
    assert_eq!(format!("{x:E}"), "4.2E1");
}
```

## Solution sketch

Implement `LowerExp` and `UpperExp`. It probably only involves adding `impl_nonzero_fmt!(LowerExp)` and `impl_nonzero_fmt!(UpperExp)` to the [list of format impls](https://doc.rust-lang.org/1.81.0/src/core/num/nonzero.rs.html#132)

## Alternatives
Use `.get()` like a pleb, which then needs to be passed as an argument since you cannot call functions from `format!` and friends.

## Links and related work
N/A

## What happens now?

This issue contains an API change proposal (or ACP) and is part of the libs-api team [feature lifecycle]. Once this issue is filed, the libs-api team will review open proposals as capability becomes available. Current response times do not have a clear estimate, but may be up to several months.

[feature lifecycle]: https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html

## Possible responses

The libs team may respond in various different ways. First, the team will consider the *problem* (this doesn't require any concrete solution or alternatives to have been proposed):

- We think this problem seems worth solving, and the standard library might be the right place to solve it.
- We think that this probably doesn't belong in the standard library.

Second, if there's a concrete solution:

- We think this specific solution looks roughly right, approved, you or someone else should implement this. (Further review will still happen on the subsequent implementation PR.)
- We're not sure this is the right solution, and the alternatives or other materials don't give us enough information to be sure about that. Here are some questions we have that aren't answered, or rough ideas about alternatives we'd want to see discussed.

**Comment by dtolnay** [comment]
Please send a PR. I agree this looks like an oversight from https://github.com/rust-lang/rust/pull/48265.
