### ISSUE TITLE
Implement io::Write on ManuallyDrop<T: io::Write>

### ISSUE THREAD

**Issue by SUPERCILEX** [rust-lang/libs-team#470]
# Proposal

## Problem statement

Currently, you can't write through a `ManuallyDrop<File>` unless you deref it which means you can't have a `BufWriter<ManuallyDrop<File>>>` and instead need to use a `BufWriter<&File>` which is hard to pass around.

## Motivating examples or use cases

```rust
    let stdout = ManuallyDrop::new(unsafe { File::from_raw_fd(raw_stdout()) });
    let mut stdout = BufWriter::new(&*stdout); // BufWriter::new(stdout) doesn't work
```

## Solution sketch

We could implement `impl<T: io::Write> io::Write for ManuallyDrop<T>` but I don't like this solution as obviously why not implement any number of other traits. Ideally there's some way to say "implement every trait available on an `&{,mut} T` for a `ManuallyDrop<T>`".

## Alternatives

Let folks write their own wrapper structs which implement the traits they need.

## Links and related work

I'm sure this must have come up before, but I couldn't find discussion online, hence making an issue here.

**Comment by the8472** [comment]
I think this example is better served by taking ownership of stdout, reassigning it to a new filedescriptor and replacing regular stdout with /dev/null. This way the output will be undisturbed by stray log calls.

**Comment by SUPERCILEX** [comment]
Yeah, I guess the example is kinda bad. I think the main point for this issue is that it'd be nice for ManuallyDrop to support "passthrough traits". Granted a feature like that probably requires an RFC so I'm fine with the ACP being closed now that it's hopefully a little searchable.

**Comment by SUPERCILEX** [comment]
Closing as I don't think this is actionable.
