### ISSUE TITLE
Support extracting underlying filled buffer from BorrowedBuf

### ISSUE THREAD

**Issue by SUPERCILEX** [rust-lang/libs-team#473]
# Proposal

## Problem statement

I'd like to be able to modify a MaybeUninit buffer and return the contents to the caller.

## Motivating examples or use cases

Currently, if a function wishes to safely modified a MaybeUninit buffer passed in by reference by the caller, they cannot return the filled buffer to the caller.

Fixing this would let the following code compile:
```rust
pub fn direct_file_name(
    buf: &mut [MaybeUninit<u8>; DIRECT_FILE_NAME_LEN + 1],
    to: RingKind,
    index: u32,
) -> DirectFileNameToken<()> {
    let mut buf = BorrowedBuf::from(buf.as_mut_slice());
    write!(buf.unfilled(), "{:0>13}\0", composite_id(to, index)).unwrap();
    DirectFileNameToken(buf.filled_mut(), PhantomData) // Doesn't compile!
}
```

## Solution sketch

Add two methods:
```rust
fn into_filled(self) -> &'data [u8]
fn into_filled_mut(&mut self) -> &'data mut [u8]
```

## Alternatives

Transmute to get lifetime extension or manually convert the MaybeUninits to u8s by using the filled length. Both of these solutions are very error prone and annoying to write.

**Comment by Amanieu** [comment]
We discussed this in the libs-api meeting and we're happy with these methods.

**Comment by joshtriplett** [comment]
Quick correction: `into_filled_mut` has the wrong signature, it should take `self`.

**Comment by joshtriplett** [comment]
Looks like https://github.com/rust-lang/rust/pull/132533 is correct and this was just a typo in the ACP.

**Comment by SUPERCILEX** [comment]
Oops, yeah sorry . Fixed.
