### ISSUE TITLE
Implement io::Write for UnixDatagram

### ISSUE THREAD

**Issue by tisonkun** [rust-lang/libs-team#480]
# Proposal

## Problem statement

UnixDatagram should be trivially able to implement `io::Write` and it fits in this category.

## Motivating examples or use cases

Straightforward.

## Solution sketch

See the pull request:

## Alternatives

N/A

**Comment by kennytm** [comment]
why should `UnixDatagram` implement `Write`? `UdpSocket` does not implement `Write` either.

(`UnixStream` does implement `Write` similar to `TcpStream`)

`Write` (and `Read`) assumes a stream-like target, where you can freely split or combine bytes, i.e. the following two calls are indistinguishable for the *receiver end* of the TCP socket:

```rust
// 1.
stream.write(b"hello, ")?;
stream.write(b"world!")?;

// 2.
stream.write(b"hello, world!")?;
```

UDP sockets don't work like that, every call to `.send()` defines the boundary of the packet, so the receiver of a UDP socket will be able to distinguish these:

```rust
// 3.
datagram.send(b"hello, ")?;
datagram.send(b"world!")?;
// the other end will always .recv() two packets

// 4.
datagram.send(b"hello, world!")?;
// the other end will always .recv() one packet 
```

This means if you simply forward `.write()` to `.send()`, convenient functions like `.write_all()` will not work correctly.

**Comment by tisonkun** [comment]
@kennytm Thanks for your information! This makes sense.
