### ISSUE TITLE
Docs - type guarantees update

### ISSUE THREAD

**Issue by WiktorPrzetacznik** [rust-lang/libs-team#482]
# Proposal

## Problem statement

Some type guarantees in docs are not precise enough.

## Motivating examples or use cases

The lack of precision can be misleading and introduces unnecessary complexity, like Pin::map_unchecked

> This function is unsafe. You must guarantee that the data you return will not move so long as the argument value does not move (for example, because it is one of the fields of that value), **and also that you do not move out of the argument you receive to the interior function**.

There's no way to do so, I'm pretty sure this is just a copy-paste from Pin::map_unchecked_mut

Another worth noting example is String::reserve (and other types based on Vec):

> Panics if the new capacity overflows usize.

The more accurate would be informing that it panics if exceeds [`isize::MAX`] bytes.

## Solution sketch

Update documentation of:

- Pin::map_unchecked 
- String::reserve, String::reserve_exact 
- Saturating 

Precise information about what I'm proposing to change can be found in the related open [PR #129822](https://github.com/rust-lang/rust/pull/129822)

## Alternatives

1. Leaving the docs as they are now.
2. Moving Vec's related docs about panicing when exceeding usize into some other place, so it doesn't have to be changed in every related type.

## Links and related work

[PR #129822 - docs changes proposal](https://github.com/rust-lang/rust/pull/129822)
[forum discussion about Pin::map_unchecked](https://internals.rust-lang.org/t/why-am-i-not-allowed-to-move-arg-in-pin-map-unchecked/19664/2?u=wiktor)
[forum discussion - Is Saturating<T> guaranteed to have the same layout and ABI as T?](https://internals.rust-lang.org/t/is-saturating-t-guaranteed-to-have-the-same-layout-and-abi-as-t/21476)

**Comment by Amanieu** [comment]
This doesn't need an ACP, I've re-rolled the PR for a libs-api member.
