### ISSUE TITLE
OsString::truncate

### ISSUE THREAD

**Issue by lolbinarycat** [rust-lang/libs-team#486]
# Proposal

## Problem statement

Truncating an `OsString` without using unsafe code.

## Motivating examples or use cases

re-using a `PathBuf` by repeatedly truncating it to its original length. 

## Solution sketch

Modeled after `String::truncate` and `OsStr::slice_encoded_bytes`.

```
/// Panics if `new_len` does not lie on an `OsStr` boundry.
pub fn truncate(&mut self, new_len: usize)
```
## Alternatives

* There is a workaround to do this without this function, but it requires a complicated dance with `std::mem::swap` and `from_encoded_bytes_unchecked`.
* Also partially possible by calling `PathBuf::pop` in a loop, but this is less effecient, especially for long paths. 

## What happens now?

This issue contains an API change proposal (or ACP) and is part of the libs-api team [feature lifecycle]. Once this issue is filed, the libs-api team will review open proposals as capability becomes available. Current response times do not have a clear estimate, but may be up to several months.

[feature lifecycle]: https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html

## Possible responses

The libs team may respond in various different ways. First, the team will consider the *problem* (this doesn't require any concrete solution or alternatives to have been proposed):

- We think this problem seems worth solving, and the standard library might be the right place to solve it.
- We think that this probably doesn't belong in the standard library.

Second, if there's a concrete solution:

- We think this specific solution looks roughly right, approved, you or someone else should implement this. (Further review will still happen on the subsequent implementation PR.)
- We're not sure this is the right solution, and the alternatives or other materials don't give us enough information to be sure about that. Here are some questions we have that aren't answered, or rough ideas about alternatives we'd want to see discussed.

**Comment by pitaj** [comment]
This would be useful indeed. I'd recommend including a `clear` function as well, equivalent to `truncate(0)`

**Comment by lolbinarycat** [comment]
> This would be useful indeed. I'd recommend including a `clear` function as well, equivalent to `truncate(0)`. String and Vec both have one.

[already exists](https://doc.rust-lang.org/stable/std/ffi/os_str/struct.OsString.html#method.clear)

**Comment by Amanieu** [comment]
We discussed this in the libs-api meeting and are happy to accept this! When writing the documentation, we should be careful to properly specify what the boundary is and that it is platform-specific.

**Comment by joshtriplett** [comment]
By way of examples, the documentation could mention that you can expect to always get a valid truncate boundary by:
- Recording a previous length of the string, appending something, then truncating it to its previous length.
- Subtracting the length of a trailing path component from the end of the string.

**Comment by lolbinarycat** [comment]
Shouldn't [OsStr::slice_encoded_bytes](https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html#method.slice_encoded_bytes) be amended to also note these are valid ways of finding a boundary?

Also, I'll start work on implementing this right away.
