### ISSUE TITLE
Infallible version of fetch_update

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/libs-team#490]
# Proposal

## Problem statement

`fetch_update` requires you to return an `Option` and handle the `Err` case. Sometimes you don't need to do that

## Motivating examples or use cases
```rs
        my_atomic
            .fetch_update(Ordering::SeqCst, Ordering::SeqCst, |current| {
                Some(current + 10 % 50)
            })
            .expect("This can't return None");
```
## Solution sketch

An alternative infallible function that doesn't require that:
```rs
    pub fn infallible_fetch_update<F>( // Name TBD
        &self,
        set_order: Ordering,
        fetch_order: Ordering,
        mut f: F,
    ) -> u64
    where
        F: FnMut(u64) -> u64,
```

## Links and related work

https://rust-lang.zulipchat.com/#narrow/channel/327149-t-libs-api.2Fapi-changes/topic/Atomics.20fetch_update.20is.20awkward

## What happens now?

This issue contains an API change proposal (or ACP) and is part of the libs-api team [feature lifecycle]. Once this issue is filed, the libs-api team will review open proposals as capability becomes available. Current response times do not have a clear estimate, but may be up to several months.

[feature lifecycle]: https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html

## Possible responses

The libs team may respond in various different ways. First, the team will consider the *problem* (this doesn't require any concrete solution or alternatives to have been proposed):

- We think this problem seems worth solving, and the standard library might be the right place to solve it.
- We think that this probably doesn't belong in the standard library.

Second, if there's a concrete solution:

- We think this specific solution looks roughly right, approved, you or someone else should implement this. (Further review will still happen on the subsequent implementation PR.)
- We're not sure this is the right solution, and the alternatives or other materials don't give us enough information to be sure about that. Here are some questions we have that aren't answered, or rough ideas about alternatives we'd want to see discussed.

**Comment by GrigorenkoPV** [comment]
Bikeshed: fetch_update_infallible

**Comment by Amanieu** [comment]
We discussed this in the libs-api meeting: we're happy to accept this as `fetch_update_infallible`. We're not huge fans of the name but couldn't think of anything better (ideallly `fetch_update` should have been called `try_fetch_update`, but that ship has sailed).
