### ISSUE TITLE
Implementing `AsRef<T> for T` for all the stdlib's types

### ISSUE THREAD

**Issue by elichai** [rust-lang/libs-team#492]
# Proposal
Implement `AsRef<T>` for all of the Standard Library's types (or at least for primitives)
## Problem statement
`AsRef` cannot be reflexive, so we don't get `AsRef<T> for T` for free.
A lot of times in rust when you write generic code you just want a reference of the thing, so you reach for `AsRef<T>` which works great when it's `AsRef<str>` or `AsRef<[T]>` but when you get to things like `AsRef<u32>` you're not stuck, as even `u32` doesn't implement `AsRef<u32>`

## Motivating examples or use cases
Consider the following trait:
```rust
trait Encoding: Sized {
    type Encoded<'a>: AsRef<Self::EncodingRef> where Self: 'a;
    type EncodedRef: ?Sized;

    fn encode(&self) -> Self::Encoded<'_>;
    fn decode(v: impl AsRef<Self::EncodedRef>) -> Self;
}
```
You can instantiate it with `Encoding<Encoded=String, EncodedRef=str>` or even `Encoding<Encoded=&'a str, EncodedRef=str>` but if you want to implement this trait for e.g. `u32`  you can't use the trait at all.
## Solution sketch

Manually implement `AsRef<T> for T` for all library types

## Alternatives
1. Find a way to make `Asref<T> for T` not conflict with `impl<U, T: AsRef<U>> AsRef<U> for &T`.
2. Add a `AsRef` derive macro that implements a reflexive `AsRef` to simplify the manual implementation. 

Zulip thread: https://rust-lang.zulipchat.com/#narrow/channel/122651-general/topic/Implementing.20.60AsRef.3CT.3E.20for.20T.60.20for.20all.20the.20stdlib's.20types

**Comment by cuviper** [comment]
> Find a way to make `Asref<T> for T` not conflict with `impl<U, T: AsRef<U>> AsRef<U> for &T`.

New blanket impls are also a breaking change -- this conflict with downstream `impl AsRef<Foo> for Foo`. Specialization might work for this, but I don't think we want any API that *depends* on specialization.

**Comment by Amanieu** [comment]
We discussed this in the libs-api meeting and felt that this would likely cause a lot of type inference failures in uses of `as_ref` in the ecosystem. We didn't think that the benefit would outweigh the costs of the potential breakage.
