### ISSUE TITLE
`CStr::from_bytes_with_nul` returns non-actionable error result

### ISSUE THREAD

**Issue by nyurik** [rust-lang/libs-team#493]
# Proposal

## Problem statement

One of `CStr` constructors, `CStr::from_bytes_with_nul(bytes: &[u8])` handles 3 cases:
1. `bytes` has one NULL as the last value - creates CStr
2. `bytes` has no NULL - error
3. `bytes` has a NULL in some other position - error

The 3rd case is error that may require lossy conversion, but the 2nd case can easily be handled by the user code. Unfortunately, this function returns an opaque `FromBytesWithNulError` error in both 2nd and 3rd case, so the user cannot detect just the 2nd case - having to re-implement the entire function and bring in the `memchr` dependency.

## Motivating examples or use cases

In [this code](https://github.com/gquintard/varnish-rs/blob/f86d7a87683b08d2e634d63e77d9dc1d24ed4a13/varnish-sys/src/vcl/ws.rs#L158), my FFI code needs to copy user's `&[u8]` into a C-allocated memory blob in a NUL-terminated `CStr` format.  My code must first validate if `&[u8]` has a trailing NUL (case 1), no NUL (adds one on the fly - case 2), or NUL in the middle (3rd case - error). I had to re-implement `from_bytes_with_nul` and add `memchr`dependency just to handle the 2nd case.

## Solution sketch

It may make sense to do one of these:
* stabilize the `kind` of the error this function returns - so it can be examined
* introduce a new function that returns validation result for all 3 cases
* something else?

`CStr::validate_bytes(value: &[u8]) -> CStrValidation` -- returns an enum with `valid, NotNulTerminated,  InteriorNul`

**Comment by kennytm** [comment]
Exposing the `kind()` should be the most natural, as that `kind` private field is already there.

**Comment by pitaj** [comment]
I think it makes sense to add a `kind()` method to the type which returns the failure mode. 

However, I am a little confused as to why you needed to reimplement the function. Seems like you could just check `bytes.last() == Some(0)` before calling `from_bytes_with_nul` instead.

**Comment by nyurik** [comment]
Thx @Amanieu , are you saying that the `enum FromBytesWithNulErrorKind` should be renamed into `enum FromBytesWithNulError` , and the `struct FromBytesWithNulError` deleted?

**Comment by Amanieu** [comment]
Yes, essentially.

**Comment by nyurik** [comment]
wouldn't this be a breaking change?

**Comment by cuviper** [comment]
It's mostly opaque, but one way it breaks is that pattern `FromBytesWithNulError { .. }` works now with a struct, and won't work with an enum.

**Comment by nyurik** [comment]
so i guess its no biggie.  I can submit a PR in a sec

**Comment by nyurik** [comment]
PR here https://github.com/rust-lang/rust/pull/134143
