### ISSUE TITLE
TrySendError method to get the user data

### ISSUE THREAD

**Issue by SUPERCILEX** [rust-lang/libs-team#498]
# Proposal

## Problem statement

Not much of a problem, but it's annoying to have to match on the error to get my data back:
```rust
match e {
    TrySendError::Full(cmd) => cmd,
    TrySendError::Disconnected(cmd) => cmd,
}
```

## Solution sketch

```rust
impl std::sync::mpsc::TrySendError<T> {
  fn into_inner(self) -> T;
}
```

## Alternatives

Write the match every time or write your own helper method.

The `into_inner` method could be bad in the sense that it obviates the need for the user to think about whether or not they should handle Full vs Disconnected errors differently.

**Comment by SUPERCILEX** [comment]
Just realized you can write it like this which is maybe good enough?
```rust
let (TrySendError::Full(cmd) | TrySendError::Disconnected(cmd)) = e;
```

**Comment by kennytm** [comment]
I think there is no harm adding `TrySendError::into_inner` (and `get_ref` and `get_mut`). 

For `SendError` you could just use `e.0`

**Comment by SUPERCILEX** [comment]
Oh good point about `SendError`, I was working with `TrySendError` and didn't realize the variants were different.

**Comment by Amanieu** [comment]
We discussed this in the libs-api meeting. We're happy to add this but it should also be added upstream in crossbeam.
