### ISSUE TITLE
Poisoning Survey

### ISSUE THREAD

**Issue by KodrAus** [rust-lang/libs-team#5]
Hey @rust-lang/libs! We’ve been talking on Zulip about possibly splitting `std::sync` into new top-level modules like `std::mutex` and “fixing” a few design decisions along the way. One of those is removing poisoning from `Mutex` and `RwLock`. That’s a big change to consider, so to first get an idea of how poisoning is used in projects we’ve put together a survey and accompanying blog post for the main blog.

I’ve made this issue to:

- Make sure we’re all happy with this post and survey representing the Libs team.
- Make sure we’re all happy with the content and questions themselves.
- See if anybody would like to be added to the survey so they can edit it and see the raw results too.

[The blog post HackMD](https://hackmd.io/icmi6sjlRcKkL9T49iQiDg?both)

[The survey Google Form](https://docs.google.com/forms/d/e/1FAIpQLSehk-GkwoCag_w3YfXDfgeANulR0h5m2d3EzUMQaiY1vRfIEw/viewform)

**Comment by KodrAus** [comment]
I wonder if this works here...

@rfcbot fcp merge

**Comment by KodrAus** [comment]
That’s a no 😄

**Comment by LukasKalbertodt** [comment]
Thanks a lot for the blog post. In fact, before reading it, I didn't understand why most of you (libs people) want to remove poisoning. To me it seemed like a very useful concept. But yeah, maybe locks and "upholding invariants"/poisoning shouldn't be complected into one type.

---

Some notes about the survey:

> If not, would you use an implementation from the standard library [...]

Just to make it completely clear, I would say "If not, would you use a **poisoning** implementation from the standard library [...]".

> Do you use the poisoning behavior of the standard library’s lock types in any of your projects?

This is a bit confusing IMO. Technically, the answer is "yes", everyone who uses those lock types uses poisoning behavior, as the standard library has no opt-out. I think this question wants to ask whether people use the poisoning behavior deliberately/in a useful way, right? 

Maybe something like "Do you use the poisoning behavior in a useful way?". Or changing the yes/no question to "How do you use the poisoning aspect of the std lock types?" with answers "I always `unwrap`", "I always `err.into_inner()`" and "I use it to ensure my invariants are not broken".

> How much churn [...]

In the blog post this was changed to "friction". It should probably changed in the survey as well?

**Comment by KodrAus** [comment]
cc @dtolnay @sfackler @withoutboats I've updated the survey based on some of the feedback we got on Zulip. Are we happy to publish this?

**Comment by dhardy** [comment]
May I add some concerns about the blog post?

1.  It does not talk about the alternative: how poisoning might be implemented in user-space. This should be fairly trivial, but would still be nice to see.
2.  It mentions:
    > The machinery needed to do this adds a non-trivial cost to using the standard locks. It comes with an ergonomic cost in having to call .lock().unwrap(), and a runtime cost in having to maintain thread-local state to track panics.
    
    We also know that "premature optimisation is the root of all evil", right? The problem here is that a cost is mentioned with no metric or context (bearing in mind that use of locks and thread-switching has its own costs too).

**Comment by KodrAus** [comment]
Thanks for the input @dhardy!

I think discussing how poisoning could be implemented yourself is probably out-of-scope for this post.

At this stage I definitely wouldn't consider optimizations on `std::sync::Mutex` that reduce its size in memory or the amount of work it needs to do during synchronization "premature", but since `parking_lot` has a few benchmarks maybe we could include some results of those to give a clearer picture of what's being left on the table with poisoning.
