### ISSUE TITLE
Make FromStr on integers const

### ISSUE THREAD

**Issue by GKFX** [rust-lang/libs-team#74]
# Proposal
Make FromStr on integers const, as well as the parse() method so that `"12".parse::<u32>()` is const. (Edit: and the u32::from_str_radix functions, since it's the same implementation.)

## Problem statement

There is currently no convenient way to convert a numeric string into a an integer at compile time.

## Motivation, use-cases

Reading numeric environment variables at compile time into integer constants.

## Solution sketches

https://github.com/rust-lang/rust/pull/99322

## Links and related work

https://github.com/rust-lang/rfcs/issues/1907
https://github.com/rust-lang/rust/issues/59133

## What happens now?

This issue is part of the libs-api team [API change proposal process]. Once this issue is filed the libs-api team will review open proposals in its weekly meeting. You should receive feedback within a week or two.

[API change proposal process]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html

**Comment by thomcc** [comment]
I think this is something we eventually want -- myself I've wanted this pretty badly before, badly enough to write <https://github.com/thomcc/envparse> (... but I suppose not badly enough to finish and publish it).

Either way, I'm in favor of it, since it comes up pretty often in my experience.

That said, actually using const trait impls seems to be a ways off, so I don't know where that fits in here.

**Comment by GKFX** [comment]
I've added making `u32::from_str_radix` (etc) const to the merge request. Would that be easier to stabilize, in that it doesn't go via the `FromStr` trait so doesn't involve using a const trait impl?

**Comment by scottmcm** [comment]
From a lang perspective, the details of `const` traits are too uncertain right now to be something I'd be willing to expose in std.  (I do expect we'll get something in the space eventually, but I'm unsure what exactly.)

So if you can pare this down to just making an inherent method const, that's probably a good plan.  Then it's just a libs-impl question of whether removing any impls used in the implementation in favour of macros would be ok.
