### ISSUE TITLE
`Cow` for `core`

### ISSUE THREAD

**Issue by daxpedda** [rust-lang/libs-team#76]
# Proposal

## Problem statement

`Cow` is not available in `core`.
A common pattern when designing allocation-free APIs is to use `Cow` in parameters and structures, it's not possible to share the same API between `no_std` with and without `alloc` without access to `Cow` in `core`.

## Motivation, use-cases

Designing allocation-free APIs that supports `no_std` with and without `alloc` with `Cow` is not possible.
Currently two alternatives present themselves:
- Changing the API when `alloc` is active.
- Have two different APIs with and without `Cow`.

The first solution is terrible for user experience, the second is still a problem because it requires duplicate implementation.

### Proposed Solution
Proposed by @scottmcm.

In `core`:
```rust
pub enum Cow<'a, B, O> {
    Borrowed(&'a B),
    Owned(O),
}
```
In `alloc`:
```rust
type Cow<'a, B, O = <B as ToOwned>::Owned> = core::borrow::Cow<'a, B, O>;
```

### Alternative

Move all of `alloc::borrow` to `core`, but leave incompatible `ToOwned` implementations in `alloc`. This is currently not possible because of coherence rules.

We could implement some internal mechanism to circumvent coherence rules for this case, but as pointed out by @chorman0773, this is incompatible with specialization:
```rust
/// `core`
pub trait ToOwned { .. }

/// crate `A`: links `core`
pub trait Foo { .. }
default impl<T: ?Sized> Foo for T { .. }
impl<T: ?Sized + ToOwned> Foo for T { .. }

pub trait Bar { .. }
impl<T: ?Sized + Foo> Bar for T { .. }

// Use `[u32] as Bar` in crate `A`.

/// `alloc`
impl<T: Clone> ToOwned for [T] { .. }

/// crate `B`: links `core`, `A` and `alloc`
// Use `[u32] as Bar` in crate `B`.
```

This would cause conflicting implementations or different ones depending if `alloc` is present or not.
To fix this, a suggestion would be to add placeholder implementations, that aren't usable in `core` but are filled out and can be used in `alloc`.

I have no experience or much knowledge of the the rustc codebase, but I'm going to assume that such a mechanism is quiet difficult to implement. But maybe there are other use-cases for this mechanism out there that could make it viable after all.

## Links and related work

https://internals.rust-lang.org/t/move-alloc-borrow-to-core/17055
https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/.60alloc.3A.3Aborrow.60.20for.20.60core.60

**Comment by CAD97** [comment]
Even without moving `Cow` to `core`, adding a generic for the owned variant would be interesting.

> We could implement some internal mechanism to circumvent coherence rules

rustc std has `#[rustc_incoherent_impl]` available, but it does need to be used carefully to avoid issues like you list. It's necessary even ignoring trait implementations, in order to add `Cow::to_mut` and `Cow::into_owned`, which require `B: ToOwned<Owned=O>`.

A placeholder trait implementation is unprecedented and would require significant work. That probably blocks that alternative on the "portability lint" and std/core unification.

**Comment by daxpedda** [comment]
> rustc std has `#[rustc_incoherent_impl]` available

That's good to know!
> That probably blocks that alternative on the "portability lint" and std/core unification.

I couldn't find anything on std/core unification, where can I find information on this?

**Comment by CAD97** [comment]
See https://rust-lang.github.io/rfcs/1868-portability-lint.html for the portability lint's original conceptualization. After that it's really just arbitrarily spread throughout development discussions around the ideal future, but it's still a *long* ways off. `-Zbuild-std` in cargo is perhaps the most recent progress towards subsetting std and retiring the facade.

**Comment by shepmaster** [comment]
I’m not clear how the core version deserves the name “clone on write” because there aren’t any related traits applied in the example. Is it really a different name?

**Comment by daxpedda** [comment]
Considering that `ToOwned` won't be in `core` in this proposition, "clone on write" is indeed misleading.
@shepmaster would you have an idea for an alternative name? (I can only think of `BoW`, "borrowed or owned")

**Comment by scottmcm** [comment]
> because there aren’t any related traits applied in the example

The *type* definition for `HashMap` doesn't have any related traits applied either, so that's not necessarily a problem.  It could have copy-on-write intent even without it.

(But it's also possible that `BorrowOrOwn`-style names could be better anyway.)

**Comment by m-ou-se** [comment]
> ## Problem statement
> 
> `Cow` is not available in `core`.

I think this needs a bit more explanation. Why is this a problem? ("{x} is not available in core" is true for many many types, but we don't consider that a problem, usually.)

**Comment by daxpedda** [comment]
There is no real problem per-se, there is only a use-case that isn't covered.
I'm not sure what to do here, I can move the use-case into the "Problem statement", but then "Motivation, use-cases" will be empty.

**Comment by shepmaster** [comment]
What would a no_std API do with a `Cow` argument without the ability to convert it to the owned variant? Would that use case be covered by taking a generic type that implements `AsRef` or `Borrow`?

**Comment by BurntSushi** [comment]
> What would a no_std API do with a `Cow` argument without the ability to convert it to the owned variant? Would that use case be covered by taking a generic type that implements `AsRef` or `Borrow`?

I've got one for ya! :) https://github.com/BurntSushi/memchr/blob/8037d11b4357b0f07be2bb66dc2659d9cf28ad32/src/cow.rs#L3-L10

The actual API does indeed take a `AsRef<[u8]>`: https://docs.rs/memchr/latest/memchr/memmem/struct.Finder.html#method.new

So, when you're without std, you can still use `Finder`, but you gotta deal with the lifetime. But with std, you can turn the `Finder` into an owned type.

Now, if `Cow` were in core, I think I'd still need to write at least a little bit of conditional code? Honestly, I'm not sure if my pattern above would still work. What would the "owned" type be in no_std mode for example?

(Note that I am not necessarily saying my use case justifies putting `Cow` in core, especially if doing so requires weird shenanigans. And defining my own `CowBytes` took very very little effort.)

**Comment by CAD97** [comment]
`AsRef` isn't sufficient, as `AsRef` isn't reflexive. (And it can't be made reflexive without impl specialization at a minimum to make the change formally nonbreaking.)

Without an `IntoOwned` bound, taking `impl Borrow` is almost sufficient to capture the behavior of taking `Cow`; the two exceptions are:

- Taking `Cow` is less polymorphic, thus (in theory) less expensive to monomorphize.
- Taking `Cow` allows you to handle the owned and borrowed cases differently even if you can't convert borrowed -> owned.


But in general I agree that APIs are better off taking `&T` than `Cow<T>`-without-`IntoOwned`.

<aside><small>(Personally, I think taking `impl Borrowed<T>` or `impl AsRef<T>` without further bounds is an antipattern. One std enjoys with `impl AsRef<Path>`, but which trips up developers passing (potentially cloned) `PathBuf` ownership where passing a reference is sufficient. `AsRef`-as-autoderef for function arguments *is* convenient, but IMHO prioritizes reading over writing/editing too much.)</small></aside>

**Comment by daxpedda** [comment]
Te problem of `Cow` without `ToOwned` makes sense to me, but I can't really figure where to go from there because I don't have a specific use-case for this situation.

However, my specific use, definitely does make sense without `ToOwned`. I use `Cow` not for it's "clone on write" ability, but specifically because I want to handle borrowed or owned data with the same interface. The point would be to give the user the choice to handle their own memory or to get an owned value back.

```rust
struct State<'a> {
    data: Cow<'a, Data>,
}

/// Example A.

let state: State<'data> = State::new(Cow::Borrowed(&data));
// ... do stuff with this state, user has to make sure `data` survives.

/// Example B.

let state: State<'static> = State::new(Cow::Owned(data));
// ... do stuff with this state, user doesn't have to deal with the lifetime anymore.
```
This can also be solved with a generic `AsRef<Data>` instead of the lifetime, but that would complicate something like this:
```rust
fn do_something_with_multiple_states<S1: AsRef<Data>, S2: AsRef<Data>, S3: AsRef<Data>>(s1: S1, s2: S2, s3: S3) { .. }
```
This can get quickly out of hand.

I've also had use-cases with `Cow<'static, Data>`, when you definitely want to own the data but want to support using globals without having to copy them each time.

---

Clearly my description in OP is misleading. Most of my use-cases only involve wanting a type representing owned or borrowed data, without all the other cool functionality that `Cow` offers.
I constantly hit this problem when designing `no_std` allocation free APIs and I always end up hand-rolling `Cow` for that.

I will update OP tmrw, I currently have a broken arm and can only write with one hand, it's rather slow writing all of this, apologies for the delays.

**Comment by robertbastian** [comment]
This would also be useful for alloc-free deserialization. If I have a data struct like
```rust
#[derive(serde::Deserialize, serde::Serialize)]
struct Data<'a>(Cow<'a, str>);
```
I cannot currently use it in `#[no_std]` without `alloc`. The similar struct
```rust
#[derive(serde::Deserialize, serde::Serialize)]
struct Data<'a>(&'a str);
```
works, but it cannot be used with for example `serde_json`, which cannot deserialize a string into `&'de str` (it has to allocate if there are escape sequences).

The hacky workaround would be something like
```rust
#[cfg(not(feature = "alloc"))]
type Cow<'a, T> = &'a T;
```
but those are quite different types, so it's not great.

**Comment by m-ou-se** [comment]
> rustc std has `#[rustc_incoherent_impl]` available

We should use it as little as possible though. (I personally think we should stop using it for new things entirely.)

**Comment by daxpedda** [comment]
> It sounds like this is not an attempt at a 'copy/clone on write' type in core, but rather an attempt at a 'borrowed or owned' type.

Indeed.

> I don't think this should be an extension/generalization of Cow.

Yeah, maybe this should be a new type with a whole RFC and what-not.

> (And I'm not sure if this should be a type in std/core at all, instead of just an enum you can define in a few lines in your own crate.)

Currently `Cow` is "abused" for exactly this kind of requirement basically everywhere. It would be nice if a type actually fulfilling these requirements could be in std/core, otherwise we would end up with a thousand custom types in all sort of libraries that aren't compatible with each other. Or ideally, there would be one popular library everybody agrees on.

This argument: "put it in std/core to have one type everybody can agree on", is probably an argument Rust has heard often, I completely lack the context how this has played out before and what the view and arguments are on this topic.

In any case, I will close this. Somebody with more time on their hands could open an RFC on this, if there is enough interest.

**Comment by m-ou-se** [comment]
> Currently Cow is "abused" for exactly this kind of requirement basically everywhere. It would be nice if a type actually fulfilling these requirements could be in std/core

That's very valid. I'd be happy to see an RFC for something like that.

**Comment by Conaclos** [comment]
Has an RFC been opened?
