### ISSUE TITLE
Implement `PartialEq` for boxed slices

### ISSUE THREAD

**Issue by CraftSpider** [rust-lang/libs-team#79]
# Proposal

## Problem statement

Currently, boxed slices aren't as ergonomic as vectors in some scenarios. In particular when working with generics, due to certain missing trait impls.

## Motivation, use-cases

A simple example of the current issue. This can be worked around with a newtype, or by instead storing a slice, but both of those have ergonomic issues:

```rs
struct Container<T> { ... }

impl Container<T> {
    fn find<U: PartialEq<T>>(foo: &U) {
        ...
        if foo == val {
            ...
        } else {
            ...
        }
    }
}

fn usage() {
    let container = Container::<Box[usize]>::new();
    // ERROR: No impl PartialEq<Box<[usize]>> for [usize] (can reverse bound to reverse the requirement)
    container.find(&[0]);
}
```

`impl PartialEq<T> for Box<T>` and friends wouldn't work, as due to Box being fundamental, downstream crates may have already written such impls. However, downstream users cannot implement the same on slices, as that situation it becomes an impl for an upstream trait on an upstream type. If we did ever wish to add such impls despite that fact, this change is forward-compatible, as they are strictly more general than the proposed changes.

## Solution sketches

Add `impl PartialEq<[T]> for Box<[T]>` and friends.

Most alternatives other than the status quo aren't feasible due to being breaking, as covered above.

## Links and related work

implementation: https://github.com/rust-lang/rust/pull/100131

## What happens now?

This issue is part of the libs-api team [API change proposal process]. Once this issue is filed the libs-api team will review open proposals in its weekly meeting. You should receive feedback within a week or two.

[API change proposal process]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html

**Comment by thomcc** [comment]
As a fairly frequent user of `Box<[T]>`, I'm in favor of this in principal, but I'm not really sure it's worth it if this change breaks causes many inference failures, which is a concern I'd have (easy to test with crater if we would like it, though).

(In practice I do find I have to do `&box_slice[..]` fairly often to force comparisons and the like to work as I need, but this is already true anyway).

**Comment by CraftSpider** [comment]
I already have the PR open, so running crater on it sounds like a good idea to me. I'm not sure the invocations or if I have the privileges needed, but if someone with permission wants to.

**Comment by m-ou-se** [comment]
This seems to be the kind of change that easily leads to an explosion of trait implementations, since there are many combinations of container/wrapper that could have a similar trait implentation.

It seems your use case is quite similar to that of `HashMap::get`, which uses the `Borrow` trait to allow using a slightly different type than the element type. Would that suffice for your use case?

**Comment by CraftSpider** [comment]
It wouldn't, due to some specifics of my use-case.

<details>
<summary>Implementation details</summary>

In short, it takes an item by value and needs to:
- Find it in the container
- If it exists, return the existing item
- If it doesn't exist, convert the passed item into a T and store it in the container (Via a custom trait like `ToOwned` but that works by-value to avoid cloning in the case the type is already a T)

The need to take the item by value when it is *sometimes* a ref is the main issue, because trying to use `Borrow` or `AsRef` or similar on the parameter type nets me the need for the container type to be both `Borrow<&[T]>` (which `Box<[T]>` is not) and `Borrow<Box<[T]>>` (which `Box<[T]>` is). Putting it on the contained type isn't possible, because I want to be generic over other non-dereferencable types. I've tried a series of other trait bounds and orders, but none of them let me keep the zero-copy nature of the API while also allowing this functionality aside from a custom SliceWrapper that implements `PartialEq` as desired.

(And all this is for efficiency, and benchmarking supports that this actually is a bottleneck in this code - skipping the clone in good cases is quite worth it)

</details>

Separately, I would argue that implementing `PartialEq` for slices on more types is generally a good thing. It's an implementation the user cannot write, and many types already have special APIs for `[T]`. `Box`, `Rc`, `Vec`, etc already treat slices as special, with common implementations to make working with them more ergonomic. I feel that it makes sense to include more trait implementations where they make sense for this kind of thing, rather than encouraging users to have to work around missing features just to get ergonomics for a fairly reasonable type to write.

**Comment by cuviper** [comment]
> `Borrow<&[T]>` (which `Box<[T]>` is not)

It is `Borrow<[T]>` though. Can you explain why you want `Borrow<&[T]>`?

`Borrow<&X>` is weird because that would double-up the return reference `borrow(&self) -> &Borrowed`, i.e. `-> &&X`, which means the only types that could implement that must already have an actual `&X` reference themselves, not just an `X` they can point to.

**Comment by CraftSpider** [comment]
It's the 'takes an item by value' part - I have to take a `T`, not a `&T`, so if I pass a slice `T` is `&[U]`, a boxed slice `T` is `Box<[U]>`. I don't *want* the double ref, but I can't pass `[U]` directly.

**Comment by dead-claudia** [comment]
Came up with a simpler proposal that covers this naturally: https://github.com/rust-lang/libs-team/issues/206

There is a caveat noted in the initial comment to be aware of, though.

**Comment by dtolnay** [comment]
> This seems to be the kind of change that easily leads to an explosion of trait implementations, since there are many combinations of container/wrapper that could have a similar trait implentation.

The current set of slice-related PartialEq impls is:

| PartialEq&lt;:arrow_down:&gt; for :arrow_right: | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 |
|:--|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
| 1. **`[T]`** | :green_heart: | :green_heart: | | | | | :green_heart: | | | | | |
| 2. **`[T; N]`** | :green_heart: | :green_heart: | :green_heart: | :green_heart: | | | :green_heart: | :green_heart: | | | | |
| 3. **`&[T]`** | | :green_heart: | :green_heart: | :green_heart: | :green_heart: | :green_heart: | :green_heart: | :green_heart: | :green_heart: | | | |
| 4. **`&mut [T]`** | | :green_heart: | :green_heart: | :green_heart: | :green_heart: | :green_heart: | :green_heart: | :green_heart: | :green_heart: | | | |
| 5. **`&[T; N]`** | | | :green_heart: | :green_heart: | :green_heart: | :green_heart: | :green_heart: | :green_heart: | | | | |
| 6. **`&mut [T; N]`** | | | :green_heart: | :green_heart: | :green_heart: | :green_heart: | | :green_heart: | | | | |
| 7. **`Vec<T>`** | :green_heart: | | :green_heart: | :green_heart: | | | :green_heart: | :green_heart: | :green_heart: | | | |
| 8. **`VecDeque<T>`** | | | | | | | | :green_heart: | | | | |
| 9. **`Cow<[T]>`** | | | | | | | | | :green_heart: | | | |
| 10. **`Box<[T]>`** | | | | | | | | | | :green_heart: | | |
| 11. **`Rc<[T]>`** | | | | | | | | | | | :green_heart: | |
| 12. **`Arc<[T]>`** | | | | | | | | | | | | :green_heart: |

This ACP proposes filling in box 1:10 "and friends", which presumably refers to some chunk of row 10 and/or column 10.

We discussed this ACP in today's libs meeting and are not on board with where this is heading.

We'd recommend exploring an alternative of putting the concept of "slice-like" behind a (sealed) trait and implementing PartialEq generically for the above slice-like types, i.e. a whole entire column at a time.

While the rendered rustdoc of PartialEq may become less useful/explicit this way, that is not concerning. People do not go looking for PartialEq impls by hunting through the documentation of PartialEq until they find the one they want. Rather they write obvious code and are surprised when it does not work. Generically implementing PartialEq slice comparisons in a principled way would lead to obvious code doing the right thing in more cases, and thereby _fewer_ people having a bad experience with the documentation of those impls.
