### ISSUE TITLE
Remove the sort from test::filter_tests

### ISSUE THREAD

**Issue by saethlin** [rust-lang/libs-team#82]
# Proposal

## Problem statement

The startup time of `cargo miri test` becomes enormous on crates with a large number of tests.

## Motivation, use-cases

On `iced-x86` with `--features=code_asm,mvex`, startup time is currently 18 minutes. This makes using Miri on such codebases a very unpleasant experience.

## Solution sketches

There are a lot of factors that contribute to this huge startup time. The one that requires an API change is that `test::filter_tests` currently sorts the filtered tests before returning them. This sort can be done by the proc macro which builds the test runtime invocation instead, so that the behavior of `cargo test` is unchanged.

## Links and related work

This PR implements the suggested solution: https://github.com/rust-lang/rust/pull/99939

**Comment by pitaj** [comment]
The linked PR was merged, so this should probably be closed.
