### ISSUE TITLE
Include libs-team repo issues/PRs in generated agenda

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/libs-team#9]
It's easy to miss PRs/issues on this repository. It might be good to automatically put them in the triage agenda (or maybe only those with a label).

**Comment by KodrAus** [comment]
#8 suggests we include our MCPs so we can discuss them. We’ve only got one so far (#6), but I thought we could open them as pull requests here so they’re basically like mini Libs team RFCs.

**Comment by m-ou-se** [comment]
@yaahc Does your new generator include this repository?

**Comment by yaahc** [comment]
> @yaahc Does your new generator include this repository?

No but I could add it easily, I set it up so that you can run the same query against an arbitrary number of repos. I'll add it to the `I-Nominated` query for right now, lmk if you want me to look up any other tags as well.
